//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UILabel, _TtC8RedditUI10StepSlider;

@interface _TtC6Reddit17LabeledSliderView : UIView
{
    // Error parsing type: , name: label
    // Error parsing type: , name: slider
    // Error parsing type: , name: items
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithItems:(id)arg1 rui:(id)arg2 stepChangeHandler:(CDUnknownBlockType)arg3;
@property(nonatomic, readonly) NSArray *items;
@property(nonatomic, readonly) _TtC8RedditUI10StepSlider *slider; // @synthesize slider;
@property(nonatomic, readonly) UILabel *label; // @synthesize label;

@end

