//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC8RedditUI10FontConfig : NSObject
{
    // Error parsing type: , name: sizeDelta
    // Error parsing type: , name: useSystemSizeScaling
}

- (id)init;
@property(nonatomic, readonly) long long hash;
- (_Bool)isEqual:(id)arg1;
- (id)withSizeDelta:(double)arg1;
- (id)initWithSizeDelta:(double)arg1 useSystemSizeScaling:(_Bool)arg2;
@property(nonatomic, readonly) _Bool useSystemSizeScaling; // @synthesize useSystemSizeScaling;
@property(nonatomic, readonly) double sizeDelta; // @synthesize sizeDelta;

@end

