//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC6Reddit14StepSliderItem : NSObject
{
    // Error parsing type: , name: title
    // Error parsing type: , name: value
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithLabel:(id)arg1 value:(id)arg2;
@property(nonatomic, readonly) NSString *value;
@property(nonatomic, readonly) NSString *title;

@end

