//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <Economy/UITableViewDataSource-Protocol.h>
#import <Economy/UITableViewDelegate-Protocol.h>

@class BaseTableView, CorrelationID, EconSpecialEvents, FeedSpinnerView, NSArray, NSLayoutConstraint, NSString, UIImageView, _TtC7Economy19EconProductsService;
@protocol GoldCoinMarketingListDelegate, _TtP7Economy15EconAppSettings_;

@interface GoldCoinMarketingList : UIView <UITableViewDataSource, UITableViewDelegate>
{
    _Bool _isPremiumSubscriber;
    _TtC7Economy19EconProductsService *_productsService;
    id <_TtP7Economy15EconAppSettings_> _settings;
    double _maxContentWidth;
    id <GoldCoinMarketingListDelegate> _delegate;
    UIImageView *_backgroundImageView;
    BaseTableView *_tableView;
    NSLayoutConstraint *_backgroundImageWidthConstraint;
    FeedSpinnerView *_loadingIndicatorView;
    NSArray *_products;
    EconSpecialEvents *_specialEvents;
    id _subscriptionToken;
    CorrelationID *_correlationID;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CorrelationID *correlationID; // @synthesize correlationID=_correlationID;
@property(retain, nonatomic) id subscriptionToken; // @synthesize subscriptionToken=_subscriptionToken;
@property(retain, nonatomic) EconSpecialEvents *specialEvents; // @synthesize specialEvents=_specialEvents;
@property(retain, nonatomic) NSArray *products; // @synthesize products=_products;
@property(nonatomic) _Bool isPremiumSubscriber; // @synthesize isPremiumSubscriber=_isPremiumSubscriber;
@property(retain, nonatomic) FeedSpinnerView *loadingIndicatorView; // @synthesize loadingIndicatorView=_loadingIndicatorView;
@property(retain, nonatomic) NSLayoutConstraint *backgroundImageWidthConstraint; // @synthesize backgroundImageWidthConstraint=_backgroundImageWidthConstraint;
@property(retain, nonatomic) BaseTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(readonly, nonatomic) __weak id <GoldCoinMarketingListDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) double maxContentWidth; // @synthesize maxContentWidth=_maxContentWidth;
@property(readonly, nonatomic) id <_TtP7Economy15EconAppSettings_> settings; // @synthesize settings=_settings;
@property(readonly, nonatomic) _TtC7Economy19EconProductsService *productsService; // @synthesize productsService=_productsService;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)hideLoadingIndicator;
- (void)showLoadingIndicator;
- (void)fetchGoldProductsIfNecessary;
- (struct UIEdgeInsets)contentInsetForRowAtIndexPath:(id)arg1 increaseTopPaddingForTheFirstCell:(_Bool)arg2;
- (void)layoutSubviews;
- (id)initWithEconomyContext:(id)arg1 maxContentWidth:(double)arg2 correlationID:(id)arg3 delegate:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

