//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GoldCoinMarketingList, GoldProduct, NSString;

@protocol GoldCoinMarketingListDelegate <NSObject>
- (void)goldCoinMarketingList:(GoldCoinMarketingList *)arg1 presentErrorMessage:(NSString *)arg2;
- (void)goldCoinMarketingList:(GoldCoinMarketingList *)arg1 purchaseProduct:(GoldProduct *)arg2;
- (void)presentFreeAwardFromGoldCoinMarketingList:(GoldCoinMarketingList *)arg1;
- (void)viewBalanceFromGoldCoinMarketingList:(GoldCoinMarketingList *)arg1;
- (void)learnAboutCoinsFromGoldCoinMarketingList:(GoldCoinMarketingList *)arg1;
@end

