//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter27FleetsDMReplyViewController : TFNViewController
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: composeViewController
    // Error parsing type: , name: account
    // Error parsing type: , name: users
    // Error parsing type: , name: recipientDisplayName
    // Error parsing type: , name: fleetID
    // Error parsing type: , name: onDismiss
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)keyboardStateDidChange;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

