//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter19FleetReplyReactView : UIView
{
    // Error parsing type: , name: _isShowingReactionMenu
    // Error parsing type: , name: selectionHandler
    // Error parsing type: , name: composeDMHandler
    // Error parsing type: , name: $__lazy_storage_$_emojiButton
    // Error parsing type: , name: $__lazy_storage_$_replyTextField
    // Error parsing type: , name: $__lazy_storage_$_emojiPicker
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)showEmojiPicker;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)handleReplyTextFieldTapped;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

