//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSDate, NSDictionary, NSString;

@protocol T1CrashReport <NSObject>
@property(readonly, nonatomic) _Bool isCrash;
@property(readonly, nonatomic) NSDate *dateCreated;
@property(readonly, copy, nonatomic) NSDictionary *customKeys;
@property(readonly, copy, nonatomic) NSString *userIdentifier;
@property(readonly, copy, nonatomic) NSString *identifier;
@end

