//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class T1PeopleDiscoveryScrollBumpCell, UICollectionViewCell;

@protocol T1PeopleDiscoveryScrollBumpCellDataSource <NSObject>
- (UICollectionViewCell *)scrollBumpCell:(T1PeopleDiscoveryScrollBumpCell *)arg1 viewForPageAtIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfPagesForScrollBumpCell:(T1PeopleDiscoveryScrollBumpCell *)arg1;
@end

