//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NFUIFamiliarityViewModel.h"

@class COEntity;

@interface _TtC4Argo30NFUIGenericComedyFeedViewModel : NFUIFamiliarityViewModel
{
    // Error parsing type: , name: sourceModel
    // Error parsing type: , name: myListStatus
    // Error parsing type: , name: similarsLoadedDelegate
    // Error parsing type: , name: trackId
    // Error parsing type: , name: requestId
    // Error parsing type: , name: listContext
    // Error parsing type: , name: simsTrackId
    // Error parsing type: , name: isHearted
    // Error parsing type: , name: similarsIds
    // Error parsing type: , name: similarsEntities
    // Error parsing type: , name: selectedEntity
    // Error parsing type: , name: internalEntityId
    // Error parsing type: , name: delegate
}

+ (id)newViewModelWithEntityId:(id)arg1;
- (void).cxx_destruct;
- (id)init;
- (id)trackingInfo;
- (id)initWithListModel:(id)arg1 withIndexPath:(id)arg2;
- (id)initWithEntityId:(id)arg1;
@property(nonatomic, retain) COEntity *entity;

@end

