//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC4Argo12SparseLolomo : NSObject
{
    // Error parsing type: , name: sparseRows
    // Error parsing type: , name: sparseRowCursor
    // Error parsing type: , name: sparseObservers
    // Error parsing type: , name: lastSummary
    // Error parsing type: , name: updating
}

+ (void)lolomoWithCompletion:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
- (id)init;

@end

