//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC4Argo16PerformanceTrace : NSObject
{
    // Error parsing type: , name: writeQueue
    // Error parsing type: , name: traceGroups
    // Error parsing type: , name: performanceTraceLog
    // Error parsing type: , name: previousSessionGroups
}

+ (void)clearPersistedCLTraceEvents;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)init;
- (void)persistCLWithTraceGroups:(id)arg1;
- (void)endPartialGroups;
- (void)endTraceGroupWithGroupName:(id)arg1;
- (void)endTraceWithGroup:(id)arg1 name:(id)arg2 data:(id)arg3;
- (void)endTraceWithGroup:(id)arg1 name:(id)arg2 status:(long long)arg3 statusMessage:(id)arg4 cached:(_Bool)arg5 queryName:(id)arg6 hasExpired:(_Bool)arg7;
- (void)endTraceWithGroup:(id)arg1 name:(id)arg2;
- (void)startBackdatedTraceWithGroup:(id)arg1 name:(id)arg2 startTime:(double)arg3;
- (void)startTraceWithGroup:(id)arg1 name:(id)arg2;

@end

