//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "NetflixNavigationBarSubHeaderNavigationProtocol-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class NSIndexPath, UIButton, UICollectionView;
@protocol _TtP4Argo24NFUIAROFilterBarDelegate_;

@interface _TtC4Argo16NFUIAROFilterBar : UIView <UICollectionViewDelegateFlowLayout, NetflixNavigationBarSubHeaderNavigationProtocol>
{
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: collectionViewLayout
    // Error parsing type: , name: items
    // Error parsing type: , name: selectedIndexPath
    // Error parsing type: , name: delegate
    // Error parsing type: , name: backButton
    // Error parsing type: , name: accessibilityElement
}

+ (void)animateWithNetflixEasingCurve:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
- (void)a11yAnnounceCurrentStatus;
- (id)a11yDescription;
- (void)handleLolomoResultsNotification:(id)arg1;
- (void)configureBackButton:(id)arg1;
- (_Bool)wantsBackButton;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)reload;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)clearSelection;
- (void)replaceWithItems:(id)arg1 animated:(_Bool)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) __weak UIButton *backButton; // @synthesize backButton;
@property(nonatomic) __weak id <_TtP4Argo24NFUIAROFilterBarDelegate_> delegate; // @synthesize delegate;
@property(nonatomic, copy) NSIndexPath *selectedIndexPath;
@property(nonatomic, retain) UICollectionView *collectionView; // @synthesize collectionView;

@end

