//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFManifestCommon/_TtC16NFManifestCommon5Track.h>

#import <NFManifestCommon/_TtP16NFManifestCommon12NFVideoTrack_-Protocol.h>

@class NSString;

@interface _TtC16NFManifestCommon10VideoTrack : _TtC16NFManifestCommon5Track <_TtP16NFManifestCommon12NFVideoTrack_>
{
}

- (id)initWithDictionary:(id)arg1 manifest:(id)arg2;
@property(nonatomic, readonly) _Bool isEncrypted;
- (id)getPsshStringForStream:(id)arg1;
- (id)drmHeaders;
- (void)enumerateStreams:(CDUnknownBlockType)arg1;
- (void)enumerateVideoStreams:(CDUnknownBlockType)arg1;
@property(nonatomic, readonly) NSString *keyId;

@end

