//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface _TtC4Argo13ConfigService : NSObject
{
    // Error parsing type: , name: config
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)init;
- (void)updateConfigWith:(id)arg1;
- (id)activeTests;
@property(nonatomic, copy) NSDictionary *config;

@end

