//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC4Argo20SearchViewController.h"

#import "DZNEmptyDataSetDelegate-Protocol.h"
#import "DZNEmptyDataSetSource-Protocol.h"
#import "NFUISearchBarDelegateProtocol-Protocol.h"
#import "NFUISearchResultsListViewModelDelegateProtocol-Protocol.h"
#import "NFUITouchGestureDelegate-Protocol.h"

@interface _TtC4Argo20SearchViewController (Argo) <NFUITouchGestureDelegate, NFUISearchBarDelegateProtocol, NFUISearchResultsListViewModelDelegateProtocol, DZNEmptyDataSetDelegate, DZNEmptyDataSetSource>
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)handleTouchesBegan:(id)arg1 with:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 fromGestureRecognizer:(id)arg2;
- (void)searchFieldEditingChanged:(id)arg1;
- (void)cancelButtonTapped;
- (void)closeSearchTapped;
- (void)searchTextCleared;
- (void)didSelectSearchResult:(id)arg1;
- (void)viewControllerOverContextDidDisappear:(id)arg1;
- (void)viewControllerOverContextWillDisappear:(id)arg1;
- (void)viewControllerOverContextWillAppear:(id)arg1;
- (id)activeScrollView;
- (void)selectedTab_DEPRECATED;
- (void)selectedTab:(id)arg1 comingFromTab:(id)arg2;
- (void)setDeeplinkPayload:(id)arg1;
- (void)setNFUITabBarItem:(id)arg1;
- (void)fetchPrequeryListWithShouldUserRetryReachability:(_Bool)arg1;
- (void)playTitleWithPlaybackRequest:(id)arg1;
- (void)showDisplayPageWithDisplayPageRequest:(id)arg1;
- (void)emptyDataSetDidTapButton:(id)arg1;
- (_Bool)emptyDataSetShouldDisplay:(id)arg1;
- (id)buttonTitleForEmptyDataSet:(id)arg1 forState:(unsigned long long)arg2;
- (id)titleForEmptyDataSet:(id)arg1;
- (void)handlePendingSuggestionIdWithAppFlowController:(id)arg1;
- (void)handlePendingSearchTerm;
- (void)handleDeepLinkActions;
@end

