//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC4Argo26MDXActionSheetCellProvider : NSObject
{
    // Error parsing type: , name: shouldSuppressHeader
    // Error parsing type: , name: shouldShowServiceInfo
    // Error parsing type: , name: delegate
    // Error parsing type: , name: displayConfiguration
    // Error parsing type: , name: displayContent
    // Error parsing type: , name: disconnectAction
    // Error parsing type: , name: tableView
}

- (void).cxx_destruct;
- (id)init;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)handleButtonAction;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)disconnect;

@end

