//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class _TtC4Argo19TitleDownloadButton;
@protocol _TtP4Argo49NFUIDisplayPageDownloadButtonViewDelegateProtocol_;

@interface _TtC4Argo29DisplayPageDownloadButtonView : UIView
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: downloadButton
    // Error parsing type: , name: edgeSpacing
}

- (void).cxx_destruct;
- (void)didTapDownload;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) _TtC4Argo19TitleDownloadButton *downloadButton; // @synthesize downloadButton;
@property(nonatomic) __weak id <_TtP4Argo49NFUIDisplayPageDownloadButtonViewDelegateProtocol_> delegate; // @synthesize delegate;

@end

