//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LolomoViewModel.h"

@class LolomoViewConfig, NSString;

@interface _TtC4Argo21SparseLolomoViewModel : LolomoViewModel
{
    // Error parsing type: , name: sparseLolomo
    // Error parsing type: , name: legacyConfig
}

- (void).cxx_destruct;
- (id)initWithContext:(id)arg1 request:(id)arg2;
- (_Bool)shouldAnimateBillboard;
- (_Bool)configureList:(id)arg1;
- (void)paginate:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)configureWithSparseLolomo:(id)arg1;
- (void)configure:(_Bool)arg1;
- (id)refreshOperation:(_Bool)arg1;
- (id)fetchOperation:(_Bool)arg1;
@property(nonatomic, readonly) NSString *lolomoId;
@property(nonatomic, readonly) _Bool isPageTypeGallery;
@property(nonatomic, readonly) _Bool isFallback;
@property(nonatomic, readonly) NSString *hydrationLevel;
@property(nonatomic, readonly) LolomoViewConfig *config;

@end

