//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC4Argo29NFUIGenericComedyFeedViewCell.h"

#import "NFUIPlayerDelegate-Protocol.h"
#import "NFUISegmentedControllerViewDelegate-Protocol.h"
#import "ShareSheetControllerDelegate-Protocol.h"

@interface _TtC4Argo29NFUIGenericComedyFeedViewCell (Argo) <NFUIPlayerDelegate, ShareSheetControllerDelegate, NFUISegmentedControllerViewDelegate>
+ (_Bool)shouldReturnClassForType:(id)arg1 withModel:(id)arg2;
+ (void)registerSelf;
+ (id)reuseIdentifier;
- (void)player:(id)arg1 error:(id)arg2;
- (void)player:(id)arg1 timeUpdate:(double)arg2;
- (void)player:(id)arg1 stateChange:(unsigned long long)arg2 previous:(unsigned long long)arg3;
- (void)playWithForce:(_Bool)arg1;
- (struct CGSize)staticCalculatedSizeForModel:(id)arg1 withCollectionView:(id)arg2;
- (void)detailsTapped;
- (void)shareSheetDidDismiss;
- (void)beginPresentationSessionForPath:(id)arg1;
- (void)visibleInfoForViewInScrollView:(id)arg1;
- (void)prepareForReuse;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)segmentedSelectedViewDidChange:(id)arg1 withDeselectedView:(id)arg2;
@end

