//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UIInteraction-Protocol.h"

@class UIView;

@interface _TtC4Argo16SheetInteraction : NSObject <UIInteraction>
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: view
    // Error parsing type: , name: topY
    // Error parsing type: , name: bottomY
    // Error parsing type: , name: detents
    // Error parsing type: , name: interactionStarted
    // Error parsing type: , name: propertyAnimator
    // Error parsing type: , name: startY
    // Error parsing type: , name: currentY
    // Error parsing type: , name: $__lazy_storage_$_panGesture
    // Error parsing type: , name: scrollPanGesture
}

- (void).cxx_destruct;
- (id)init;
- (void)pan:(id)arg1;
- (void)didMoveToView:(id)arg1;
- (void)willMoveToView:(id)arg1;
@property(nonatomic) __weak UIView *view; // @synthesize view;

@end

