//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFManifestCommon/_TtC16NFManifestCommon9TextTrack.h>

@interface _TtC16NFManifestCommon17FilteredTextTrack : _TtC16NFManifestCommon9TextTrack
{
    // Error parsing type: , name: filteredStreamDownloadableIds
}

- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1 manifest:(id)arg2;
@property(nonatomic, readonly) _Bool hasRichWebVTT;
@property(nonatomic, readonly) _Bool hasWebVTT;
@property(nonatomic, readonly) _Bool hasImageBased;
@property(nonatomic, readonly) unsigned long long streamCount;
- (void)enumerateTextStreams:(CDUnknownBlockType)arg1;

@end

