//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFManifestCommon/_TtC16NFManifestCommon10VideoTrack.h>

@interface _TtC16NFManifestCommon18FilteredVideoTrack : _TtC16NFManifestCommon10VideoTrack
{
    // Error parsing type: , name: filteredStreamDownloadableIds
    // Error parsing type: , name: dupeDlidToResolutions
}

- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1 manifest:(id)arg2;
@property(nonatomic, readonly) unsigned long long streamCount;
- (void)enumerateVideoStreams:(CDUnknownBlockType)arg1;
- (id)initWithDictionary:(id)arg1 filteredDownloadableIds:(id)arg2 dupeDownloadableIdsToResolutions:(id)arg3 manifest:(id)arg4;

@end

