//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NFUIButton, NFUILabel;

@interface _TtC4Argo31MDXStopConnectingViewController : UIViewController
{
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: subtitleLabel
    // Error parsing type: , name: stopConnectingButton
    // Error parsing type: , name: keepTryingButton
    // Error parsing type: , name: mdxConnectStop
    // Error parsing type: , name: cancelCommandID
    // Error parsing type: , name: $__lazy_storage_$_clLogger
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)keepTryingButtonDidTap:(id)arg1;
- (void)stopConnectingButtonDidTap:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak NFUIButton *keepTryingButton; // @synthesize keepTryingButton;
@property(nonatomic) __weak NFUIButton *stopConnectingButton; // @synthesize stopConnectingButton;
@property(nonatomic) __weak NFUILabel *subtitleLabel; // @synthesize subtitleLabel;
@property(nonatomic) __weak NFUILabel *titleLabel; // @synthesize titleLabel;

@end

