//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NFNetworkState/_TtP14NFNetworkState29NFReachabilityObservationDeck_-Protocol.h>

@protocol _TtP14NFNetworkState20NFReachabilityStatus_, _TtP14NFNetworkState29NFReachabilityObservationDeck_;

@interface _TtC14NFNetworkState20ReachabilityProvider : NSObject <_TtP14NFNetworkState29NFReachabilityObservationDeck_>
{
    // Error parsing type: , name: serialQueue
    // Error parsing type: , name: monitor
    // Error parsing type: , name: observations
    // Error parsing type: , name: _reachabilityStatus
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)removeReachabilityObserver:(id)arg1;
- (void)addReachabilityObserver:(id)arg1 initialState:(_Bool)arg2;
@property(nonatomic, readonly) id <_TtP14NFNetworkState29NFReachabilityObservationDeck_> reachabilityObservationDeck;
@property(nonatomic, readonly) id <_TtP14NFNetworkState20NFReachabilityStatus_> reachabilityStatus;
- (id)init;

@end

