//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NFUIButton, NFUICloseButton, NFUILabel, NSLayoutConstraint, NSString, UIImageView, _TtC4Argo12NFUIPinsView;

@interface _TtC4Argo21MDXCardViewController : UIViewController
{
    // Error parsing type: , name: netflixTVImageView
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: availableTVLabel
    // Error parsing type: , name: readyToSignInLabel
    // Error parsing type: , name: signInOnTVButton
    // Error parsing type: , name: closeButton
    // Error parsing type: , name: pinsView
    // Error parsing type: , name: netflixTVToTopConstraint
    // Error parsing type: , name: $__lazy_storage_$_clLogger
    // Error parsing type: , name: mdxConnect
    // Error parsing type: , name: mdxConnectStop
    // Error parsing type: , name: targetFriendlyName
    // Error parsing type: , name: targetMDXUUID
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (_Bool)accessibilityPerformEscape;
@property(nonatomic) _Bool accessibilityViewIsModal;
- (void)closeButtonDidTap:(id)arg1;
- (void)signInOnTVDidTap:(id)arg1;
- (void)viewDidTap:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic, copy) NSString *targetMDXUUID;
@property(nonatomic, copy) NSString *targetFriendlyName;
@property(nonatomic, copy) CDUnknownBlockType mdxConnectStop;
@property(nonatomic, copy) CDUnknownBlockType mdxConnect;
@property(nonatomic) __weak NSLayoutConstraint *netflixTVToTopConstraint; // @synthesize netflixTVToTopConstraint;
@property(nonatomic) __weak _TtC4Argo12NFUIPinsView *pinsView; // @synthesize pinsView;
@property(nonatomic) __weak NFUICloseButton *closeButton; // @synthesize closeButton;
@property(nonatomic) __weak NFUIButton *signInOnTVButton; // @synthesize signInOnTVButton;
@property(nonatomic) __weak NFUILabel *readyToSignInLabel; // @synthesize readyToSignInLabel;
@property(nonatomic) __weak NFUILabel *availableTVLabel; // @synthesize availableTVLabel;
@property(nonatomic) __weak NFUILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic) __weak UIImageView *netflixTVImageView; // @synthesize netflixTVImageView;

@end

