//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC4Argo29NFUIComedyFeedMyListToastView : UIView
{
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: descriptionLabel
    // Error parsing type: , name: internalTitle
    // Error parsing type: , name: timeoutAmount
    // Error parsing type: , name: hasShownOnce
    // Error parsing type: , name: isShowing
    // Error parsing type: , name: isContentWarningInternal
    // Error parsing type: , name: internalState
    // Error parsing type: , name: timer
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

