//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSDate, NSString;

@interface _TtC4Argo15NFUILiveLogItem : NSObject
{
    // Error parsing type: , name: index
    // Error parsing type: , name: profileGuid
    // Error parsing type: , name: logGroup
    // Error parsing type: , name: logEntry
    // Error parsing type: , name: logDate
    // Error parsing type: , name: logData
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, copy) NSData *logData;
@property(nonatomic, copy) NSDate *logDate;
@property(nonatomic, copy) NSString *logEntry;
@property(nonatomic, copy) NSString *logGroup;
@property(nonatomic, copy) NSString *profileGuid;

@end

