//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC4Argo16TabBarFacadeView : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_bgRect
    // Error parsing type: , name: $__lazy_storage_$_bgCircle
    // Error parsing type: , name: tabTypes
    // Error parsing type: , name: $__lazy_storage_$_stackView
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

