//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NFUIFamiliarityViewCell.h"

@class NSArray;
@protocol NFUIReusableViewModelProtocol;

@interface _TtC4Argo29NFUIGenericComedyFeedViewCell : NFUIFamiliarityViewCell
{
    // Error parsing type: , name: RATIO_VERTICAL
    // Error parsing type: , name: RATIO_HORIZONTAL
    // Error parsing type: , name: MARGIN
    // Error parsing type: , name: SimsMargin
    // Error parsing type: , name: NumSims
    // Error parsing type: , name: shouldPlay
    // Error parsing type: , name: isVisible
    // Error parsing type: , name: internalViewModel
    // Error parsing type: , name: elementContainer
    // Error parsing type: , name: titleTreatment
    // Error parsing type: , name: buttons
    // Error parsing type: , name: maturityContainer
    // Error parsing type: , name: maturityLabel
    // Error parsing type: , name: progressBar
    // Error parsing type: , name: similars
    // Error parsing type: , name: volumeButton
    // Error parsing type: , name: disabledAutoPlayButton
    // Error parsing type: , name: placeHolderImage
    // Error parsing type: , name: topGradient
    // Error parsing type: , name: player
    // Error parsing type: , name: playbackDelegate
    // Error parsing type: , name: buttonDelegate
    // Error parsing type: , name: myListDelegate
    // Error parsing type: , name: heartDelegate
    // Error parsing type: , name: shareDelegate
    // Error parsing type: , name: disabledAutoPlayTapDelegate
    // Error parsing type: , name: similarsDelegate
    // Error parsing type: , name: volumeChangeDelegate
    // Error parsing type: , name: detailsTappedDelegate
    // Error parsing type: , name: visibility
    // Error parsing type: , name: isPressed
    // Error parsing type: , name: isBouncing
    // Error parsing type: , name: isDeeplinking
    // Error parsing type: , name: isProgressing
    // Error parsing type: , name: isDragging
    // Error parsing type: , name: isActivelyScrolling
    // Error parsing type: , name: isSharing
    // Error parsing type: , name: isPulsing
    // Error parsing type: , name: internalViewModelSet
    // Error parsing type: , name: error
    // Error parsing type: , name: hasSetupSimilars
    // Error parsing type: , name: buttonsBottomConstraint
    // Error parsing type: , name: retryContainer
}

+ (id)viewModelForListModel:(id)arg1 withIndexPath:(id)arg2;
+ (void)setAllowsVolume:(_Bool)arg1;
+ (_Bool)allowsVolume;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)cellDidBecomeInactive:(id)arg1;
- (void)cellDidEndDisplaying:(id)arg1;
- (void)cellWillDisappearFromContext:(unsigned long long)arg1;
- (void)cellWillEnterForeground:(id)arg1;
- (void)cellDidBecomeActive:(id)arg1;
- (void)cellWillDisplay:(id)arg1;
- (void)cellDidAppearFromContext:(unsigned long long)arg1;
- (void)pressedWithGesture:(id)arg1;
@property(nonatomic, retain) id <NFUIReusableViewModelProtocol> viewModel;
@property(nonatomic, copy) NSArray *accessibilityElements;
- (void)hiddenPlayTapped:(id)arg1;
- (void)commonInit;

@end

