//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC4Argo13PerfScaleView : UIView
{
    // Error parsing type: , name: perfScale
    // Error parsing type: , name: timeStart
    // Error parsing type: , name: scaleLayer
    // Error parsing type: , name: leadingLabel
    // Error parsing type: , name: trailingLabel
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;

@end

