//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UIViewControllerAnimatedTransitioning-Protocol.h"

@interface _TtC4Argo18ModalSheetAnimator : NSObject <UIViewControllerAnimatedTransitioning>
{
    // Error parsing type: , name: isDismissing
    // Error parsing type: , name: oldContainerView
    // Error parsing type: , name: presentedController
}

- (void).cxx_destruct;
- (id)init;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;

@end

