//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "COEntity.h"

@interface _TtCC4Argo32NFUIComedyFeedHeaderReusableView26NFUIComedyFeedHeaderEntity : COEntity
{
    // Error parsing type: , name: synopsis
}

+ (id)falcorKeyPathsForUpdateMap;
+ (id)falcorKeyPathMap;
- (void).cxx_destruct;
- (id)initWithObjectContext:(id)arg1 baseFalcorKeyPath:(id)arg2;

@end

