//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NFUICloseButton, NSLayoutConstraint, UIImageView, UILabel, UIStackView;

@interface _TtC4Argo36CollectingPhoneNumbersViewController : UIViewController
{
    // Error parsing type: , name: sheildImageView
    // Error parsing type: , name: closeButton
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: subtitleLabel
    // Error parsing type: , name: ctaStackView
    // Error parsing type: , name: sheildImageViewTopContraint
    // Error parsing type: , name: viewModel
    // Error parsing type: , name: $__lazy_storage_$_phoneInputField
    // Error parsing type: , name: $__lazy_storage_$_networkManager
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)addPhoneNumberDidTap:(id)arg1;
- (void)remindMeLaterDidTap:(id)arg1;
- (void)closeButtonDidTap:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak NSLayoutConstraint *sheildImageViewTopContraint; // @synthesize sheildImageViewTopContraint;
@property(nonatomic) __weak UIStackView *ctaStackView; // @synthesize ctaStackView;
@property(nonatomic) __weak UILabel *subtitleLabel; // @synthesize subtitleLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic) __weak NFUICloseButton *closeButton; // @synthesize closeButton;
@property(nonatomic) __weak UIImageView *sheildImageView; // @synthesize sheildImageView;

@end

