//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSUserDefaults;

@interface _TtC4Argo14NFUILiveLogger : NSObject
{
    // Error parsing type: , name: logStore
    // Error parsing type: , name: enabled
    // Error parsing type: , name: groupUserDefaults
    // Error parsing type: , name: sortDescending
}

+ (void)logSanitizedString:(id)arg1 data:(id)arg2 group:(id)arg3;
+ (void)logSanitizedString:(id)arg1 dictionary:(id)arg2 group:(id)arg3;
+ (void)logSanitizedString:(id)arg1 group:(id)arg2;
+ (void)configureWithValue:(_Bool)arg1 profileGuid:(id)arg2;
+ (id)log;
- (void).cxx_destruct;
- (void)toggleSort;
- (void)removeAllLogs;
- (void)removeLogGroup:(id)arg1;
- (void)removeLogItem:(id)arg1;
- (id)logItemsForGroup:(id)arg1;
- (id)distinctGroups;
- (id)init;
@property(nonatomic, retain) NSUserDefaults *groupUserDefaults; // @synthesize groupUserDefaults;
@property(nonatomic) _Bool enabled; // @synthesize enabled;

@end

