//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC4Argo27NFUIComedyFeedOutroCardView.h"

@interface _TtC4Argo27NFUIComedyFeedOutroCardView (Argo)
+ (_Bool)shouldReturnClassForType:(id)arg1 withModel:(id)arg2;
+ (void)registerSelf;
+ (id)reuseIdentifier;
- (struct CGSize)staticCalculatedSizeForModel:(id)arg1 withCollectionView:(id)arg2;
- (void)visibleInfoForViewInScrollView:(id)arg1;
@end

