//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol _TtP16NFManifestCommon12NFAudioTrack_;

@interface _TtC16NFManifestCommon15TrackPreference : NSObject
{
    // Error parsing type: , name: data
    // Error parsing type: , name: audioTrack
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *audioMediaId;
@property(nonatomic, readonly) NSString *videoMediaId;
@property(nonatomic, readonly) NSString *subtitleMediaId;
@property(nonatomic, readonly) NSString *mediaId;
@property(nonatomic, readonly) unsigned long long preferenceOrder;
@property(nonatomic, retain) id <_TtP16NFManifestCommon12NFAudioTrack_> audioTrack; // @synthesize audioTrack;
- (id)initWithDictionary:(id)arg1;

@end

