//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

#import "UIKeyInput-Protocol.h"
#import "UITextInputTraits-Protocol.h"

@class UIColor;

@interface _TtC4Argo12NFUIPinsView : UIControl <UIKeyInput, UITextInputTraits>
{
    // Error parsing type: , name: pinLength
    // Error parsing type: , name: pinWidth
    // Error parsing type: , name: spacing
    // Error parsing type: , name: textColor
    // Error parsing type: , name: fontSize
    // Error parsing type: , name: borderLineColor
    // Error parsing type: , name: borderLineThickness
    // Error parsing type: , name: pinsText
    // Error parsing type: , name: delegate
    // Error parsing type: , name: nextTag
    // Error parsing type: , name: $__lazy_storage_$_pinsStack
}

- (void).cxx_destruct;
- (void)deleteBackward;
- (void)insertText:(id)arg1;
- (void)prepareForInterfaceBuilder;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) long long keyboardType;
@property(nonatomic, readonly) _Bool hasText;
@property(nonatomic, readonly) _Bool canBecomeFirstResponder;
@property(nonatomic) double borderLineThickness; // @synthesize borderLineThickness;
@property(nonatomic, retain) UIColor *borderLineColor; // @synthesize borderLineColor;
@property(nonatomic) double fontSize; // @synthesize fontSize;
@property(nonatomic, retain) UIColor *textColor; // @synthesize textColor;
@property(nonatomic) double spacing; // @synthesize spacing;
@property(nonatomic) double pinWidth; // @synthesize pinWidth;
@property(nonatomic) long long pinLength; // @synthesize pinLength;

@end

