//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC4Argo13PerfEventView : UIView
{
    // Error parsing type: , name: sourceEvent
    // Error parsing type: , name: color
    // Error parsing type: , name: hasTimeGap
    // Error parsing type: , name: offsetLabelInset
    // Error parsing type: , name: startMarker
    // Error parsing type: , name: endMarker
    // Error parsing type: , name: crossMarker
    // Error parsing type: , name: strokeWidth
    // Error parsing type: , name: offsetLabel
    // Error parsing type: , name: timeGapView
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

