//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC4Argo15SparseLolomoRow : NSObject
{
    // Error parsing type: , name: sparseItems
    // Error parsing type: , name: index
    // Error parsing type: , name: lolomoRowEdge
    // Error parsing type: , name: lolomoRow
    // Error parsing type: , name: priorRow
    // Error parsing type: , name: rowCursor
    // Error parsing type: , name: sparseObservers
    // Error parsing type: , name: sparseItemCursor
    // Error parsing type: , name: sparseItemCursorIndex
    // Error parsing type: , name: updating
}

- (void).cxx_destruct;
- (id)init;

@end

