//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextField.h>

@interface _TtC4Argo20PhoneNumberTextField : UITextField
{
    // Error parsing type: , name: $__lazy_storage_$_flagButton
    // Error parsing type: , name: $__lazy_storage_$_phoneNumberUtility
    // Error parsing type: , name: currentRegion
    // Error parsing type: , name: prefix
    // Error parsing type: , name: $__lazy_storage_$_errorMessageLabel
    // Error parsing type: , name: withPrefix
    // Error parsing type: , name: withFlag
}

- (void).cxx_destruct;
- (void)flagButtonDidTap:(id)arg1;
- (void)deleteBackward;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

