//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIPresentationController.h>

@interface _TtC4Argo32ModalSheetPresentationController : UIPresentationController
{
    // Error parsing type: , name: dimmedView
    // Error parsing type: , name: dismissAnimator
    // Error parsing type: , name: sheetView
    // Error parsing type: , name: closeButton
    // Error parsing type: , name: sheetCornerRadius
    // Error parsing type: , name: propertyAnimator
    // Error parsing type: , name: dismissing
    // Error parsing type: , name: sheetInteraction
    // Error parsing type: , name: percentInteractor
}

- (void).cxx_destruct;
- (id)initWithPresentedViewController:(id)arg1 presentingViewController:(id)arg2;
- (void)preferredContentSizeDidChangeForChildContentContainer:(id)arg1;
- (void)containerViewDidLayoutSubviews;
- (void)containerViewWillLayoutSubviews;
- (void)presentationTransitionDidEnd:(_Bool)arg1;
- (void)dismissalTransitionDidEnd:(_Bool)arg1;
- (void)dismissalTransitionWillBegin;
- (void)presentationTransitionWillBegin;
@property(nonatomic, readonly) struct CGRect frameOfPresentedViewInContainerView;
@property(nonatomic, readonly) _Bool shouldPresentInFullscreen;
- (void)dismiss;

@end

