//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC4Argo26ComedyFeedPreviewsRenderer.h"

@interface _TtC4Argo26ComedyFeedPreviewsRenderer (Argo)
- (id)gradientColorsForDate;
- (id)gradientLayerWithBounds:(struct CGRect)arg1 isSpecialPromo:(_Bool)arg2 isWatched:(_Bool)arg3;
- (id)gradientImageWithBounds:(struct CGRect)arg1 isSpecialPromo:(_Bool)arg2 isWatched:(_Bool)arg3;
- (void)setHasSeenSpecialPromoWithHasSeen:(_Bool)arg1;
- (_Bool)shouldShowSpecialPreviewOverride;
@end

