//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NavigationBarAppearanceManager;

@interface _TtC4Argo28NFUILolomoFeedViewController : UIViewController
{
    // Error parsing type: , name: feedViewController
    // Error parsing type: , name: model
    // Error parsing type: , name: listRefreshBinding
    // Error parsing type: , name: _navBarManager
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)paginateForAmount:(unsigned long long)arg1;
- (void)cellDidSetViewModel:(id)arg1 forIndexPath:(id)arg2 withViewModel:(id)arg3;
- (void)configureWithViewModel:(id)arg1;
- (id)createNewViewModel:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)willMoveToParentViewController:(id)arg1;
@property(nonatomic, retain) NavigationBarAppearanceManager *navBarManager;

@end

