//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewHeaderFooterView.h>

@class UIImageView, UILabel;

@interface _TtC4Argo17ActionSheetHeader : UITableViewHeaderFooterView
{
    // Error parsing type: , name: _textLabel
    // Error parsing type: , name: isDynamicTypeEnabled
    // Error parsing type: , name: iconImageView
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithReuseIdentifier:(id)arg1;
- (void)prepareForReuse;
- (void)traitCollectionDidChange:(id)arg1;
- (void)layoutSubviews;
- (void)awakeFromNib;
@property(nonatomic, retain) UILabel *textLabel;
@property(nonatomic, retain) UIImageView *iconImageView; // @synthesize iconImageView;

@end

