//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC4Argo24PreviewsPromoOverlayView : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_lottieAnimationView
    // Error parsing type: , name: beginAnimationStarted
    // Error parsing type: , name: endAnimationStarted
}

- (void).cxx_destruct;
- (void)resetAnimation;
- (void)animateOutWithDuration:(double)arg1;
- (void)animateInWithDuration:(double)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

