//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC4Argo21NFUIEmojiReactionsBar : UIView
{
    // Error parsing type: , name: emojisStackView
    // Error parsing type: , name: container
    // Error parsing type: , name: countLabel
    // Error parsing type: , name: widthOverride
    // Error parsing type: , name: hasMoved
    // Error parsing type: , name: defaultWidthAnchor
    // Error parsing type: , name: hoveredItem
    // Error parsing type: , name: selectedEmoji
    // Error parsing type: , name: tapDelegate
    // Error parsing type: , name: emojiTypes
}

- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)tapped:(id)arg1;
- (void)didMoveToSuperview;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

