//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFManifestCommon/_TtC16NFManifestCommon6Stream.h>

@class NSArray, NSSet, NSString;

@interface _TtC16NFManifestCommon10TextStream : _TtC16NFManifestCommon6Stream
{
    // Error parsing type: , name: streamTypeIdentifier
}

- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1 track:(id)arg2;
@property(nonatomic, readonly) NSSet *allStreamCdnIdSet;
@property(nonatomic, readonly) NSArray *allStreamUrls;
@property(nonatomic, readonly) NSArray *rankSortedTextCdnInfoArray;
@property(nonatomic, readonly) _Bool isImageBased;
@property(nonatomic, readonly) NSString *streamProfileName;
@property(nonatomic, readonly) unsigned long long nominalBitrate;
- (id)urlStringForCdnId:(long long)arg1;
@property(nonatomic, readonly) NSString *downloadableId;
@property(nonatomic, readonly) long long streamMediaType;
- (id)initWithDictionary:(id)arg1 track:(id)arg2 streamTypeIdentifier:(id)arg3;
@property(nonatomic, copy) NSString *streamTypeIdentifier;

@end

