//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NFUIButton, UILabel, _TtC4Argo12NFUIPinsView;

@interface _TtC4Argo42CollectingPhoneNumbersVerifyViewController : UIViewController
{
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: pinsView
    // Error parsing type: , name: verifyButton
    // Error parsing type: , name: resendCodeButton
    // Error parsing type: , name: doItLaterButton
    // Error parsing type: , name: phoneNumber
    // Error parsing type: , name: countryCode
    // Error parsing type: , name: $__lazy_storage_$_networkManager
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)backButtonDidTap:(id)arg1;
- (void)DoItLaterButtonDidTap:(id)arg1;
- (void)resendCodeButtonDidTap:(id)arg1;
- (void)verifyButtonDidTap:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak NFUIButton *doItLaterButton; // @synthesize doItLaterButton;
@property(nonatomic) __weak NFUIButton *resendCodeButton; // @synthesize resendCodeButton;
@property(nonatomic) __weak NFUIButton *verifyButton; // @synthesize verifyButton;
@property(nonatomic) __weak _TtC4Argo12NFUIPinsView *pinsView; // @synthesize pinsView;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel;

@end

