//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC4Argo17VanityURLResolver : NSObject
{
    // Error parsing type: , name: landingPageURL
    // Error parsing type: , name: currentSession
    // Error parsing type: , name: cancellable
}

- (void).cxx_destruct;
- (id)init;
- (void)resolveURL:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

