//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@interface _TtC4Argo23PerfTraceViewController : UIViewController <UIGestureRecognizerDelegate>
{
    // Error parsing type: , name: streamViews
    // Error parsing type: , name: scrollView
    // Error parsing type: , name: compareView
    // Error parsing type: , name: debugCounter
    // Error parsing type: , name: firstLoad
    // Error parsing type: , name: skipTimegaps
    // Error parsing type: , name: skipZeros
    // Error parsing type: , name: editMode
    // Error parsing type: , name: editInitialOffset
    // Error parsing type: , name: editInitialTransform
    // Error parsing type: , name: pinchRecognizer
    // Error parsing type: , name: hideCompareRecnognizer
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)pannedWithRecognizer:(id)arg1;
- (void)doubleTappedWithRecognizer:(id)arg1;
- (void)pinchedWithRecognizer:(id)arg1;
- (void)saveStackTapped;
- (void)toggleZeroLength;
- (void)toggleSkip;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)hideCompareViewWithRecognizer:(id)arg1;
- (void)viewDidLoad;

@end

