//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NCLDataDelegate-Protocol.h"

@class NSString;
@protocol NCLUploadDelegate;

@interface _TtC4Argo11CSDataStore : NSObject <NCLDataDelegate>
{
    // Error parsing type: , name: uploadDelegate
    // Error parsing type: , name: storePath
    // Error parsing type: , name: dbPointer
    // Error parsing type: , name: currentDelta
    // Error parsing type: , name: firstSnapshot
    // Error parsing type: , name: batchInterval
    // Error parsing type: , name: batchSize
    // Error parsing type: , name: lastFlush
}

- (void).cxx_destruct;
- (id)init;
- (void)configureWithState:(id)arg1;
- (id)currentState;
- (id)getOpenSessionIds;
- (void)flushWithCompletion:(CDUnknownBlockType)arg1;
- (void)snapshot:(id)arg1;
- (void)addEventWithId:(id)arg1 andContext:(id)arg2;
- (id)endSession:(id)arg1 endContext:(id)arg2;
- (id)getSession:(id)arg1;
- (void)startSession:(id)arg1 andContext:(id)arg2;
- (id)removeContext:(id)arg1;
- (void)addContextWithId:(id)arg1 andContext:(id)arg2;
- (void)removeObject:(id)arg1;
- (void)closeDB;
- (_Bool)didOpen;
- (void)dealloc;
- (id)initWithStore:(id)arg1;
@property(nonatomic, copy) NSString *storePath;
@property(nonatomic) __weak id <NCLUploadDelegate> uploadDelegate; // @synthesize uploadDelegate;

@end

