//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC8ArgoCore8ACFalcor : NSObject
{
}

+ (_Bool)conformsToSubscription:(id)arg1;
+ (id)createModel:(id)arg1 optimizedPaths:(id)arg2;
+ (id)errorDomain;
- (id)init;

@end

