//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC4Argo18RecaptchaUtilities : NSObject
{
}

+ (id)initDisclosureTextViewWithContent:(id)arg1 strLinkDict:(id)arg2;
+ (id)initDisclaimerLabelWithDisclaimer:(id)arg1 learnMore:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)performRecaptchaWith:(id)arg1 client:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (id)initClientWith:(id)arg1;
+ (id)fetchSiteKeyFrom:(id)arg1;
+ (double)RecaptchaDisclosureHeight;
+ (double)RecaptchaDisclosureDistance;
+ (double)RecaptchaDisclaimerDistance;
+ (double)RecaptchaDisclaimerWidth;
- (void).cxx_destruct;
- (id)init;

@end

