//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@interface _TtC4Argo24NFUIAROFilterBarItemView : UICollectionViewCell
{
    // Error parsing type: , name: name
    // Error parsing type: , name: nameLabel
    // Error parsing type: , name: edgePadding
    // Error parsing type: , name: selectionBackgroundView
    // Error parsing type: , name: isProminent
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool selected;
- (_Bool)isSelected;

@end

