//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC4Argo17VanityURLResolver.h"

@class NSURL;

@interface _TtC4Argo21VanityURLResolverMock : _TtC4Argo17VanityURLResolver
{
    // Error parsing type: , name: callCount
    // Error parsing type: , name: url
    // Error parsing type: , name: landingUrl
}

- (void).cxx_destruct;
- (id)init;
- (void)resolveURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(nonatomic, copy) NSURL *landingUrl;
@property(nonatomic, copy) NSURL *url;
@property(nonatomic) long long callCount; // @synthesize callCount;

@end

