//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NFUILabel, NSString, UIButton, UIImageView;

@interface _TtC4Argo31NetflixNavigationBarTitleButton : UIView
{
    // Error parsing type: , name: NetflixLogoSize
    // Error parsing type: , name: netflixLogo
    // Error parsing type: , name: netflixLogoTapContainer
    // Error parsing type: , name: backButton
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: showsLogo
    // Error parsing type: , name: homeButtonPadding
    // Error parsing type: , name: backButtonPadding
}

- (void).cxx_destruct;
- (void)setShowsLogo:(_Bool)arg1 animated:(_Bool)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, copy) NSString *text;
@property(nonatomic) _Bool showsLogo; // @synthesize showsLogo;
@property(nonatomic, readonly) NFUILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic, readonly) UIButton *backButton; // @synthesize backButton;
@property(nonatomic, readonly) UIView *netflixLogoTapContainer; // @synthesize netflixLogoTapContainer;
@property(nonatomic, readonly) UIImageView *netflixLogo; // @synthesize netflixLogo;

@end

