//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <ArgoCore/FalcorDataSource-Protocol.h>
#import <ArgoCore/FalcorLoggerDelegate-Protocol.h>

__attribute__((visibility("hidden")))
@interface _TtC8ArgoCore24ACFModelDelegateMediator : NSObject <FalcorDataSource, FalcorLoggerDelegate>
{
    // Error parsing type: , name: model
}

- (void).cxx_destruct;
- (id)init;
- (id)falcor:(id)arg1 preCallWithKeyPaths:(id)arg2;
- (id)falcor:(id)arg1 preGetWithKeyPaths:(id)arg2;
- (id)falcor:(id)arg1 callWithParams:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)falcor:(id)arg1 getWithParams:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)falcor:(id)arg1 logDebugUserInfo:(id)arg2;
- (void)falcor:(id)arg1 logDebug:(id)arg2;
- (void)falcor:(id)arg1 logInfo:(id)arg2;
- (_Bool)enableExNetworkLoggingInFalcor:(id)arg1;
- (void)falcor:(id)arg1 logError:(id)arg2;
- (_Bool)enableLoggingInFalcor:(id)arg1;

@end

