//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface _TtC4Argo21ActionSheetController : UIViewController
{
    // Error parsing type: , name: animator
    // Error parsing type: , name: subview
    // Error parsing type: , name: sheetTitle
    // Error parsing type: , name: contentInset
    // Error parsing type: , name: closeButton
    // Error parsing type: , name: bottomConstraint
    // Error parsing type: , name: heightConstraint
    // Error parsing type: , name: titleLabelHeightConstraint
    // Error parsing type: , name: highlightIndexPath
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: tableview
    // Error parsing type: , name: delegate
    // Error parsing type: , name: dataSource
    // Error parsing type: , name: anchor
    // Error parsing type: , name: _cellProvider
    // Error parsing type: , name: viewTranslation
    // Error parsing type: , name: concreteProvider
    // Error parsing type: , name: userInfo
    // Error parsing type: , name: presentationSessionId
    // Error parsing type: , name: customRowHeight
    // Error parsing type: , name: displayConfiguration
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)handleDismissWithSender:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)handleDynamicTypeChangeWithNotification:(id)arg1;
- (_Bool)accessibilityPerformEscape;
@property(nonatomic) _Bool accessibilityViewIsModal;
- (_Bool)respondsToSelector:(SEL)arg1;
- (void)dismissVCWithSessionOptionWithEndSession:(_Bool)arg1;
- (void)dismissVC;
@property(nonatomic, readonly) unsigned long long supportedInterfaceOrientations;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(long long)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewSafeAreaInsetsDidChange;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

