//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <NFRCW/UITextFieldDelegate-Protocol.h>

@class UIButton, UIImageView, UILabel, UITextField;

@interface _TtC56googlemac_iPhone_recaptcha_recaptcha_2fa_view_controller26Recaptcha2FAViewController : UIViewController <UITextFieldDelegate>
{
    // Error parsing type: , name: verificationHandler
    // Error parsing type: , name: pendingTokenPromise
    // Error parsing type: , name: pinTextField
    // Error parsing type: , name: messageLabel
    // Error parsing type: , name: verifyButton
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: recaptchaLogo
    // Error parsing type: , name: errorLabel
    // Error parsing type: , name: explanationLabel
    // Error parsing type: , name: privacyAndTermsLabel
    // Error parsing type: , name: lastError
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)textFieldChanged:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)cancelVerification:(id)arg1;
- (void)verifyAccount:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic, retain) UILabel *privacyAndTermsLabel; // @synthesize privacyAndTermsLabel;
@property(nonatomic, retain) UILabel *explanationLabel; // @synthesize explanationLabel;
@property(nonatomic, retain) UILabel *errorLabel; // @synthesize errorLabel;
@property(nonatomic, retain) UIImageView *recaptchaLogo; // @synthesize recaptchaLogo;
@property(nonatomic, retain) UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic, retain) UIButton *verifyButton; // @synthesize verifyButton;
@property(nonatomic, retain) UILabel *messageLabel; // @synthesize messageLabel;
@property(nonatomic, retain) UITextField *pinTextField; // @synthesize pinTextField;

@end

