//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NFUIFamiliarityViewCell.h"

@interface _TtC4Argo27NFUIComedyFeedOutroCardView : NFUIFamiliarityViewCell
{
    // Error parsing type: , name: RATIO
    // Error parsing type: , name: animation
    // Error parsing type: , name: background
    // Error parsing type: , name: title
    // Error parsing type: , name: button
    // Error parsing type: , name: partiallyVisibleAxis
    // Error parsing type: , name: isVisible
}

+ (id)viewModelForEntityId:(id)arg1;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)prepareForReuse;
- (void)tapped;
- (void)commonInit;
- (void)cellWillDisplay:(id)arg1;
- (void)cellDidEndDisplaying:(id)arg1;
- (void)cellDidDisappearFromContext:(unsigned long long)arg1;
- (void)cellDidAppearFromContext:(unsigned long long)arg1;
- (void)cellDidBecomeActive:(id)arg1;
- (void)cellDidBecomeInactive:(id)arg1;

@end

