//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC4Argo16SparseLolomoItem.h"

@interface _TtC4Argo23SparseLolomoPreviewItem : _TtC4Argo16SparseLolomoItem
{
    // Error parsing type: , name: node
    // Error parsing type: , name: previewEdge
}

- (void).cxx_destruct;

@end

