//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NFUIFamiliarityViewModel.h"

@interface _TtC4Argo32NFUIComedyFeedOutroCardViewModel : NFUIFamiliarityViewModel
{
}

- (id)initWithListModel:(id)arg1 withIndexPath:(id)arg2;
- (id)initWithEntityId:(id)arg1;
- (id)init;
@property(nonatomic) _Bool shouldCacheSize;

@end

