//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFManifestCommon/_TtC16NFManifestCommon8Manifest.h>

#import <NFManifestCommon/_TtP16NFManifestCommon18NFFilteredManifest_-Protocol.h>

@class NSArray, NSSet;

@interface _TtC16NFManifestCommon16FilteredManifest : _TtC16NFManifestCommon8Manifest <_TtP16NFManifestCommon18NFFilteredManifest_>
{
    // Error parsing type: , name: offline
    // Error parsing type: , name: wifi
    // Error parsing type: , name: cellularVideoBitrateCap
    // Error parsing type: , name: platformConfigProvider
    // Error parsing type: , name: filteredManifestDelegate
    // Error parsing type: , name: filteredStreamDownloadableIds
    // Error parsing type: , name: filteredTrackNames
    // Error parsing type: , name: dupeDlidToResolutions
    // Error parsing type: , name: cachedTrackPreferenceArray
    // Error parsing type: , name: validVideoTrackCount
    // Error parsing type: , name: hasHEVC
}

- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;
@property(nonatomic, readonly) NSArray *sortedTrackPreferenceArray;
- (void)additionalVideoFilterPass;
- (void)setupFilters;
- (id)initWithDictionary:(id)arg1 filteredManifestDelegate:(id)arg2;
@property(nonatomic) _Bool hasHEVC; // @synthesize hasHEVC;
@property(nonatomic) unsigned long long validVideoTrackCount; // @synthesize validVideoTrackCount;
@property(nonatomic, copy) NSSet *filteredTrackNames;
@property(nonatomic, copy) NSSet *filteredStreamDownloadableIds;

@end

