//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NFUIFamiliarityRowCell.h"

@interface _TtC4Argo24NFUILolomoFeedDefaultRow : NFUIFamiliarityRowCell
{
}

+ (id)customLayout;
+ (_Bool)shouldReturnClassForType:(id)arg1 withModel:(id)arg2;
+ (id)reuseIdentifier;
+ (void)registerSelf;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)registrationType;
- (double)minimumInterItemSpacingForSection:(long long)arg1;
- (double)minimumLineSpacingForSection:(long long)arg1;
- (struct UIEdgeInsets)insetsForSection:(long long)arg1;
- (void)didSelectItemAtIndexPath:(id)arg1;
- (struct CGSize)calculatedSize:(struct CGSize)arg1 withModel:(id)arg2 withCollectionView:(id)arg3;

@end

