//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface _TtC16NFManifestCommon13TrickplayInfo : NSObject
{
    // Error parsing type: , name: data
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSArray *urls;
@property(nonatomic, readonly) unsigned long long size;
@property(nonatomic, readonly) unsigned long long height;
@property(nonatomic, readonly) unsigned long long width;
@property(nonatomic, readonly) NSString *downloadableId;
- (id)initWithDictionary:(id)arg1;

@end

