//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIAccessibilityElement.h>

@class NSString;

@interface _TtC4Argo32AROFilterBarAccessibilityElement : UIAccessibilityElement
{
    // Error parsing type: , name: filterBar
    // Error parsing type: , name: focusedIndexPath
    // Error parsing type: , name: didMakeInitialFocus
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithAccessibilityContainer:(id)arg1;
- (_Bool)accessibilityPerformEscape;
@property(nonatomic, copy) NSString *accessibilityLabel;
@property(nonatomic) unsigned long long accessibilityTraits;
- (_Bool)accessibilityActivate;
- (void)accessibilityDecrement;
- (void)accessibilityIncrement;
- (void)accessibilityElementDidLoseFocus;
- (void)accessibilityElementDidBecomeFocused;

@end

