//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "NFUICollectionViewCellManagerDelegate-Protocol.h"

@interface _TtC4Argo28NFUIComedyFeedViewController : UIViewController <NFUICollectionViewCellManagerDelegate>
{
    // Error parsing type: , name: shouldInitialBounce
    // Error parsing type: , name: feedViewController
    // Error parsing type: , name: model
    // Error parsing type: , name: generator
    // Error parsing type: , name: timer
    // Error parsing type: , name: expirySession
    // Error parsing type: , name: isShortClips
    // Error parsing type: , name: isPlatformFeed
    // Error parsing type: , name: toast
    // Error parsing type: , name: completionView
    // Error parsing type: , name: contentToast
    // Error parsing type: , name: isVisible
    // Error parsing type: , name: isActive
    // Error parsing type: , name: nfui_tabBarItem
    // Error parsing type: , name: pendingDeeplinkClipId
    // Error parsing type: , name: isAnnouncing
    // Error parsing type: , name: isPresentingDisplayPage
    // Error parsing type: , name: retries
    // Error parsing type: , name: activityIndicator
    // Error parsing type: , name: dpNav
    // Error parsing type: , name: retryContainer
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)screenshotTaken:(id)arg1;
- (void)announcementDidFinish:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
@property(nonatomic) _Bool isPlatformFeed; // @synthesize isPlatformFeed;
@property(nonatomic) _Bool isShortClips; // @synthesize isShortClips;

@end

