//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSSet, NSString;
@protocol _TtP16NFManifestCommon7NFTrack_;

@interface _TtC16NFManifestCommon6Stream : NSObject
{
    // Error parsing type: , name: duped
    // Error parsing type: , name: track
    // Error parsing type: , name: stream
}

+ (int)streamTypeFlagFromStreamProfile:(long long)arg1;
+ (long long)streamProfileFromString:(id)arg1;
+ (id)streamProfileNameFromStreamProfile:(long long)arg1;
+ (_Bool)isDVStreamProfile:(long long)arg1;
+ (_Bool)isHEVCStreamProfile:(long long)arg1;
+ (_Bool)isHEVCStream:(id)arg1;
+ (_Bool)isHevcDvStream:(id)arg1;
+ (_Bool)isHevcSdrStream:(id)arg1;
+ (_Bool)isAL1Stream:(id)arg1;
+ (_Bool)isCE3Stream:(id)arg1;
+ (id)mimeCodecFromStreamProfile:(long long)arg1;
+ (id)mimeTypeFromStreamProfile:(long long)arg1;
- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *debugDescription;
@property(nonatomic, readonly) NSSet *allStreamCdnIdSet;
@property(nonatomic, readonly) NSArray *allStreamUrls;
- (id)urlStringForCdnId:(long long)arg1;
@property(nonatomic, readonly) unsigned long long size;
@property(nonatomic, readonly) unsigned long long peakBitrate;
@property(nonatomic, readonly) unsigned long long nominalBitrate;
@property(nonatomic, readonly) long long streamProfile;
@property(nonatomic, readonly) NSString *streamProfileName;
@property(nonatomic, readonly) long long streamMediaType;
@property(nonatomic, readonly) NSString *downloadableId;
- (id)initWithDictionary:(id)arg1 track:(id)arg2;
@property(nonatomic, retain) NSDictionary *stream; // @synthesize stream;
@property(nonatomic, retain) id <_TtP16NFManifestCommon7NFTrack_> track; // @synthesize track;
@property(nonatomic) _Bool duped; // @synthesize duped;
@property(nonatomic, readonly) NSDictionary *ssixRange;
@property(nonatomic, readonly) NSDictionary *sidxRange;

@end

