//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC4Argo32NFUIComedyFeedGenericProgressBar : UIView
{
    // Error parsing type: , name: maxAlpha
    // Error parsing type: , name: orientation
    // Error parsing type: , name: progressBar
    // Error parsing type: , name: currentXScale
    // Error parsing type: , name: currentYScale
    // Error parsing type: , name: shapeLayer
    // Error parsing type: , name: animation
    // Error parsing type: , name: isLoadingInternal
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

