//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC4Argo21MDXActionSheetManager : NSObject
{
    // Error parsing type: , name: dataSource
    // Error parsing type: , name: cellProvider
    // Error parsing type: , name: sinks
    // Error parsing type: , name: presentationSessionId
    // Error parsing type: , name: rowHeight
    // Error parsing type: , name: mdxFlowViewController
    // Error parsing type: , name: presentingController
}

- (void).cxx_destruct;
- (id)init;
- (void)handleButtonAction;

@end

