//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFManifestAccess/_TtP16NFManifestCommon7NFTrack_-Protocol.h>

@class NSArray, NSString;

@protocol _TtP16NFManifestCommon11NFTextTrack_ <_TtP16NFManifestCommon7NFTrack_>
+ (long long)typeFromSubtitleTrackTypeString:(NSString *)arg1;
+ (NSString *)identifierForImageBased;
+ (NSString *)identifierForWebVTT;
+ (NSString *)identifierForRichWebVTT;
@property(readonly, copy, nonatomic) NSArray *rankSortedCdnInfoArray;
@property(readonly, copy, nonatomic) NSString *languageCode;
@property(readonly, copy, nonatomic) NSString *language;
@property(readonly, copy, nonatomic) NSString *displayName;
@property(readonly, nonatomic) long long textTrackType;
@property(readonly, nonatomic) _Bool isClosedCaption;
@property(readonly, nonatomic) _Bool isForcedNarrative;
@property(readonly, nonatomic) _Bool hasRichWebVTT;
@property(readonly, nonatomic) _Bool hasWebVTT;
@property(readonly, nonatomic) _Bool hasImageBased;
- (void)enumerateTextStreams:(void (^)(id <NFTextStream>, unsigned long long, _Bool *))arg1;
- (NSString *)downloadableIdForStreamIdentifier:(NSString *)arg1;
@end

