//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFNetworkState/NSObject-Protocol.h>

@protocol _TtP14NFNetworkState20NFReachabilityStatus_, _TtP14NFNetworkState29NFReachabilityObservationDeck_;

@protocol _TtP14NFNetworkState22NFReachabilityProvider_ <NSObject>
@property(nonatomic, readonly) id <_TtP14NFNetworkState29NFReachabilityObservationDeck_> reachabilityObservationDeck;
@property(nonatomic, readonly) id <_TtP14NFNetworkState20NFReachabilityStatus_> reachabilityStatus;
@end

