//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFManifestAccess/NSCopying-Protocol.h>
#import <NFManifestAccess/NSObject-Protocol.h>

@class NSString;

@protocol _TtP16NFManifestCommon9NFCdnInfo_ <NSCopying, NSObject>
@property(readonly, nonatomic) long long locationLevel;
@property(readonly, nonatomic) long long locationWeight;
@property(readonly, copy, nonatomic) NSString *locationKey;
@property(readonly, nonatomic) _Bool lowgrade;
@property(readonly, nonatomic) long long identifier;
@property(readonly, nonatomic) long long rank;
@property(readonly, copy, nonatomic) NSString *name;
@end

