//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFManifestAccess/NSObject-Protocol.h>

@class NSArray, NSDictionary, NSSet, NSString;
@protocol NFCdnInfo, NFTextTrack, _TtP16NFManifestCommon10NFManifest_, _TtP16NFManifestCommon12NFAudioTrack_, _TtP16NFManifestCommon8NFStream_;

@protocol _TtP16NFManifestCommon10NFManifest_ <NSObject>
+ (NSArray *)rankSortedCdnInfoArrayForServers:(NSArray *)arg1 manifest:(id <_TtP16NFManifestCommon10NFManifest_>)arg2;
@property(readonly, copy, nonatomic) NSArray *trickplayInfos;
@property(readonly, copy, nonatomic) NSDictionary *downloadIdToVideoResolutionClass;
@property(readonly, copy, nonatomic) NSDictionary *maxBitrateByVideoResolutionClass;
@property(readonly, copy, nonatomic) NSArray *sortedTrackPreferenceArray;
@property(readonly, copy, nonatomic) NSArray *rankSortedCdnInfoArray;
@property(readonly, copy, nonatomic) NSString *movieId;
- (NSArray *)validCdnForStream:(id <_TtP16NFManifestCommon8NFStream_>)arg1;
- (_Bool)isAudioTrackInTrackPrefereceArray:(id <_TtP16NFManifestCommon12NFAudioTrack_>)arg1;
- (_Bool)isTextTrackInTrackPrefereceArray:(id <NFTextTrack>)arg1;
- (NSDictionary *)locationForKey:(NSString *)arg1;
- (id <NFCdnInfo>)cdnInfoAfter:(id <NFCdnInfo>)arg1 validCdnIdSet:(NSSet *)arg2;
- (id <NFCdnInfo>)cdnInfoFromCdnId:(long long)arg1;
- (void)enumerateTracks:(void (^)(id <_TtP16NFManifestCommon7NFTrack_>, unsigned long long, _Bool *))arg1;
- (void)enumerateTextTracks:(void (^)(id <NFTextTrack>, unsigned long long, _Bool *))arg1;
- (void)enumerateAudioTracks:(void (^)(id <_TtP16NFManifestCommon12NFAudioTrack_>, unsigned long long, _Bool *))arg1;
- (void)enumerateVideoTracks:(void (^)(id <NFVideoTrack>, unsigned long long, _Bool *))arg1;
@end

