//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFManifestAccess/_TtP16NFManifestCommon10NFManifest_-Protocol.h>

@class NSString;
@protocol _TtP16NFManifestCommon8NFStream_;

@protocol _TtP16NFManifestCommon17NFCachingManifest_ <_TtP16NFManifestCommon10NFManifest_>
- (id <_TtP16NFManifestCommon8NFStream_>)streamForDownlodable:(NSString *)arg1;
@end

