//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFNetworkState/NSObject-Protocol.h>

@protocol _TtP14NFNetworkState22NFReachabilityObserver_;

@protocol _TtP14NFNetworkState29NFReachabilityObservationDeck_ <NSObject>
- (void)removeReachabilityObserver:(id <_TtP14NFNetworkState22NFReachabilityObserver_>)arg1;
- (void)addReachabilityObserver:(id <_TtP14NFNetworkState22NFReachabilityObserver_>)arg1 initialState:(_Bool)arg2;
@end

