//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFManifestAccess/_TtP16NFManifestCommon8NFStream_-Protocol.h>

@class NSString;

@protocol _TtP16NFManifestCommon13NFAudioStream_ <_TtP16NFManifestCommon8NFStream_>
+ (unsigned long long)audioChannelCountFromString:(NSString *)arg1;
@property(readonly, nonatomic) _Bool isEncryptedAudio;
@property(readonly, nonatomic) unsigned long long audioChannelCount;
@end

