//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AVAudioSession, NSHashTable, NSString;

@interface AudioSessionAnnouncer : NSObject
{
    _Bool _checkSpecialAudioDevice;
    float _outputVolume;
    NSString *_currentAudioSessionPortType;
    NSString *_currentAudioRouteString;
    unsigned long long _currentFormats;
    unsigned long long _currentAirplayMode;
    NSHashTable *_delegates;
    AVAudioSession *_audioSession;
    unsigned long long _oldMode;
    unsigned long long _bluetoothFormats;
    unsigned long long _speakerFormats;
    unsigned long long _unknownCounter;
}

+ (id)sharedInstanceWithConfig:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) _Bool checkSpecialAudioDevice; // @synthesize checkSpecialAudioDevice=_checkSpecialAudioDevice;
@property(nonatomic) unsigned long long unknownCounter; // @synthesize unknownCounter=_unknownCounter;
@property(nonatomic) unsigned long long speakerFormats; // @synthesize speakerFormats=_speakerFormats;
@property(nonatomic) unsigned long long bluetoothFormats; // @synthesize bluetoothFormats=_bluetoothFormats;
@property(nonatomic) unsigned long long oldMode; // @synthesize oldMode=_oldMode;
@property(retain, nonatomic) AVAudioSession *audioSession; // @synthesize audioSession=_audioSession;
@property(retain, nonatomic) NSHashTable *delegates; // @synthesize delegates=_delegates;
@property(nonatomic) float outputVolume; // @synthesize outputVolume=_outputVolume;
@property(nonatomic) unsigned long long currentAirplayMode; // @synthesize currentAirplayMode=_currentAirplayMode;
@property(nonatomic) unsigned long long currentFormats; // @synthesize currentFormats=_currentFormats;
@property(retain, nonatomic) NSString *currentAudioRouteString; // @synthesize currentAudioRouteString=_currentAudioRouteString;
@property(retain, nonatomic) NSString *currentAudioSessionPortType; // @synthesize currentAudioSessionPortType=_currentAudioSessionPortType;
- (void)updateCurrentAudioSessionPortTypeAndRouteString;
- (void)audioRouteChanged;
- (void)audioRouteChangedCb:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)initWithConfig:(id)arg1;
- (void)unregisterDelegate:(id)arg1;
- (void)registerDelegate:(id)arg1;

@end

