//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BSGConfigurationBuilder : NSObject
{
}

+ (void)loadSendThreads:(id)arg1 options:(id)arg2;
+ (void)loadMaxBreadcrumbs:(id)arg1 options:(id)arg2;
+ (void)loadEndpoints:(id)arg1 options:(id)arg2;
+ (void)loadStringArray:(id)arg1 options:(id)arg2 key:(id)arg3;
+ (void)loadString:(id)arg1 options:(id)arg2 key:(id)arg3;
+ (void)loadBoolean:(id)arg1 options:(id)arg2 key:(id)arg3;
+ (id)configurationFromOptions:(id)arg1;

@end

