//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Nbp/NSObject-Protocol.h>

@class NSDictionary, NSMutableDictionary, NSString;

@protocol BugsnagClassLevelMetadataStore <NSObject>
+ (void)clearMetadataFromSection:(NSString *)arg1 withKey:(NSString *)arg2;
+ (void)clearMetadataFromSection:(NSString *)arg1;
+ (id)getMetadataFromSection:(NSString *)arg1 withKey:(NSString *)arg2;
+ (NSMutableDictionary *)getMetadataFromSection:(NSString *)arg1;
+ (void)addMetadata:(id)arg1 withKey:(NSString *)arg2 toSection:(NSString *)arg3;
+ (void)addMetadata:(NSDictionary *)arg1 toSection:(NSString *)arg2;
@end

