//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BugsnagKVStore : NSObject
{
}

+ (void)initialize;
- (id)stringForKey:(id)arg1 defaultValue:(id)arg2;
- (void)setString:(id)arg1 forKey:(id)arg2;
- (id)NSBooleanForKey:(id)arg1 defaultValue:(_Bool)arg2;
- (_Bool)booleanForKey:(id)arg1 defaultValue:(_Bool)arg2;
- (void)setBoolean:(_Bool)arg1 forKey:(id)arg2;

@end

