//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BugsnagEndpointConfiguration : NSObject
{
    NSString *_notify;
    NSString *_sessions;
}

- (void).cxx_destruct;
@property(retain) NSString *sessions; // @synthesize sessions=_sessions;
@property(retain) NSString *notify; // @synthesize notify=_notify;
- (id)initWithNotify:(id)arg1 sessions:(id)arg2;
- (id)init;

@end

