//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BugsnagCrashSentry : NSObject
{
}

- (void)reportUserException:(id)arg1 reason:(id)arg2 handledState:(id)arg3 appState:(id)arg4 callbackOverrides:(id)arg5 eventOverrides:(id)arg6 metadata:(id)arg7 config:(id)arg8;
- (unsigned int)mapKSToBSGCrashTypes:(id)arg1;
- (void)install:(id)arg1 apiClient:(id)arg2 onCrash:(CDUnknownFunctionPointerType)arg3;

@end

