//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BugsnagApp : NSObject
{
    NSString *_bundleVersion;
    NSString *_codeBundleId;
    NSString *_dsymUuid;
    NSString *_id;
    NSString *_releaseStage;
    NSString *_type;
    NSString *_version;
}

+ (void)populateFields:(id)arg1 dictionary:(id)arg2 config:(id)arg3 codeBundleId:(id)arg4;
+ (id)appWithDictionary:(id)arg1 config:(id)arg2 codeBundleId:(id)arg3;
+ (id)deserializeFromJson:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *releaseStage; // @synthesize releaseStage=_releaseStage;
@property(retain, nonatomic) NSString *id; // @synthesize id=_id;
@property(retain, nonatomic) NSString *dsymUuid; // @synthesize dsymUuid=_dsymUuid;
@property(retain, nonatomic) NSString *codeBundleId; // @synthesize codeBundleId=_codeBundleId;
@property(retain, nonatomic) NSString *bundleVersion; // @synthesize bundleVersion=_bundleVersion;
- (id)toDict;

@end

