//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface CurrentNetworkInfoProvider : NSObject
{
    NSMutableDictionary *_interfaceMap;
}

+ (id)updateInfoDictionary:(id)arg1 interfaceFamily:(int)arg2 interfaceName:(id)arg3 ip4or6Address:(id)arg4 maskAddress:(id)arg5;
+ (id)networkInterfacesAndGatewayInfo;
+ (id)fillInLinkMediaInfo:(int)arg1 if_name:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *interfaceMap; // @synthesize interfaceMap=_interfaceMap;
- (id)currentNetwork;
- (void)findNetworkInterfaces;
- (void)cacheNetworkInterfaces;
- (id)fillInInterfaceDetails:(int)arg1 interfaceName:(id)arg2 ip4or6Address:(id)arg3;
- (id)getDefaultGatewayInterfaceName;

@end

