//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DeepLinkAction, NSNumber, NSTimer, SFSafariViewController, UIWindow, _TtC4Argo17VanityURLResolver;
@protocol DeepLinkControllerDelegateProtocol, NFInAppURLHandler;

@interface DeepLinkController : NSObject
{
    _Bool _enabled;
    _Bool _echo;
    DeepLinkAction *_pendingAction;
    id <DeepLinkControllerDelegateProtocol> _delegate;
    SFSafariViewController *_safariViewController;
    _TtC4Argo17VanityURLResolver *_vanityURLResolver;
    id <NFInAppURLHandler> _urlHandler;
    UIWindow *_hiddenWindow;
    NSTimer *_dismissHiddenWindowTimer;
    NSNumber *_inputContextId;
}

+ (_Bool)isValidNFLXURL:(id)arg1;
+ (void)configureWithAction:(id)arg1;
+ (_Bool)configureWithLegacyQParam:(id)arg1;
+ (_Bool)configureWithPushNotification:(id)arg1;
+ (_Bool)configureWithUserActivity:(id)arg1;
+ (void)configureWithSafariCookie;
+ (_Bool)configureWithURL:(id)arg1;
+ (id)sharedController;
+ (id)titleDeepLinkForEntity:(id)arg1 trackId:(id)arg2;
+ (id)watchDeepLinkForEntity:(id)arg1 trackId:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSNumber *inputContextId; // @synthesize inputContextId=_inputContextId;
@property(retain, nonatomic) NSTimer *dismissHiddenWindowTimer; // @synthesize dismissHiddenWindowTimer=_dismissHiddenWindowTimer;
@property(retain, nonatomic) UIWindow *hiddenWindow; // @synthesize hiddenWindow=_hiddenWindow;
@property(retain, nonatomic) id <NFInAppURLHandler> urlHandler; // @synthesize urlHandler=_urlHandler;
@property(retain, nonatomic) _TtC4Argo17VanityURLResolver *vanityURLResolver; // @synthesize vanityURLResolver=_vanityURLResolver;
@property(retain, nonatomic) SFSafariViewController *safariViewController; // @synthesize safariViewController=_safariViewController;
@property(nonatomic) __weak id <DeepLinkControllerDelegateProtocol> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool echo; // @synthesize echo=_echo;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) DeepLinkAction *pendingAction; // @synthesize pendingAction=_pendingAction;
- (_Bool)actionContainsAutoLoginToken:(id)arg1;
- (void)tryToResolveVanityURL:(id)arg1;
- (void)createActionFromURL:(id)arg1;
- (void)removeInputContextIfNeeded;
- (void)flushPendingAction;
- (void)clearPendingAction;
- (void)reset;
- (_Bool)hasNonMemberPlaybackLink;
- (_Bool)hasNonMemberOverrideLink;
- (void)dismissHiddenWindow;
- (void)initLinkToWebUI;

@end

