//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTLProbeClient/FTLProbeFetcherProvider-Protocol.h>

@class NSMutableDictionary, NSString;

@interface FTLProbeURLSessionFetcherProvider : NSObject <FTLProbeFetcherProvider>
{
    NSMutableDictionary *_fetchers;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *fetchers; // @synthesize fetchers=_fetchers;
- (id)fetcherForProbe:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

