//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFPlaylistGeneration/NSObject-Protocol.h>

@class NSString;

@protocol HLSSegmentEnumeratorProtocol <NSObject>
- (_Bool)useProxy;
- (void)enumerateHLSSegmentForVideoOption:(NSString *)arg1 isIFrame:(_Bool)arg2 withBlock:(void (^)(unsigned long long, unsigned int, double, double, unsigned long long, NSDictionary *, _Bool *))arg3;
@end

