//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary, NSString, UIGestureRecognizer, UIView;

@interface HudDownloadableIdSelector : NSObject
{
    _Bool _forAutomation;
    NSString *_movieId;
    NSArray *_videoCodecGroupNames;
    UIView *_parentView;
    UIGestureRecognizer *_closingGestureRecognizer;
    NSArray *_accessLogArray;
    NSMutableDictionary *_data;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *data; // @synthesize data=_data;
@property(retain, nonatomic) NSArray *accessLogArray; // @synthesize accessLogArray=_accessLogArray;
@property(nonatomic) __weak UIGestureRecognizer *closingGestureRecognizer; // @synthesize closingGestureRecognizer=_closingGestureRecognizer;
@property(nonatomic) __weak UIView *parentView; // @synthesize parentView=_parentView;
@property(retain, nonatomic) NSArray *videoCodecGroupNames; // @synthesize videoCodecGroupNames=_videoCodecGroupNames;
@property(retain, nonatomic) NSString *movieId; // @synthesize movieId=_movieId;
@property(nonatomic) _Bool forAutomation; // @synthesize forAutomation=_forAutomation;
- (void)setCheckBoxInView:(id)arg1 toState:(id)arg2;
- (void)setCheckBoxImage:(id)arg1 forState:(id)arg2;
- (void)setGroupEntryCheckBoxesToGroupState:(id)arg1;
- (void)flipStateInfoInItem:(id)arg1 leaveMixedGroupAsIs:(_Bool)arg2;
- (void)sendChangeBackToPlatform;
- (void)setCheckBoxImageForGroup:(id)arg1 andItem:(id)arg2;
- (void)selectionSanityCheck;
- (void)setGroupHeadEntryCheckBoxToReflectGroupState:(id)arg1;
- (void)methodTouchUpInside:(id)arg1;
- (void)flipStateForAllData;
- (void)handleDoubleTouch:(id)arg1;
- (void)handleTouch:(id)arg1;
- (id)composeVideoDownloadableIdsStringAndStateArray:(id)arg1 forCodec:(id)arg2;
- (id)createUIControlWithText:(id)arg1 state:(id)arg2 parentView:(id)arg3 viewAbove:(id)arg4 extraTopSpace:(long long)arg5;
- (id)playlistCodecTypeToProfileCodecType:(id)arg1;
- (void)applyAccessLogToData;
- (void)addAccessLog:(id)arg1;
- (long long)totalHeight;
- (void)processDownloadableIdInfo:(id)arg1 withParentView:(id)arg2 viewAbove:(id)arg3;
- (id)initWithClosingGestureRecognizer:(id)arg1;

@end

