//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Nbp/MdxSessionDelegate-Protocol.h>
#import <Nbp/MdxTarget-Protocol.h>

@class MdxSession, NSString;
@protocol MdxDevice, MdxTargetDelegate;

@interface IosMdxTarget : NSObject <MdxSessionDelegate, MdxTarget>
{
    _Bool attemptedRemoteLogin;
    id <MdxTargetDelegate> _delegate;
    id <MdxDevice> _device;
    MdxSession *_session;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MdxSession *session; // @synthesize session=_session;
@property(retain, nonatomic) id <MdxDevice> device; // @synthesize device=_device;
@property _Bool attemptedRemoteLogin; // @synthesize attemptedRemoteLogin;
@property(nonatomic) __weak id <MdxTargetDelegate> delegate; // @synthesize delegate=_delegate;
- (id)_sendAppMessage:(id)arg1 arguments:(id)arg2 extraArguments:(id)arg3;
- (id)stop:(id)arg1;
- (id)stop:(id)arg1:(id)arg2;
- (id)skip:(id)arg1:(int)arg2;
- (id)skip:(id)arg1:(int)arg2:(id)arg3;
- (id)setVolume:(id)arg1:(int)arg2;
- (id)setVolume:(id)arg1:(int)arg2:(id)arg3;
- (id)setTime:(id)arg1:(int)arg2;
- (id)setTime:(id)arg1:(int)arg2:(id)arg3;
- (id)setAudioSubtitles:(id)arg1:(id)arg2:(id)arg3;
- (id)setAudioSubtitles:(id)arg1:(id)arg2;
- (id)sendAppMessage:(id)arg1:(id)arg2;
- (id)resume:(id)arg1;
- (id)resume:(id)arg1:(id)arg2;
- (id)play:(id)arg1:(id)arg2;
- (id)play:(id)arg1:(id)arg2:(id)arg3;
- (id)_translateBooleansInDictionary:(id)arg1 forKeys:(id)arg2;
- (id)skipIntro:(id)arg1 source:(id)arg2;
- (id)pause:(id)arg1:(id)arg2;
- (id)pause:(id)arg1;
- (id)getPlayerState:(id)arg1;
- (id)getPlayerState;
- (id)getCapabilities:(id)arg1;
- (id)getCapabilities;
- (id)getAudioSubtitles:(id)arg1:(id)arg2;
- (id)getAudioSubtitles:(id)arg1;
- (id)dismissPostPlay:(id)arg1:(id)arg2;
- (id)dismissPostPlay:(id)arg1;
- (id)disconnectFromApp:(_Bool)arg1;
- (id)connectToApp:(long long)arg1;
- (id)connectToApp:(long long)arg1:(id)arg2;
- (id)bindMsgStream:(id)arg1:(int)arg2:(CDUnknownBlockType)arg3:(CDUnknownBlockType)arg4;
- (id)autoAdvance:(id)arg1:(int)arg2;
- (id)autoAdvance:(id)arg1:(int)arg2:(id)arg3;
@property(readonly) NSString *mdxUuid;
@property(readonly) long long launchState;
@property(readonly) _Bool isAvailable;
@property(readonly) NSString *id;
@property(readonly) NSString *modelNumber;
@property(readonly) NSString *modelName;
@property(readonly) NSString *manufacturer;
@property(readonly) NSString *friendlyName;
@property(readonly) long long discoveryState;
- (id)initWithDevice:(id)arg1;
@property(readonly) NSString *targetType;
- (void)propertyDidChange:(id)arg1 oldValue:(id)arg2 newValue:(id)arg3;
@property(readonly) NSString *remoteLoginSessionId;
@property(readonly) _Bool isWaitingOnSignin;
@property(readonly) _Bool canRemoteLogin;
- (void)remoteLoginResponse:(id)arg1;
- (void)remoteLoginUserInteractionRequired:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)didAttemptRemoteLogin;
- (void)appConnectionDidEnd;
- (void)didReceiveAppMessage:(id)arg1;
- (void)launchStateDidChange:(long long)arg1;
- (void)discoveryStateDidChange:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

