//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Nbp/MdxApi.h>

#import <Nbp/MdxDiscoveryDelegate-Protocol.h>

@class NSMapTable, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface IosMdxApi : MdxApi <MdxDiscoveryDelegate>
{
    _Bool _isStarted;
    NSMapTable *_devices;
    NSObject<OS_dispatch_queue> *_targetQueue;
    NSString *_lastProfileId;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *lastProfileId; // @synthesize lastProfileId=_lastProfileId;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *targetQueue; // @synthesize targetQueue=_targetQueue;
@property(nonatomic) _Bool isStarted; // @synthesize isStarted=_isStarted;
@property(retain, nonatomic) NSMapTable *devices; // @synthesize devices=_devices;
- (void)updatedDevice:(id)arg1;
- (void)lostDevice:(id)arg1;
- (void)foundDevice:(id)arg1;
- (void)handledUnexpectedException:(id)arg1;
- (id)stop;
- (id)start;
- (id)reset;
- (void)refreshDevices;
- (void)configure:(id)arg1;
- (void)unload;
- (void)load:(id)arg1:(id)arg2:(CDUnknownBlockType)arg3;
- (void)load:(id)arg1:(CDUnknownBlockType)arg2;
- (id)initWithBridge:(id)arg1 castDiscoveryProvider:(id)arg2;
- (id)init;
- (id)config;
- (id)availableDevices;
- (id)version;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

