//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "AnnotationDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class NSString, UIButton, UILabel, UITextView, UIView, iPFTAnnotationView, iPFTSubmitData;

@interface iPFTAnnotationViewController : UIViewController <AnnotationDelegate, UITextViewDelegate, UIGestureRecognizerDelegate>
{
    iPFTAnnotationView *_activeAnnotation;
    float _originalX;
    float _position0;
    float _position1;
    float _position2;
    UIView *_viewDetails;
    UITextView *_textDetails;
    UILabel *_labelDetailsPlaceholder;
    UIButton *_buttonDelete;
    UIButton *_buttonDone;
    UILabel *_labelAnnotationTitle;
    iPFTSubmitData *_submitData;
}

- (void).cxx_destruct;
@property(retain, nonatomic) iPFTSubmitData *submitData; // @synthesize submitData=_submitData;
@property(nonatomic) __weak UILabel *labelAnnotationTitle; // @synthesize labelAnnotationTitle=_labelAnnotationTitle;
@property(nonatomic) __weak UIButton *buttonDone; // @synthesize buttonDone=_buttonDone;
@property(nonatomic) __weak UIButton *buttonDelete; // @synthesize buttonDelete=_buttonDelete;
@property(nonatomic) __weak UILabel *labelDetailsPlaceholder; // @synthesize labelDetailsPlaceholder=_labelDetailsPlaceholder;
@property(nonatomic) __weak UITextView *textDetails; // @synthesize textDetails=_textDetails;
@property(nonatomic) __weak UIView *viewDetails; // @synthesize viewDetails=_viewDetails;
- (void)buttonDeletePressed:(id)arg1;
- (void)buttonDonePressed:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)tappedAnnotation:(id)arg1;
- (void)alertConfirmDelete;
- (void)hideAnnotationDetails:(_Bool)arg1;
- (void)displayAnnotationDetails;
- (void)deleteAnnotation:(id)arg1;
- (void)alertMaxAnnotationsReached;
- (void)addNewAnnotationAtPosition:(struct CGPoint)arg1;
- (void)addAnnotationGestureDetected:(id)arg1;
- (void)panGestureDetected:(id)arg1;
- (void)moveDetailView:(float)arg1 animated:(_Bool)arg2;
- (void)addGestureRecognizers;
- (void)keyboardWillHide;
- (void)keyboardWillShow;
- (void)initData;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

