//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "iPFTModule.h"

@class NSData, NSMutableArray, UIImage;

@interface iPFTModuleRedmineTicket : iPFTModule
{
    int _requestMax;
    int _responseCount;
    NSData *_submitStacktrace;
    NSData *_submitLog;
    UIImage *_submitImage;
    NSMutableArray *_uploads;
}

- (void).cxx_destruct;
- (void)sendRequest:(id)arg1;
- (void)postTicket;
- (void)uploadTextfile:(id)arg1;
- (void)uploadImage:(id)arg1;
- (void)send:(id)arg1;
- (id)init;

@end

