//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "iPFTBaseViewController.h"

@class UIImageView, UILabel, UISegmentedControl, UIView, iPFTAnnotationViewController, iPFTPaintViewController;

@interface iPFTMainViewController : iPFTBaseViewController
{
    _Bool _isDrawing;
    UIImageView *_imageScreenshot;
    iPFTAnnotationViewController *_viewAnnotations;
    iPFTPaintViewController *_viewPaint;
    UILabel *_labelDescription;
    UISegmentedControl *_segmentedBrushes;
    UIView *_viewTouchEvent;
    UILabel *_labelTouchEvent;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UILabel *labelTouchEvent; // @synthesize labelTouchEvent=_labelTouchEvent;
@property(nonatomic) __weak UIView *viewTouchEvent; // @synthesize viewTouchEvent=_viewTouchEvent;
@property(nonatomic) __weak UISegmentedControl *segmentedBrushes; // @synthesize segmentedBrushes=_segmentedBrushes;
@property(nonatomic) __weak UILabel *labelDescription; // @synthesize labelDescription=_labelDescription;
@property(retain, nonatomic) iPFTPaintViewController *viewPaint; // @synthesize viewPaint=_viewPaint;
@property(retain, nonatomic) iPFTAnnotationViewController *viewAnnotations; // @synthesize viewAnnotations=_viewAnnotations;
@property(nonatomic) __weak UIImageView *imageScreenshot; // @synthesize imageScreenshot=_imageScreenshot;
- (void)segmentedBrushChanged:(id)arg1;
- (void)cancelButtonPressed:(id)arg1;
- (void)nextButtonPressed:(id)arg1;
- (void)addPaintViewController:(struct CGRect)arg1;
- (void)addAnnotationViewController:(struct CGRect)arg1;
- (void)toggleDrawing:(id)arg1;
- (void)hideTouchEventOverlay;
- (void)showTouchEventOverlay;
- (void)addDoneButtonAsLeftNavbarButton;
- (void)addEditButtonAsLeftNavbarButton;
- (void)startInitialScreenshotAnimation;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)initData;

@end

