//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "iPFTBaseViewController.h"

#import "SKPSMTPMessageDelegate-Protocol.h"
#import "iPFTOptionViewDelegate-Protocol.h"

@class NSString, UIButton, UILabel, iPFTOptionView;

@interface iPFTOptionsViewController : iPFTBaseViewController <iPFTOptionViewDelegate, SKPSMTPMessageDelegate>
{
    iPFTOptionView *_optionName;
    iPFTOptionView *_optionScreenshot;
    iPFTOptionView *_optionMessage;
    iPFTOptionView *_optionStackTrace;
    UILabel *_labelOptionsDesc;
    UILabel *_labelName;
    UILabel *_labelNameDesc;
    UILabel *_labelEmailDesc;
    UILabel *_labelMessage;
    UILabel *_labelMessageDesc;
    UILabel *_labelScreenshot;
    UILabel *_labelScreenshotDesc;
    UILabel *_labelStacktrace;
    UILabel *_labelStacktraceDesc;
    UIButton *_buttonChangeName;
    UIButton *_buttonViewLog;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIButton *buttonViewLog; // @synthesize buttonViewLog=_buttonViewLog;
@property(nonatomic) __weak UIButton *buttonChangeName; // @synthesize buttonChangeName=_buttonChangeName;
@property(nonatomic) __weak UILabel *labelStacktraceDesc; // @synthesize labelStacktraceDesc=_labelStacktraceDesc;
@property(nonatomic) __weak UILabel *labelStacktrace; // @synthesize labelStacktrace=_labelStacktrace;
@property(nonatomic) __weak UILabel *labelScreenshotDesc; // @synthesize labelScreenshotDesc=_labelScreenshotDesc;
@property(nonatomic) __weak UILabel *labelScreenshot; // @synthesize labelScreenshot=_labelScreenshot;
@property(nonatomic) __weak UILabel *labelMessageDesc; // @synthesize labelMessageDesc=_labelMessageDesc;
@property(nonatomic) __weak UILabel *labelMessage; // @synthesize labelMessage=_labelMessage;
@property(nonatomic) __weak UILabel *labelEmailDesc; // @synthesize labelEmailDesc=_labelEmailDesc;
@property(nonatomic) __weak UILabel *labelNameDesc; // @synthesize labelNameDesc=_labelNameDesc;
@property(nonatomic) __weak UILabel *labelName; // @synthesize labelName=_labelName;
@property(nonatomic) __weak UILabel *labelOptionsDesc; // @synthesize labelOptionsDesc=_labelOptionsDesc;
@property(nonatomic) __weak iPFTOptionView *optionStackTrace; // @synthesize optionStackTrace=_optionStackTrace;
@property(nonatomic) __weak iPFTOptionView *optionMessage; // @synthesize optionMessage=_optionMessage;
@property(nonatomic) __weak iPFTOptionView *optionScreenshot; // @synthesize optionScreenshot=_optionScreenshot;
@property(nonatomic) __weak iPFTOptionView *optionName; // @synthesize optionName=_optionName;
- (void)messageSent:(id)arg1;
- (void)messageFailed:(id)arg1 error:(id)arg2;
- (void)sendEmailWithDefaultEmail;
- (void)sendingSuccessful;
- (void)sendingFailed:(id)arg1;
- (void)cancelButtonPressed:(id)arg1;
- (void)nextButtonPressed:(id)arg1;
- (void)buttonViewLogPressed:(id)arg1;
- (void)buttonEditNamePressed:(id)arg1;
- (void)switchStatus:(id)arg1;
- (void)initData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

