//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "iPFTBaseViewController.h"

#import "UIScrollViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSMutableArray, NSString, UIButton, UIImage, UIImageView, UILabel, UIPageControl, UIScrollView, UITextField, UIView;

@interface iPFTInfoViewController : iPFTBaseViewController <UIScrollViewDelegate, UITextFieldDelegate>
{
    UIImageView *_imageViewParentView;
    UIImage *_imageParentView;
    NSMutableArray *_arrayPages;
    UIScrollView *_scrollMain;
    UIPageControl *_pageControl;
    UIView *_viewWelcome;
    UILabel *_labelWelcomeTitle;
    UILabel *_labelWelcomeDescription;
    UIView *_viewStartFeedback;
    UILabel *_labelStartFeedbackTitle;
    UILabel *_labelStartFeedbackDescription;
    UIButton *_buttonStartFeedback;
    UIView *_viewContact;
    UIView *_viewContactContent;
    UILabel *_labelContactTitle;
    UILabel *_labelContactDescription;
    UITextField *_textContactName;
    UITextField *_textContactEmail;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UITextField *textContactEmail; // @synthesize textContactEmail=_textContactEmail;
@property(nonatomic) __weak UITextField *textContactName; // @synthesize textContactName=_textContactName;
@property(nonatomic) __weak UILabel *labelContactDescription; // @synthesize labelContactDescription=_labelContactDescription;
@property(nonatomic) __weak UILabel *labelContactTitle; // @synthesize labelContactTitle=_labelContactTitle;
@property(nonatomic) __weak UIView *viewContactContent; // @synthesize viewContactContent=_viewContactContent;
@property(nonatomic) __weak UIView *viewContact; // @synthesize viewContact=_viewContact;
@property(nonatomic) __weak UIButton *buttonStartFeedback; // @synthesize buttonStartFeedback=_buttonStartFeedback;
@property(nonatomic) __weak UILabel *labelStartFeedbackDescription; // @synthesize labelStartFeedbackDescription=_labelStartFeedbackDescription;
@property(nonatomic) __weak UILabel *labelStartFeedbackTitle; // @synthesize labelStartFeedbackTitle=_labelStartFeedbackTitle;
@property(nonatomic) __weak UIView *viewStartFeedback; // @synthesize viewStartFeedback=_viewStartFeedback;
@property(nonatomic) __weak UILabel *labelWelcomeDescription; // @synthesize labelWelcomeDescription=_labelWelcomeDescription;
@property(nonatomic) __weak UILabel *labelWelcomeTitle; // @synthesize labelWelcomeTitle=_labelWelcomeTitle;
@property(nonatomic) __weak UIView *viewWelcome; // @synthesize viewWelcome=_viewWelcome;
@property(nonatomic) __weak UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(nonatomic) __weak UIScrollView *scrollMain; // @synthesize scrollMain=_scrollMain;
@property(retain, nonatomic) NSMutableArray *arrayPages; // @synthesize arrayPages=_arrayPages;
@property(retain, nonatomic) UIImage *imageParentView; // @synthesize imageParentView=_imageParentView;
@property(nonatomic) __weak UIImageView *imageViewParentView; // @synthesize imageViewParentView=_imageViewParentView;
- (void)doneButtonPressed:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)dismissKeyboard:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)resetView;
- (void)moveView:(float)arg1;
- (void)resignAllResponders;
- (void)initData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

