//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSNumber, NSString, UIImage;

@interface iPFTSubmitData : NSObject
{
    NSString *_stacktrace;
    NSString *_log;
    NSNumber *_timestamp;
    UIImage *_screenshot;
    UIImage *_annotatedScreenshot;
    NSString *_message;
    NSMutableArray *_arrayAnnotations;
    NSString *_appName;
    NSString *_appVersion;
    NSString *_appBuild;
    NSString *_iosVersion;
    NSString *_deviceName;
}

+ (id)captureView:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *deviceName; // @synthesize deviceName=_deviceName;
@property(retain, nonatomic) NSString *iosVersion; // @synthesize iosVersion=_iosVersion;
@property(retain, nonatomic) NSString *appBuild; // @synthesize appBuild=_appBuild;
@property(retain, nonatomic) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(retain, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(retain, nonatomic) NSMutableArray *arrayAnnotations; // @synthesize arrayAnnotations=_arrayAnnotations;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) UIImage *annotatedScreenshot; // @synthesize annotatedScreenshot=_annotatedScreenshot;
@property(retain, nonatomic) UIImage *screenshot; // @synthesize screenshot=_screenshot;
@property(retain, nonatomic) NSNumber *timestamp; // @synthesize timestamp=_timestamp;
@property(retain, nonatomic) NSString *log; // @synthesize log=_log;
@property(retain, nonatomic) NSString *stacktrace; // @synthesize stacktrace=_stacktrace;
- (id)senderEmail;
- (id)senderName;
- (void)setSenderEmail:(id)arg1;
- (void)setSenderName:(id)arg1;
- (id)getDataForSubmission;
- (id)fetchTimestamp;
- (id)formatAppLogEntry:(id)arg1;
- (id)fetchApplicationLog;
- (id)fetchStacktrace;
- (void)fetchAnnotatedScreenshot:(id)arg1;
- (void)fetchScreenshot;
- (id)init;

@end

