//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIImageView;

@interface iPFTPaintViewController : UIViewController
{
    struct CGPoint _lastPoint;
    double _r;
    double _g;
    double _b;
    double _brush;
    double _opacity;
    _Bool _swiped;
    _Bool _erase;
    UIImageView *_drawImage;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIImageView *drawImage; // @synthesize drawImage=_drawImage;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)setEraserActive;
- (void)setBrushSize:(float)arg1;
- (void)initData;
- (void)viewDidLoad;

@end

