//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

@class UIImage, UIImageView;

@interface iPFTNavigationController : UINavigationController
{
    UIImage *_imageParentView;
    UIImageView *_imageViewBackground;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *imageViewBackground; // @synthesize imageViewBackground=_imageViewBackground;
@property(retain, nonatomic) UIImage *imageParentView; // @synthesize imageParentView=_imageParentView;
- (_Bool)shouldAutorotate;
- (long long)preferredInterfaceOrientationForPresentation;
- (void)initData;
- (void)viewWillAppear:(_Bool)arg1;

@end

