//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "iPFTBaseViewController.h"

@class NSString, NSURL, UIWebView;

@interface iPFTHelpViewController : iPFTBaseViewController
{
    NSString *_path;
    NSURL *_baseURL;
    NSString *_cssPath;
    NSString *_cssString;
    NSString *_preHTML;
    NSString *_postHTML;
    UIWebView *_webView;
    NSString *_contentHTML;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *contentHTML; // @synthesize contentHTML=_contentHTML;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
- (void)loadContentHTML;
- (void)initData;

@end

