//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSNumber, NSString, UIImageView, UILabel;
@protocol AnnotationDelegate;

@interface iPFTAnnotationView : UIView <UIGestureRecognizerDelegate>
{
    UIImageView *_imageAnnotation;
    NSNumber *_uniqueID;
    NSString *_details;
    id <AnnotationDelegate> _delegate;
    UILabel *_labelID;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *labelID; // @synthesize labelID=_labelID;
@property(nonatomic) id <AnnotationDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *details; // @synthesize details=_details;
@property(retain, nonatomic) NSNumber *uniqueID; // @synthesize uniqueID=_uniqueID;
@property(retain, nonatomic) UIImageView *imageAnnotation; // @synthesize imageAnnotation=_imageAnnotation;
- (void)panGestureDetected:(id)arg1;
- (void)tapGestureDetected:(id)arg1;
- (void)addGestureRecognizers;
- (void)initData;
- (id)initWithPosition:(struct CGPoint)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

