//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray, NSDictionary;
@protocol iPFTModuleDelegate;

@interface iPFTModule : UIViewController
{
    _Bool _sending;
    NSDictionary *_dictModuleData;
    id <iPFTModuleDelegate> _delegate;
    NSArray *_arraySubmitData;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *arraySubmitData; // @synthesize arraySubmitData=_arraySubmitData;
@property(nonatomic) id <iPFTModuleDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSDictionary *dictModuleData; // @synthesize dictModuleData=_dictModuleData;
- (void)loadModuleDataFromPlist;
- (void)send:(id)arg1;
- (id)init;

@end

