//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface iPFTPersistence : NSObject
{
}

+ (_Bool)getBlockShakeGesture;
+ (void)setBlockShakeGesture:(_Bool)arg1;
+ (_Bool)getOption:(id)arg1;
+ (void)setOption:(id)arg1 value:(_Bool)arg2;
+ (_Bool)hasAnnotationInfoBeenShown;
+ (void)setAnnotationInfoHasBeenShown;
+ (_Bool)hasInfoBeenShown;
+ (void)setInfoHasBeenShown;
+ (id)getSenderEmail;
+ (void)setSenderEmail:(id)arg1;
+ (id)getSenderName;
+ (void)setSenderName:(id)arg1;

@end

