//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Nbp/BasePlaybackStartupManager.h>

@class AVContentKeySession, ManagedPsshCoordinator, NSArray;
@protocol PlaybackLicenseStrategy;

@interface LicensedManifestPlaybackStartupManager : BasePlaybackStartupManager
{
    _Bool _licensedManifestFetchedLDL;
    AVContentKeySession *_avcks;
    NSArray *_licenseChallengeResponses;
    id <PlaybackLicenseStrategy> _playbackLicenseStrategy;
    ManagedPsshCoordinator *_psshCoordinator;
}

- (void).cxx_destruct;
@property(retain, nonatomic) ManagedPsshCoordinator *psshCoordinator; // @synthesize psshCoordinator=_psshCoordinator;
@property(nonatomic) _Bool licensedManifestFetchedLDL; // @synthesize licensedManifestFetchedLDL=_licensedManifestFetchedLDL;
@property(retain, nonatomic) id <PlaybackLicenseStrategy> playbackLicenseStrategy; // @synthesize playbackLicenseStrategy=_playbackLicenseStrategy;
@property(retain, nonatomic) NSArray *licenseChallengeResponses; // @synthesize licenseChallengeResponses=_licenseChallengeResponses;
@property(retain, nonatomic) AVContentKeySession *avcks; // @synthesize avcks=_avcks;
- (void)didDeliverLicenseChallengeResponses:(id)arg1 wasAdHoc:(_Bool)arg2;
- (id)didReceiveLicenseChallengeResponses:(id)arg1 inputError:(id)arg2;
- (_Bool)hasLicenseExpired;
- (void)closePlaybackStartupManager;
- (void)playbackInitiateRequested;
- (void)playbackStartRequested;
- (void)setupWithMovieDetails:(id)arg1 asset:(id)arg2;
- (void)setupContentKeySession;
- (id)initWithConfig:(id)arg1 licenseCoordinator:(id)arg2 dispatchQueue:(id)arg3 delegate:(id)arg4;

@end

