//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString;
@protocol NSObject;

@interface LicenseChallenge : NSObject
{
    _Bool _upgradeRequest;
    id <NSObject> _contentKeySessionRequestReference;
    id <NSObject> _keyLoaderDelegateRequestReference;
    NSData *_requestChallengeData;
    NSString *_optionalDeviceHeaderBytesString;
    NSString *_trackName;
    unsigned long long _challengeVersion;
    NSString *_uuidString;
    NSString *_originalLicenseUrl;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *originalLicenseUrl; // @synthesize originalLicenseUrl=_originalLicenseUrl;
@property(retain, nonatomic) NSString *uuidString; // @synthesize uuidString=_uuidString;
@property(nonatomic, getter=isUpgradeRequest) _Bool upgradeRequest; // @synthesize upgradeRequest=_upgradeRequest;
@property(nonatomic) unsigned long long challengeVersion; // @synthesize challengeVersion=_challengeVersion;
@property(retain, nonatomic) NSString *trackName; // @synthesize trackName=_trackName;
@property(retain, nonatomic) NSString *optionalDeviceHeaderBytesString; // @synthesize optionalDeviceHeaderBytesString=_optionalDeviceHeaderBytesString;
@property(retain, nonatomic) NSData *requestChallengeData; // @synthesize requestChallengeData=_requestChallengeData;
@property(retain, nonatomic) id <NSObject> keyLoaderDelegateRequestReference; // @synthesize keyLoaderDelegateRequestReference=_keyLoaderDelegateRequestReference;
@property(retain, nonatomic) id <NSObject> contentKeySessionRequestReference; // @synthesize contentKeySessionRequestReference=_contentKeySessionRequestReference;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToLicenseChallenge:(id)arg1;
- (_Bool)isOfflineChallenge;
- (id)init;

@end

