//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NFPlaylistGeneration/HLSSegmentEnumeratorProtocol-Protocol.h>
#import <NFPlaylistGeneration/SidxInfoProtocol-Protocol.h>

@class NSString;

@interface LinearSidxInfo : NSObject <SidxInfoProtocol, HLSSegmentEnumeratorProtocol>
{
    _Bool _isMcClearenStream;
    _Bool _McClearenStreamMarkerAdded;
    unsigned short _referenceCount;
    unsigned short _sidxInfoEntryCount;
    unsigned short _hlsSegmentEntryCount;
    unsigned int _timescale;
    unsigned int _maxSubsegmentDuration;
    unsigned int _accumulatedSegmentDuration;
    unsigned int _accumulatedSegmentSize;
    unsigned int _preferredTargetDuration;
    unsigned int _preferredTargetDurationOnTimecale;
    unsigned long long _firstMoofOffset;
    unsigned long long _accumulatedDuration;
    long long _mediaType;
    struct hlsSegmentEntry *_segmentEntries;
}

@property(nonatomic) struct hlsSegmentEntry *segmentEntries; // @synthesize segmentEntries=_segmentEntries;
@property(nonatomic) long long mediaType; // @synthesize mediaType=_mediaType;
@property(nonatomic) unsigned long long accumulatedDuration; // @synthesize accumulatedDuration=_accumulatedDuration;
@property(nonatomic) unsigned long long firstMoofOffset; // @synthesize firstMoofOffset=_firstMoofOffset;
@property(nonatomic) unsigned int preferredTargetDurationOnTimecale; // @synthesize preferredTargetDurationOnTimecale=_preferredTargetDurationOnTimecale;
@property(nonatomic) unsigned int preferredTargetDuration; // @synthesize preferredTargetDuration=_preferredTargetDuration;
@property(nonatomic) unsigned int accumulatedSegmentSize; // @synthesize accumulatedSegmentSize=_accumulatedSegmentSize;
@property(nonatomic) unsigned int accumulatedSegmentDuration; // @synthesize accumulatedSegmentDuration=_accumulatedSegmentDuration;
@property(nonatomic) unsigned int maxSubsegmentDuration; // @synthesize maxSubsegmentDuration=_maxSubsegmentDuration;
@property(nonatomic) unsigned short hlsSegmentEntryCount; // @synthesize hlsSegmentEntryCount=_hlsSegmentEntryCount;
@property(nonatomic) unsigned short sidxInfoEntryCount; // @synthesize sidxInfoEntryCount=_sidxInfoEntryCount;
@property(nonatomic) unsigned short referenceCount; // @synthesize referenceCount=_referenceCount;
@property(nonatomic) _Bool McClearenStreamMarkerAdded; // @synthesize McClearenStreamMarkerAdded=_McClearenStreamMarkerAdded;
@property(nonatomic) _Bool isMcClearenStream; // @synthesize isMcClearenStream=_isMcClearenStream;
@property(nonatomic) unsigned int timescale; // @synthesize timescale=_timescale;
- (id)segmentEnumerator;
- (double)maxSegmentDuration;
- (double)maxIFrameSegmentDuration;
- (double)duration;
- (_Bool)useProxy;
- (void)enumerateHLSSegmentForVideoOption:(id)arg1 isIFrame:(_Bool)arg2 withBlock:(CDUnknownBlockType)arg3;
- (void)addSidxEntryWithReferencedSize:(unsigned int)arg1 subsegmentDuration:(unsigned int)arg2 ssixEntryMoofAndIFrameSize:(unsigned int)arg3;
- (void)onAllSidxEntriesAdded;
- (_Bool)shouldStartANewHLSSegmentForSegmentDuration:(unsigned int)arg1;
- (void)dealloc;
- (id)initWithFirstMoofOffset:(unsigned long long)arg1 timescale:(unsigned int)arg2 reference_count:(unsigned short)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

