//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString;

@interface LivePlaybackSegmentTracker : NSObject
{
    _Bool _lastSegmentProduced;
    _Bool _discontinued;
    NSString *_playbackId;
    NSString *_mediaType;
    NSDate *_firstSegmentProductionTime;
    NSDate *_initialSegmentProductionTime;
    long long _targetLatencySegmentNumber;
    double _targetLatency;
    long long _initialSegmentNumber;
    long long _firstSegmentNumber;
    long long _lastSegmentNumber;
    double _firstSegmentDuration;
    double _playbackTimeSeconds;
    long long _bufferDuration;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool discontinued; // @synthesize discontinued=_discontinued;
@property(nonatomic) _Bool lastSegmentProduced; // @synthesize lastSegmentProduced=_lastSegmentProduced;
@property(nonatomic) long long bufferDuration; // @synthesize bufferDuration=_bufferDuration;
@property(nonatomic) double playbackTimeSeconds; // @synthesize playbackTimeSeconds=_playbackTimeSeconds;
@property(nonatomic) double firstSegmentDuration; // @synthesize firstSegmentDuration=_firstSegmentDuration;
@property(nonatomic) long long lastSegmentNumber; // @synthesize lastSegmentNumber=_lastSegmentNumber;
@property(nonatomic) long long firstSegmentNumber; // @synthesize firstSegmentNumber=_firstSegmentNumber;
@property(nonatomic) long long initialSegmentNumber; // @synthesize initialSegmentNumber=_initialSegmentNumber;
@property(nonatomic) double targetLatency; // @synthesize targetLatency=_targetLatency;
@property(nonatomic) long long targetLatencySegmentNumber; // @synthesize targetLatencySegmentNumber=_targetLatencySegmentNumber;
@property(retain, nonatomic) NSDate *initialSegmentProductionTime; // @synthesize initialSegmentProductionTime=_initialSegmentProductionTime;
@property(retain, nonatomic) NSDate *firstSegmentProductionTime; // @synthesize firstSegmentProductionTime=_firstSegmentProductionTime;
@property(retain, nonatomic) NSString *mediaType; // @synthesize mediaType=_mediaType;
@property(retain, nonatomic) NSString *playbackId; // @synthesize playbackId=_playbackId;
- (double)playbackTime;
- (void)updatePlaybackTime:(double)arg1;
- (void)produceSubtitleNextSegments:(id)arg1;
- (double)segmentDurationFromSubtitleLineEntry:(id)arg1;
- (void)produceNextSegments:(id)arg1;
- (void)setTargetDuration:(long long)arg1;
- (_Bool)isLastSegmentProduced;
- (_Bool)isDiscontinued;
- (_Bool)isNextSegmentAvailable;
- (_Bool)isPlaylistStarted;
- (long long)getLastSegmentNumber;
- (long long)getFirstSegmentNumber;
- (long long)getInitialSegmentNumber;
- (id)initWithPlaybackId:(id)arg1 withMediaType:(id)arg2 andBufferDuration:(long long)arg3;

@end

