//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "NFUIRenderTimerDelegateProtocol-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class LolomoListViewModel, NFUIRenderTimer, NSString, NSUUID, UICollectionView, UICollectionViewFlowLayout;
@protocol LolomoViewDelegate><LolomoActionDelegate;

@interface LolomoAbstractEntityRowCell : UICollectionViewCell <UICollectionViewDelegate, UICollectionViewDataSource, NFUIRenderTimerDelegateProtocol>
{
    _Bool _isForReuse;
    _Bool _paginationEnabled;
    _Bool _paginating;
    _Bool _rtlRotationFix;
    id <LolomoViewDelegate><LolomoActionDelegate> _lolomoViewDelegate;
    UICollectionView *_collectionView;
    UICollectionViewFlowLayout *_collectionViewLayout;
    LolomoListViewModel *_viewModel;
    NFUIRenderTimer *_renderTimer;
    NSUUID *_paginationUUID;
    double _lastOffset;
    double _currentVelocity;
    double _previousWidth;
}

- (void).cxx_destruct;
@property(nonatomic) double previousWidth; // @synthesize previousWidth=_previousWidth;
@property(nonatomic) _Bool rtlRotationFix; // @synthesize rtlRotationFix=_rtlRotationFix;
@property(nonatomic) double currentVelocity; // @synthesize currentVelocity=_currentVelocity;
@property(nonatomic) double lastOffset; // @synthesize lastOffset=_lastOffset;
@property(retain, nonatomic) NSUUID *paginationUUID; // @synthesize paginationUUID=_paginationUUID;
@property(nonatomic) _Bool paginating; // @synthesize paginating=_paginating;
@property(nonatomic) _Bool paginationEnabled; // @synthesize paginationEnabled=_paginationEnabled;
@property(nonatomic) __weak NFUIRenderTimer *renderTimer; // @synthesize renderTimer=_renderTimer;
@property(nonatomic) __weak LolomoListViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak UICollectionViewFlowLayout *collectionViewLayout; // @synthesize collectionViewLayout=_collectionViewLayout;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) __weak id <LolomoViewDelegate><LolomoActionDelegate> lolomoViewDelegate; // @synthesize lolomoViewDelegate=_lolomoViewDelegate;
@property(readonly, nonatomic) _Bool isForReuse; // @synthesize isForReuse=_isForReuse;
- (void)_insertIndexPahtsWithoutAnimation:(id)arg1;
- (void)_updateContentOffsetIfNeeded;
- (void)prepareForReuse;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;
- (unsigned long long)definitiveItemCount;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)callPaginationOnDelegate:(long long)arg1;
- (void)checkPaginationStatus:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)rowCellDidEndDisplaying;
- (void)rowCellWillDisplay;
- (void)configureWithViewModel:(id)arg1;
- (void)layoutSubviews;
- (void)willInitializeWithViewModel:(id)arg1;
- (id)itemCellAtIndexPath:(id)arg1;
- (id)newCollectionFlowLayout;
- (void)viewInitialized:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

