//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LolomoAbstractEntityItemCell.h"

#import "LolomoItemCell-Protocol.h"
#import "NFUICellFactoryItemProtocol-Protocol.h"
#import "NFUIRenderTimerDelegateProtocol-Protocol.h"
#import "NFUIReusableViewProtocol-Protocol.h"

@class LolomoListItemViewModel, LolomoListViewModel, NFUIGradientView, NFUILabel, NFUIRenderTimer, NSString, PlayButton, SimpleProgressBarView, UIButton, UICollectionView, UIImageView, UILabel, UITapGestureRecognizer, UIView, UIViewController;
@protocol LolomoViewDelegate><LolomoActionDelegate;

@interface LolomoContinueWatchingItemCell : LolomoAbstractEntityItemCell <LolomoItemCell, NFUIRenderTimerDelegateProtocol, NFUICellFactoryItemProtocol, NFUIReusableViewProtocol>
{
    _Bool _isLayoutPass;
    _Bool hasInlineVideo;
    _Bool _shouldBlockDetailsAction;
    UICollectionView *delegateCollectionView;
    UIViewController *delegateViewController;
    LolomoListViewModel *delegateListViewModel;
    id delegate;
    UIImageView *_displayArtImageView;
    UILabel *_titleLabel;
    NFUILabel *_subtitleCWLabel;
    NFUIGradientView *_gradientView;
    UIButton *_rightButton;
    UIButton *_leftButton;
    UIButton *_inScreenInfobutton;
    SimpleProgressBarView *_progressBar;
    PlayButton *_playButton;
    UIImageView *_familiarityPlayButton;
    UITapGestureRecognizer *_familiarityPlayGesture;
    UIView *_imageContainer;
    UIView *_bottomContainer;
}

+ (id)viewModelForListModel:(id)arg1 withIndexPath:(id)arg2;
+ (id)dequeueForItemAtIndexPath:(id)arg1 inCollectionView:(id)arg2 withLolomoViewDelegate:(id)arg3;
+ (void)registerInCollectionView:(id)arg1 withLolomoViewDelegate:(id)arg2;
+ (void)load;
+ (id)reuseIdentifier;
+ (_Bool)shouldReturnClassForType:(id)arg1 withModel:(id)arg2;
- (void).cxx_destruct;
@property(nonatomic) __weak UIView *bottomContainer; // @synthesize bottomContainer=_bottomContainer;
@property(nonatomic) __weak UIView *imageContainer; // @synthesize imageContainer=_imageContainer;
@property(retain, nonatomic) UITapGestureRecognizer *familiarityPlayGesture; // @synthesize familiarityPlayGesture=_familiarityPlayGesture;
@property(retain, nonatomic) UIImageView *familiarityPlayButton; // @synthesize familiarityPlayButton=_familiarityPlayButton;
@property(nonatomic) __weak PlayButton *playButton; // @synthesize playButton=_playButton;
@property(nonatomic) __weak SimpleProgressBarView *progressBar; // @synthesize progressBar=_progressBar;
@property(nonatomic) __weak UIButton *inScreenInfobutton; // @synthesize inScreenInfobutton=_inScreenInfobutton;
@property(nonatomic) __weak UIButton *leftButton; // @synthesize leftButton=_leftButton;
@property(nonatomic) __weak UIButton *rightButton; // @synthesize rightButton=_rightButton;
@property(nonatomic) __weak NFUIGradientView *gradientView; // @synthesize gradientView=_gradientView;
@property(nonatomic) __weak NFUILabel *subtitleCWLabel; // @synthesize subtitleCWLabel=_subtitleCWLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIImageView *displayArtImageView; // @synthesize displayArtImageView=_displayArtImageView;
@property(nonatomic) _Bool shouldBlockDetailsAction; // @synthesize shouldBlockDetailsAction=_shouldBlockDetailsAction;
@property(nonatomic) _Bool hasInlineVideo; // @synthesize hasInlineVideo;
@property(nonatomic) _Bool isLayoutPass; // @synthesize isLayoutPass=_isLayoutPass;
@property(nonatomic) __weak id delegate; // @synthesize delegate;
@property(nonatomic) __weak LolomoListViewModel *delegateListViewModel; // @synthesize delegateListViewModel;
@property(nonatomic) __weak UIViewController *delegateViewController; // @synthesize delegateViewController;
@property(nonatomic) __weak UICollectionView *delegateCollectionView; // @synthesize delegateCollectionView;
- (id)cellViewModel;
- (void)moreMenuPressed:(id)arg1;
- (void)infoButtonPressed:(id)arg1;
- (void)playButtonPressed:(id)arg1;
- (void)playButtonTapped:(id)arg1;
- (void)prepareForReuse;
- (void)itemCellDidEndDisplaying;
- (void)setHighlighted:(_Bool)arg1;
- (void)applyInScreenButtonMask;
- (void)setupDisplayArtImageView;
- (void)resetDisplayArtWithUrl:(id)arg1;
- (void)renewBookmark;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)layoutLabelAndGradientView;
- (void)congifureSubtitleUsingViewModel:(id)arg1;
- (id)a11yTitleForViewModel:(id)arg1;
- (void)reloadImageFromViewModel;
- (void)configureWithViewModel:(id)arg1;
- (void)adjustForCurrentLayoutDirection;
- (void)willInitializeWithViewModel:(id)arg1;
- (void)viewInitialized:(_Bool)arg1;
- (struct CGSize)calculatedSize:(struct CGSize)arg1 withModel:(id)arg2 withCollectionView:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isForReuse;
@property(nonatomic) __weak id <LolomoViewDelegate><LolomoActionDelegate> lolomoViewDelegate;
@property(nonatomic) __weak NFUIRenderTimer *renderTimer;
@property(nonatomic) _Bool shouldSkipViewModelCreationWhenSizing;
@property(readonly) Class superclass;
@property(readonly, nonatomic) __weak LolomoListItemViewModel *viewModel;

@end

