//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LolomoAbstractEntityItemCell.h"

#import "LolomoItemCell-Protocol.h"
#import "NFUICellFactoryItemProtocol-Protocol.h"
#import "NFUIRenderTimerDelegateProtocol-Protocol.h"
#import "NFUIReusableViewProtocol-Protocol.h"

@class LolomoListItemViewModel, LolomoListViewModel, NFUIRenderTimer, NFUITitleTreatmentView, NSLayoutConstraint, NSString, UICollectionView, UIImageView, UIViewController;
@protocol LolomoViewDelegate><LolomoActionDelegate;

@interface LolomoRoarItemCell : LolomoAbstractEntityItemCell <LolomoItemCell, NFUIRenderTimerDelegateProtocol, NFUICellFactoryItemProtocol, NFUIReusableViewProtocol>
{
    _Bool _isLayoutPass;
    _Bool hasInlineVideo;
    UICollectionView *delegateCollectionView;
    UIViewController *delegateViewController;
    LolomoListViewModel *delegateListViewModel;
    id delegate;
    UIImageView *_imageView;
    NFUITitleTreatmentView *_titleTreatmentView;
    NSLayoutConstraint *_titleTreatmentBottomConstraint;
}

+ (id)viewModelForListModel:(id)arg1 withIndexPath:(id)arg2;
+ (id)dequeueForItemAtIndexPath:(id)arg1 inCollectionView:(id)arg2 withLolomoViewDelegate:(id)arg3;
+ (void)registerInCollectionView:(id)arg1 withLolomoViewDelegate:(id)arg2;
+ (id)reuseIdentifier;
+ (_Bool)shouldReturnClassForType:(id)arg1 withModel:(id)arg2;
+ (void)load;
- (void).cxx_destruct;
@property(nonatomic) __weak NSLayoutConstraint *titleTreatmentBottomConstraint; // @synthesize titleTreatmentBottomConstraint=_titleTreatmentBottomConstraint;
@property(nonatomic) __weak NFUITitleTreatmentView *titleTreatmentView; // @synthesize titleTreatmentView=_titleTreatmentView;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) _Bool hasInlineVideo; // @synthesize hasInlineVideo;
@property(nonatomic) _Bool isLayoutPass; // @synthesize isLayoutPass=_isLayoutPass;
@property(nonatomic) __weak id delegate; // @synthesize delegate;
@property(nonatomic) __weak LolomoListViewModel *delegateListViewModel; // @synthesize delegateListViewModel;
@property(nonatomic) __weak UIViewController *delegateViewController; // @synthesize delegateViewController;
@property(nonatomic) __weak UICollectionView *delegateCollectionView; // @synthesize delegateCollectionView;
- (void)prepareForReuse;
- (void)applyGradient;
- (void)setHighlighted:(_Bool)arg1;
- (void)reloadImageFromViewModel;
- (void)displayTallPanel:(id)arg1;
- (void)configureWithViewModel:(id)arg1;
- (void)viewInitialized:(_Bool)arg1;
- (struct CGSize)calculatedSize:(struct CGSize)arg1 withModel:(id)arg2 withCollectionView:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isForReuse;
@property(nonatomic) __weak id <LolomoViewDelegate><LolomoActionDelegate> lolomoViewDelegate;
@property(nonatomic) __weak NFUIRenderTimer *renderTimer;
@property(nonatomic) _Bool shouldBlockDetailsAction;
@property(nonatomic) _Bool shouldSkipViewModelCreationWhenSizing;
@property(readonly) Class superclass;
@property(readonly, nonatomic) __weak LolomoListItemViewModel *viewModel;

@end

