//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFPlaylistGeneration/LinearSidxInfo.h>

@class NSArray, NSDictionary, NSMutableDictionary;

@interface LoviSidxInfo : LinearSidxInfo
{
    unsigned short _POIsIdx;
    NSDictionary *_playbook;
    NSArray *_POIs;
    NSMutableDictionary *_POIToSegmentEntriyIdx;
    unsigned long long *_accumulatedOffsets;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long *accumulatedOffsets; // @synthesize accumulatedOffsets=_accumulatedOffsets;
@property(retain, nonatomic) NSMutableDictionary *POIToSegmentEntriyIdx; // @synthesize POIToSegmentEntriyIdx=_POIToSegmentEntriyIdx;
@property(retain, nonatomic) NSArray *POIs; // @synthesize POIs=_POIs;
@property(nonatomic) unsigned short POIsIdx; // @synthesize POIsIdx=_POIsIdx;
@property(retain, nonatomic) NSDictionary *playbook; // @synthesize playbook=_playbook;
- (_Bool)useProxy;
- (void)enumerateHLSSegmentForVideoOption:(id)arg1 isIFrame:(_Bool)arg2 withBlock:(CDUnknownBlockType)arg3;
- (double)duration;
- (void)onAllSidxEntriesAdded;
- (_Bool)shouldStartANewHLSSegmentForSegmentDuration:(unsigned int)arg1;
- (void)dealloc;
- (id)initWithFirstMoofOffset:(unsigned long long)arg1 timescale:(unsigned int)arg2 reference_count:(unsigned short)arg3;

@end

