//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NflxTimer;
@protocol OS_dispatch_queue;

@interface ManifestFetch : NSObject
{
    _Bool _mslFree;
    _Bool _isSupplemental;
    _Bool _fakeLicenseFetchFailure;
    long long _batchManifestCount;
    long long _batchManifestWaitTimeMs;
    NSObject<OS_dispatch_queue> *_manifestFetchDispatchQueue;
    NflxTimer *_manifestLaunchTimer;
    NSMutableArray *_batchManifestInfos;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool fakeLicenseFetchFailure; // @synthesize fakeLicenseFetchFailure=_fakeLicenseFetchFailure;
@property(nonatomic) _Bool isSupplemental; // @synthesize isSupplemental=_isSupplemental;
@property(nonatomic) _Bool mslFree; // @synthesize mslFree=_mslFree;
@property(retain, nonatomic) NSMutableArray *batchManifestInfos; // @synthesize batchManifestInfos=_batchManifestInfos;
@property(retain, nonatomic) NflxTimer *manifestLaunchTimer; // @synthesize manifestLaunchTimer=_manifestLaunchTimer;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *manifestFetchDispatchQueue; // @synthesize manifestFetchDispatchQueue=_manifestFetchDispatchQueue;
@property(nonatomic) long long batchManifestWaitTimeMs; // @synthesize batchManifestWaitTimeMs=_batchManifestWaitTimeMs;
@property(nonatomic) long long batchManifestCount; // @synthesize batchManifestCount=_batchManifestCount;
- (void)logMessage:(id)arg1 withPlaybackIdsFromBatchManifestInfo:(id)arg2;
- (void)dumpBatchManifestResults:(id)arg1 forArguments:(id)arg2 andBatchManifestInfo:(id)arg3;
- (void)_sendManifestRequestEndForBatchManifestInfo:(id)arg1;
- (void)_sendManifestRequestStartForBatchManifestInfo:(id)arg1;
- (void)retrieveManifestWithInfos:(id)arg1;
- (void)launchManifestRequest;
- (void)addManifestInfoForBatchRequest:(id)arg1 andLaunchRequestImmediately:(_Bool)arg2;
- (void)setMaxAllowedBatchManifestCount:(long long)arg1 batchManifestWaitTimeMs:(long long)arg2;
- (id)initWithIsSupplemental:(_Bool)arg1;

@end

