//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class APIState, ManifestRequestArguments, NSDictionary, NSError, NSString;
@protocol PlatformConfigProvider, StartPlayEventReporterDelegate;

@interface ManifestInfo : NSObject
{
    NSString *_playbackId;
    id <PlatformConfigProvider> _playbackConfig;
    APIState *_stateData;
    ManifestRequestArguments *_arguments;
    CDUnknownBlockType _manifestReadyCompletionBlock;
    id <StartPlayEventReporterDelegate> _startPlayEventReporterDelegate;
    NSDictionary *_manifestDict;
    NSError *_error;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSDictionary *manifestDict; // @synthesize manifestDict=_manifestDict;
@property(nonatomic) __weak id <StartPlayEventReporterDelegate> startPlayEventReporterDelegate; // @synthesize startPlayEventReporterDelegate=_startPlayEventReporterDelegate;
@property(copy, nonatomic) CDUnknownBlockType manifestReadyCompletionBlock; // @synthesize manifestReadyCompletionBlock=_manifestReadyCompletionBlock;
@property(retain, nonatomic) ManifestRequestArguments *arguments; // @synthesize arguments=_arguments;
@property(retain, nonatomic) APIState *stateData; // @synthesize stateData=_stateData;
@property(retain, nonatomic) id <PlatformConfigProvider> playbackConfig; // @synthesize playbackConfig=_playbackConfig;
@property(retain, nonatomic) NSString *playbackId; // @synthesize playbackId=_playbackId;
- (id)initWithPlaybackId:(id)arg1;

@end

