//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, NflxMovieDetails, PlaylistParameter;
@protocol _TtP16NFManifestCommon10NFManifest_;

@interface MasterPlaylist : NSObject
{
    _Bool _masterPlaylistCreated;
    NSString *_playbackId;
    PlaylistParameter *_playlistParameter;
    id <_TtP16NFManifestCommon10NFManifest_> _manifestAccess;
    long long _errorCode;
    NflxMovieDetails *_movieDetails;
    NSMutableDictionary *_subtitleGroupDict;
    NSMutableDictionary *_audioGroupDict;
    NSMutableDictionary *_videoGroupDict;
    NSMutableArray *_orderedSubtitleGroupIds;
    NSMutableArray *_orderedAudioGroupIds;
    NSArray *_orderedVideoGroupIds;
    NSMutableDictionary *_audioGroupIdArrayDictByCdnIndex;
    NSMutableDictionary *_subtitleGroupIdDictByCdnIndex;
    NSDictionary *_livePlaybackSegmentTrackers;
}

+ (int)minimumBitrateForCodecPrefix:(id)arg1 fromGroupToLanguageMap:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *livePlaybackSegmentTrackers; // @synthesize livePlaybackSegmentTrackers=_livePlaybackSegmentTrackers;
@property(nonatomic) _Bool masterPlaylistCreated; // @synthesize masterPlaylistCreated=_masterPlaylistCreated;
@property(retain, nonatomic) NSMutableDictionary *subtitleGroupIdDictByCdnIndex; // @synthesize subtitleGroupIdDictByCdnIndex=_subtitleGroupIdDictByCdnIndex;
@property(retain, nonatomic) NSMutableDictionary *audioGroupIdArrayDictByCdnIndex; // @synthesize audioGroupIdArrayDictByCdnIndex=_audioGroupIdArrayDictByCdnIndex;
@property(retain, nonatomic) NSArray *orderedVideoGroupIds; // @synthesize orderedVideoGroupIds=_orderedVideoGroupIds;
@property(retain, nonatomic) NSMutableArray *orderedAudioGroupIds; // @synthesize orderedAudioGroupIds=_orderedAudioGroupIds;
@property(retain, nonatomic) NSMutableArray *orderedSubtitleGroupIds; // @synthesize orderedSubtitleGroupIds=_orderedSubtitleGroupIds;
@property(retain, nonatomic) NSMutableDictionary *videoGroupDict; // @synthesize videoGroupDict=_videoGroupDict;
@property(retain, nonatomic) NSMutableDictionary *audioGroupDict; // @synthesize audioGroupDict=_audioGroupDict;
@property(retain, nonatomic) NSMutableDictionary *subtitleGroupDict; // @synthesize subtitleGroupDict=_subtitleGroupDict;
@property(retain, nonatomic) NflxMovieDetails *movieDetails; // @synthesize movieDetails=_movieDetails;
@property(nonatomic) long long errorCode; // @synthesize errorCode=_errorCode;
@property(retain, nonatomic) id <_TtP16NFManifestCommon10NFManifest_> manifestAccess; // @synthesize manifestAccess=_manifestAccess;
@property(retain, nonatomic) PlaylistParameter *playlistParameter; // @synthesize playlistParameter=_playlistParameter;
@property(retain, nonatomic) NSString *playbackId; // @synthesize playbackId=_playbackId;
- (void)selectFirstBitrateStream_considering_feasibility;
- (void)recordFirstFeasibleVideoGroup:(id)arg1;
- (void)selectFirstBitrateStream;
- (void)createVideoStreamsAndRenditions;
- (_Bool)shouldSkipVideoStream:(id)arg1;
- (_Bool)shouldSkipVideoGroup:(id)arg1;
- (void)fillMissingLanguageInAacGroups:(id)arg1;
- (void)fillMissingLanguageFromAacGroups:(id)arg1 groupToLanguages:(id)arg2 refLanguages:(id)arg3;
- (void)fillMissingLanguageForGroups:(id)arg1 forCodecRanking:(id)arg2 groupToLanguages:(id)arg3 refLanguages:(id)arg4;
- (id)findGroupIdsWithMissingLanguage:(id)arg1 forCodec:(id)arg2 refLanguages:(id)arg3;
- (void)fillMissingLanguageForAudioGroup:(id)arg1;
- (void)createAudioGroups;
- (void)validateAudioGroupLanguages:(id)arg1 referenceAacAudioGroup:(id)arg2;
- (id)oneAtmosGroupIdFromGroupToLanguageMap:(id)arg1;
- (int)preferredAACBitrateFromGroupToLanguageMap:(id)arg1;
- (id)firstAACGroupIdFromGroupToLanguageMap:(id)arg1;
- (_Bool)wantAudioTrackType:(long long)arg1;
- (_Bool)shouldSkipAudioStream:(id)arg1;
- (_Bool)shouldSkipAudio:(id)arg1 firstAudioCodec:(id)arg2;
- (void)createSubtitleGroups:(_Bool)arg1;
- (_Bool)processImageBasedSubtitle;
- (id)findPlaylistGroupEntry:(id)arg1;
- (void)playlistStringForAllVideoStreams:(id)arg1;
- (void)playlistStringForRemainingVideoStreams:(id)arg1;
- (void)playlistStringForFirstVideoStreams:(id)arg1;
- (void)playlistStringForVideoGroups:(id)arg1;
- (void)playlistStringForAudioGroups:(id)arg1;
- (void)playlistStringForSubtitleGroups:(id)arg1;
- (void)playlistStringHeaderSection:(id)arg1;
- (void)updatePlaybackTime:(double)arg1;
- (id)buildVariantPlaylist:(id)arg1 playlistKey:(id)arg2 movieHeaderDownloader:(id)arg3;
- (id)getLivePlaybackSegmentTrackerForMediaType:(id)arg1;
- (void)generatePlaylistString;
- (void)createMasterPlaylist;
- (void)dealloc;
- (id)initWithPlaybackId:(id)arg1 parameter:(id)arg2 manifestAccess:(id)arg3 nflxMovieDetails:(id)arg4;
- (void)recordVideoGroup:(id)arg1 pairedWithAudioGroup:(id)arg2;

@end

