//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NFPlaylistGeneration/HlsPlaylistEntity-Protocol.h>

@class MasterPlaylist, NSArray, NSMutableArray, NSNumber, NSString, PlaylistParameter;
@protocol _TtP16NFManifestCommon13NFVideoStream_;

@interface MasterPlaylistVideoStream : NSObject <HlsPlaylistEntity>
{
    _Bool _isHEVC;
    _Bool _isEncrypted;
    NSArray *_playlistKeys;
    NSArray *_iframePlaylistKeys;
    id <_TtP16NFManifestCommon13NFVideoStream_> _stream;
    MasterPlaylist *_masterPlaylist;
    PlaylistParameter *_playlistParameter;
    NSString *_cdnId;
    unsigned long long _cdnIndex;
    NSNumber *_bps;
    NSString *_groupId;
    NSMutableArray *_audioGroupIdArray;
    NSString *_subtitleGroupId;
    long long _defaultIdx;
    NSArray *_urls;
    NSArray *_iframeUrls;
    NSString *_videoGroupId;
    NSString *_iframeVideoGroupId;
}

+ (long long)channelCountForAudioGroupId:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *iframeVideoGroupId; // @synthesize iframeVideoGroupId=_iframeVideoGroupId;
@property(retain, nonatomic) NSString *videoGroupId; // @synthesize videoGroupId=_videoGroupId;
@property(retain, nonatomic) NSArray *iframeUrls; // @synthesize iframeUrls=_iframeUrls;
@property(retain, nonatomic) NSArray *urls; // @synthesize urls=_urls;
@property(nonatomic) long long defaultIdx; // @synthesize defaultIdx=_defaultIdx;
@property(nonatomic) _Bool isEncrypted; // @synthesize isEncrypted=_isEncrypted;
@property(retain, nonatomic) NSString *subtitleGroupId; // @synthesize subtitleGroupId=_subtitleGroupId;
@property(retain, nonatomic) NSMutableArray *audioGroupIdArray; // @synthesize audioGroupIdArray=_audioGroupIdArray;
@property(retain, nonatomic) NSString *groupId; // @synthesize groupId=_groupId;
@property(retain, nonatomic) NSNumber *bps; // @synthesize bps=_bps;
@property(nonatomic) unsigned long long cdnIndex; // @synthesize cdnIndex=_cdnIndex;
@property(retain, nonatomic) NSString *cdnId; // @synthesize cdnId=_cdnId;
@property(retain, nonatomic) PlaylistParameter *playlistParameter; // @synthesize playlistParameter=_playlistParameter;
@property(nonatomic) __weak MasterPlaylist *masterPlaylist; // @synthesize masterPlaylist=_masterPlaylist;
@property(retain, nonatomic) id <_TtP16NFManifestCommon13NFVideoStream_> stream; // @synthesize stream=_stream;
@property(nonatomic) _Bool isHEVC; // @synthesize isHEVC=_isHEVC;
@property(retain, nonatomic) NSArray *iframePlaylistKeys; // @synthesize iframePlaylistKeys=_iframePlaylistKeys;
@property(retain, nonatomic) NSArray *playlistKeys; // @synthesize playlistKeys=_playlistKeys;
- (_Bool)shouldPairWithAudioGroupId:(id)arg1;
- (void)generatePlaylistString:(id)arg1 audioGroupId:(id)arg2 subtitleGroupId:(id)arg3;
- (int)hlsVariantScoreWithAudioGroupId:(id)arg1;
- (_Bool)useVideoRendition;
- (long long)minBitrateForAudioGroupId:(id)arg1;
- (void)generateIFramePlaylistString:(id)arg1;
- (id)generateLiveVariantPlaylist:(id)arg1 forPlaylistKey:(id)arg2;
- (id)generateVodVariantPlaylist:(id)arg1 forPlaylistKey:(id)arg2;
- (id)generateVariantPlaylist:(id)arg1 forPlaylistKey:(id)arg2;
- (void)generatePlaylistString:(id)arg1;
- (void)generatePlaylistStringForVideoRenditions:(id)arg1;
- (_Bool)takePartInFirstBitrateSelection;
- (int)determinePeakBandwidthFrom:(int)arg1 fallbackTo:(int)arg2;
- (id)codecString;
- (id)initWithManifest:(id)arg1 track:(id)arg2 stream:(id)arg3 audioGroupIdArray:(id)arg4 subtitleGroupId:(id)arg5 cdnId:(id)arg6 cdnIndex:(unsigned long long)arg7 group:(id)arg8;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

