//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Nbp/MdxDevice-Protocol.h>

@class NFCWDevice, NSString;

@interface MdxCastDevice : NSObject <MdxDevice>
{
    _Bool _canRemoteLogin;
    _Bool _isWaitingOnSignin;
    NFCWDevice *_nfcwDevice;
    NSString *_remoteLoginSessionId;
}

- (void).cxx_destruct;
@property(retain) NSString *remoteLoginSessionId; // @synthesize remoteLoginSessionId=_remoteLoginSessionId;
@property _Bool isWaitingOnSignin; // @synthesize isWaitingOnSignin=_isWaitingOnSignin;
@property _Bool canRemoteLogin; // @synthesize canRemoteLogin=_canRemoteLogin;
@property(retain, nonatomic) NFCWDevice *nfcwDevice; // @synthesize nfcwDevice=_nfcwDevice;
- (void)startSessionWithIntent:(long long)arg1 callback:(CDUnknownBlockType)arg2;
@property(readonly) NSString *targetType;
@property(readonly) NSString *url;
@property(readonly) NSString *mdxUuid;
@property(readonly) NSString *modelNumber;
@property(readonly) NSString *modelName;
@property(readonly) NSString *manufacturer;
@property(readonly) NSString *friendlyName;
@property(readonly) NSString *deviceId;
- (id)device;
@property(readonly) long long discoveryState;
- (id)initWithDevice:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

