//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSError;

@interface MdxLoginUIRequest : NSObject
{
    _Bool _pinRequired;
    long long _attemptNumber;
    NSError *_lastError;
}

- (void).cxx_destruct;
@property(retain) NSError *lastError; // @synthesize lastError=_lastError;
@property long long attemptNumber; // @synthesize attemptNumber=_attemptNumber;
@property _Bool pinRequired; // @synthesize pinRequired=_pinRequired;

@end

