//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSObject, NSString;
@protocol MdxTarget;

@protocol MdxTargetDelegate <NSObject>

@optional
- (void)propertyChanged:(NSObject<MdxTarget> *)arg1:(NSString *)arg2:(NSString *)arg3:(NSString *)arg4;
- (void)newAppMessage:(NSObject<MdxTarget> *)arg1:(NSString *)arg2:(id)arg3:(int)arg4;
- (void)appConnectionEnded:(NSObject<MdxTarget> *)arg1;
- (void)launchStateChanged:(NSObject<MdxTarget> *)arg1:(long long)arg2;
- (void)discoveryStateChanged:(NSObject<MdxTarget> *)arg1:(long long)arg2;
@end

