//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Nbp/NSObject-Protocol.h>

@class NSArray, NSDictionary, NSObject, NSString;
@protocol MdxMsgStreamBinding, MdxTargetDelegate, Promise;

@protocol MdxTarget <NSObject>
@property(readonly) NSString *mdxUuid;
@property(readonly) long long launchState;
@property(readonly) NSString *targetType;
@property(readonly) NSString *remoteLoginSessionId;
@property(readonly) _Bool isWaitingOnSignin;
@property(readonly) _Bool canRemoteLogin;
@property _Bool attemptedRemoteLogin;
@property(readonly) _Bool isAvailable;
@property(readonly) NSString *id;
@property(readonly) NSString *modelNumber;
@property(readonly) NSString *modelName;
@property(readonly) NSString *manufacturer;
@property(readonly) NSString *friendlyName;
@property(readonly) long long discoveryState;
@property(nonatomic) __weak id <MdxTargetDelegate> delegate;
- (NSObject<Promise> *)stop:(NSString *)arg1;
- (NSObject<Promise> *)stop:(NSString *)arg1:(NSDictionary *)arg2;
- (NSObject<Promise> *)skipIntro:(NSString *)arg1 source:(NSString *)arg2;
- (NSObject<Promise> *)skip:(NSString *)arg1:(int)arg2;
- (NSObject<Promise> *)skip:(NSString *)arg1:(int)arg2:(NSDictionary *)arg3;
- (NSObject<Promise> *)setVolume:(NSString *)arg1:(int)arg2;
- (NSObject<Promise> *)setVolume:(NSString *)arg1:(int)arg2:(NSDictionary *)arg3;
- (NSObject<Promise> *)setTime:(NSString *)arg1:(int)arg2;
- (NSObject<Promise> *)setTime:(NSString *)arg1:(int)arg2:(NSDictionary *)arg3;
- (NSObject<Promise> *)setAudioSubtitles:(NSString *)arg1:(NSString *)arg2;
- (NSObject<Promise> *)setAudioSubtitles:(NSString *)arg1:(NSString *)arg2:(NSDictionary *)arg3;
- (NSObject<Promise> *)sendAppMessage:(NSString *)arg1:(NSDictionary *)arg2;
- (NSObject<Promise> *)resume:(NSString *)arg1;
- (NSObject<Promise> *)resume:(NSString *)arg1:(NSDictionary *)arg2;
- (NSObject<Promise> *)play:(NSString *)arg1:(NSString *)arg2;
- (NSObject<Promise> *)play:(NSString *)arg1:(NSString *)arg2:(NSDictionary *)arg3;
- (NSObject<Promise> *)pause:(NSString *)arg1:(NSDictionary *)arg2;
- (NSObject<Promise> *)pause:(NSString *)arg1;
- (NSObject<Promise> *)getPlayerState:(NSDictionary *)arg1;
- (NSObject<Promise> *)getPlayerState;
- (NSObject<Promise> *)getCapabilities:(NSDictionary *)arg1;
- (NSObject<Promise> *)getCapabilities;
- (NSObject<Promise> *)getAudioSubtitles:(NSString *)arg1;
- (NSObject<Promise> *)getAudioSubtitles:(NSString *)arg1:(NSDictionary *)arg2;
- (NSObject<Promise> *)dismissPostPlay:(NSString *)arg1:(NSDictionary *)arg2;
- (NSObject<Promise> *)dismissPostPlay:(NSString *)arg1;
- (NSObject<Promise> *)disconnectFromApp:(_Bool)arg1;
- (NSObject<Promise> *)connectToApp:(long long)arg1;
- (NSObject<Promise> *)connectToApp:(long long)arg1:(NSString *)arg2;
- (NSObject<MdxMsgStreamBinding> *)bindMsgStream:(NSArray *)arg1:(int)arg2:(void (^)(NSString *, NSDictionary *, NSObject<MdxMsgStreamBinding> *))arg3:(void (^)(_Bool))arg4;
- (NSObject<Promise> *)autoAdvance:(NSString *)arg1:(int)arg2;
- (NSObject<Promise> *)autoAdvance:(NSString *)arg1:(int)arg2:(NSDictionary *)arg3;
@end

