//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MdxUiMenuStatusViewModel : NSObject
{
    NSString *_statusTitleText;
    NSString *_statusDescriptionText;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *statusDescriptionText; // @synthesize statusDescriptionText=_statusDescriptionText;
@property(readonly, copy, nonatomic) NSString *statusTitleText; // @synthesize statusTitleText=_statusTitleText;
- (id)initWithDictionary:(id)arg1;

@end

