//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSDictionary, NSString, NSURL;
@protocol MSLRequest, MSLTask;

@protocol MSLClient
- (void)backupMSLCredentialsFromId:(NSString *)arg1 toId:(NSString *)arg2;
- (void)updateMSLCredentialsFromId:(NSString *)arg1 toId:(NSString *)arg2;
- (id <MSLTask>)sendMslRequest:(id <MSLRequest>)arg1 callback:(void (^)(id <MSLRequest>, id <MSLResponse>))arg2;
- (id <MSLRequest>)requestWithURL:(NSURL *)arg1 headers:(NSDictionary *)arg2 credentials:(NSDictionary *)arg3 body:(id)arg4 timeout:(double)arg5;
- (id <MSLRequest>)requestWithURL:(NSURL *)arg1 headers:(NSDictionary *)arg2 GUID:(NSString *)arg3 body:(id)arg4 timeout:(double)arg5;
- (id <MSLRequest>)requestWithURL:(NSURL *)arg1 headers:(NSDictionary *)arg2 body:(id)arg3 timeout:(double)arg4;
@end

