//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MslContextHolder : NSObject
{
    shared_ptr_b1ca2fe9 _mslContext;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(nonatomic) shared_ptr_b1ca2fe9 mslContext; // @synthesize mslContext=_mslContext;
- (id)initWithMslContext:(shared_ptr_b1ca2fe9)arg1;

@end

