//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MslHttpRequestStream, MslHttpResponseStream, NSDictionary, NSError, NSHTTPURLResponse, NSMutableData, NSNumber, NSString, NSURL, NSURLRequest;
@protocol AppleURLSession;

@interface MslHttpTransaction : NSObject
{
    _Bool _didSendRequest;
    _Bool _didFinishBody;
    NSHTTPURLResponse *_response;
    NSError *_error;
    NSError *_errorWithResponseInfo;
    id <AppleURLSession> _session;
    NSURLRequest *_request;
    MslHttpRequestStream *_reqStream;
    MslHttpResponseStream *_respStream;
    NSMutableData *_reqBody;
    NSURL *_url;
    NSDictionary *_headers;
    NSString *_actionName;
    NSNumber *_taskIdentifier;
    NSMutableData *_badResponseData;
    NSDictionary *_options;
}

- (void).cxx_destruct;
@property(retain) NSDictionary *options; // @synthesize options=_options;
@property(retain) NSMutableData *badResponseData; // @synthesize badResponseData=_badResponseData;
@property(nonatomic) _Bool didFinishBody; // @synthesize didFinishBody=_didFinishBody;
@property(nonatomic) _Bool didSendRequest; // @synthesize didSendRequest=_didSendRequest;
@property(retain, nonatomic) NSNumber *taskIdentifier; // @synthesize taskIdentifier=_taskIdentifier;
@property(retain, nonatomic) NSString *actionName; // @synthesize actionName=_actionName;
@property(retain, nonatomic) NSDictionary *headers; // @synthesize headers=_headers;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) NSMutableData *reqBody; // @synthesize reqBody=_reqBody;
@property(retain, nonatomic) MslHttpResponseStream *respStream; // @synthesize respStream=_respStream;
@property(retain, nonatomic) MslHttpRequestStream *reqStream; // @synthesize reqStream=_reqStream;
@property(retain, nonatomic) NSURLRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) id <AppleURLSession> session; // @synthesize session=_session;
@property(retain) NSError *errorWithResponseInfo; // @synthesize errorWithResponseInfo=_errorWithResponseInfo;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSHTTPURLResponse *response; // @synthesize response=_response;
- (void)close;
- (_Bool)flush;
- (long long)read:(char *)arg1 length:(unsigned long long)arg2;
- (long long)write:(char *)arg1 length:(unsigned long long)arg2;
- (void)_sendWholeRequest;
- (void)_startStreamedRequest;
- (void)completeReceived:(id)arg1;
- (void)_maybeRecordBadStatusError;
- (void)dataReceived:(id)arg1;
- (void)responseReceived:(id)arg1;
- (id)_makeRequest:(id)arg1 headers:(id)arg2;
- (id)initWithURL:(id)arg1 headers:(id)arg2 session:(id)arg3 options:(id)arg4;
- (id)initWithURL:(id)arg1 headers:(id)arg2 session:(id)arg3;

@end

