//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MslLoginHijack : NSObject
{
}

+ (_Bool)shouldHijackCall:(id)arg1 nrmstart:(id)arg2;
+ (_Bool)_isSwitchProfileCall:(id)arg1;
+ (_Bool)_findMSLLoginAllocation:(id)arg1;
+ (_Bool)_nrmstart:(id)arg1 isInTest:(long long)arg2 cell:(long long)arg3;
- (id)executeWithParams:(id)arg1 endpoint:(id)arg2 nrmstart:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)_extractProfileIDFromParams:(id)arg1;
- (void)_findAccountOwnerInPayload:(id)arg1 userId:(id)arg2 updatingMslClient:(id)arg3;
- (void)_updateCookieStoreFromResponseHeaders:(id)arg1 url:(id)arg2 notifyApp:(_Bool)arg3;
- (void)_notifyAppOfCookieChanges:(id)arg1;
- (id)_requestBodyFromParams:(id)arg1;
- (id)_parseJSONString:(id)arg1;
- (id)_headersForLogin:(id)arg1 parameters:(id)arg2;
- (_Bool)_isInUserIdTokenLoginTest:(id)arg1;

@end

