//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSNumber, NSString;
@protocol NCLDataDelegate, NCLMetricDelegate, NCLUploadDelegate;

@interface NCLLogger : NSObject
{
    long long _MAX_BITS_COUNT;
    long long _INCREMENTING_BITS_COUNT;
    long long _RANDOM_BITS_COUNT;
    long long _INCREMENTING_BITS_MASK;
    long long _RANDOM_BITS_SHIFT;
    long long _lastIncrementingBits;
    NSDictionary *_CL_TYPES;
    long long _sequence;
    NSNumber *_logSessionId;
    NSString *_source;
    id <NCLUploadDelegate> _delegate;
    id <NCLMetricDelegate> _metricDelegate;
    id <NCLDataDelegate> _dataDelegate;
    NSNumber *_initialContextId;
}

+ (double)getClientTimeInMS;
+ (id)dispatchQueue;
+ (id)logger;
- (void).cxx_destruct;
@property(retain, nonatomic) NSNumber *initialContextId; // @synthesize initialContextId=_initialContextId;
@property(nonatomic) __weak id <NCLDataDelegate> dataDelegate; // @synthesize dataDelegate=_dataDelegate;
@property(nonatomic) __weak id <NCLMetricDelegate> metricDelegate; // @synthesize metricDelegate=_metricDelegate;
@property(nonatomic) __weak id <NCLUploadDelegate> delegate; // @synthesize delegate=_delegate;
- (void)sever;
- (id)serialize;
- (void)end;
- (void)start;
- (void)backgroundProcessFlushWithCompletion:(CDUnknownBlockType)arg1;
- (void)flushWithCompletion:(CDUnknownBlockType)arg1;
- (id)endSession:(id)arg1 withDataReturnPayload:(id)arg2;
- (id)endSession:(id)arg1 withData:(id)arg2;
- (id)endSession:(id)arg1;
- (id)startSession:(id)arg1;
- (id)startSession:(id)arg1 withData:(id)arg2;
- (id)logEvent:(id)arg1;
- (id)createDebugObjectWithData:(id)arg1;
- (id)logEvent:(id)arg1 withData:(id)arg2;
- (id)createEventContext:(id)arg1 withData:(id)arg2;
- (void)removeContext:(id)arg1;
- (id)addContext:(id)arg1;
- (id)addContext:(id)arg1 withData:(id)arg2;
- (id)getNextContextId;
- (void)configure:(id)arg1;
- (void)configureWithState:(id)arg1;
- (void)initState;
- (id)init;

@end

