//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "DataBrokerDataProviderProtocol-Protocol.h"
#import "DeepLinkControllerDelegateProtocol-Protocol.h"

@class NSString, NeroActivationController, NeroAppFlowController, NeroDownloadService, NeroHTTPManager, NeroNFUIStartupController, NeroPlaybackController, NeroUIApplication, RootViewController;
@protocol DataBrokerDataProviderProtocol;

@interface Nero : NSObject <DeepLinkControllerDelegateProtocol, DataBrokerDataProviderProtocol>
{
    id <DataBrokerDataProviderProtocol> _delegate;
    RootViewController *_rootViewController;
    NeroActivationController *_activationController;
    NeroAppFlowController *_appFlowController;
    NeroDownloadService *_downloadService;
    NeroHTTPManager *_httpManager;
    NeroPlaybackController *_playbackController;
    NeroNFUIStartupController *_startupController;
    NeroUIApplication *_uiApplication;
}

+ (id)deepLinkDelegate;
+ (void)setRootViewController:(id)arg1;
+ (id)rootViewController;
+ (id)nero;
- (void).cxx_destruct;
@property(retain, nonatomic) NeroUIApplication *uiApplication; // @synthesize uiApplication=_uiApplication;
@property(retain, nonatomic) NeroNFUIStartupController *startupController; // @synthesize startupController=_startupController;
@property(retain, nonatomic) NeroPlaybackController *playbackController; // @synthesize playbackController=_playbackController;
@property(retain, nonatomic) NeroHTTPManager *httpManager; // @synthesize httpManager=_httpManager;
@property(retain, nonatomic) NeroDownloadService *downloadService; // @synthesize downloadService=_downloadService;
@property(retain, nonatomic) NeroAppFlowController *appFlowController; // @synthesize appFlowController=_appFlowController;
@property(retain, nonatomic) NeroActivationController *activationController; // @synthesize activationController=_activationController;
@property(nonatomic) __weak RootViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(nonatomic) __weak id <DataBrokerDataProviderProtocol> delegate; // @synthesize delegate=_delegate;
- (id)objectContext;
- (void)deepLinkController:(id)arg1 handleAction:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

