//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationBar.h>

@class UILabel, UIView;

@interface NetflixNavigationBar : UINavigationBar
{
    UIView *_subheaderView;
    UIView *_backgroundView;
    double _percentVisible;
    UIView *_notificationBadge;
    UILabel *_notificationCountLabel;
    UIView *_goingAwaySubheader;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIView *goingAwaySubheader; // @synthesize goingAwaySubheader=_goingAwaySubheader;
@property(nonatomic) __weak UILabel *notificationCountLabel; // @synthesize notificationCountLabel=_notificationCountLabel;
@property(nonatomic) __weak UIView *notificationBadge; // @synthesize notificationBadge=_notificationBadge;
@property(nonatomic) double percentVisible; // @synthesize percentVisible=_percentVisible;
@property(nonatomic) __weak UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIView *subheaderView; // @synthesize subheaderView=_subheaderView;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)updateWithNotificationCount:(unsigned long long)arg1;
- (void)updateBadgePosition;
- (void)configureBadge;
- (void)layoutSubviews;
- (id)topItem;
- (void)logoTapped:(id)arg1;
- (void)_configureForItem_forPills:(id)arg1;
- (void)_configureForItem:(id)arg1;
- (void)configureForItem:(id)arg1;
- (id)popNavigationItemAnimated:(_Bool)arg1;
- (void)setItems:(id)arg1;
- (void)pushNavigationItem:(id)arg1 animated:(_Bool)arg2;
- (void)addSubheaderView:(id)arg1;
- (void)setSubheaderView:(id)arg1 withTransitionCoordinator:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

