//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NFNetworkState/_TtP14NFNetworkState22NFReachabilityObserver_-Protocol.h>

@class NSDictionary, NSString, Reachability, _TtC14NFNetworkState20ReachabilityProvider;

@interface NetflixReachability : NSObject <_TtP14NFNetworkState22NFReachabilityObserver_>
{
    unsigned long long _stateNetworkStatus;
    NSString *_configuredHostName;
    Reachability *_objcReachabilityObject;
    NSDictionary *_networkInfo;
    _TtC14NFNetworkState20ReachabilityProvider *_reachabilityProvider;
}

+ (id)defaultInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) _TtC14NFNetworkState20ReachabilityProvider *reachabilityProvider; // @synthesize reachabilityProvider=_reachabilityProvider;
@property(copy, nonatomic) NSDictionary *networkInfo; // @synthesize networkInfo=_networkInfo;
@property(retain, nonatomic) Reachability *objcReachabilityObject; // @synthesize objcReachabilityObject=_objcReachabilityObject;
@property(copy, nonatomic) NSString *configuredHostName; // @synthesize configuredHostName=_configuredHostName;
- (void)reachabilityProvider:(id)arg1 didDetectPathStatusChange:(id)arg2;
- (_Bool)temporaryAPI_isNetworkAvailable;
- (_Bool)temporaryAPI_isNetworkConstrained;
- (_Bool)temporaryAPI_isNetworkExpensive;
- (void)stopNotifier;
- (void)startNotifier;
- (void)handleReachabilityChanged:(id)arg1;
- (_Bool)isConnectedToMobileNetwork;
- (_Bool)isConnectedToWifiNetwork;
@property(readonly, nonatomic) unsigned long long stateNetworkStatus;
- (unsigned int)currentReachabilityFlags;
- (id)currentNetworkStatus;
- (void)setStateNetworkStatus:(unsigned long long)arg1;
- (void)postStateSpecificNotification:(unsigned long long)arg1;
- (void)notifyNotReachable;
- (void)notifyReachableViaWWAN;
- (void)notifyReachableViaWiFi;
- (id)initWithHostName:(id)arg1;
- (void)setUseUpdatedReachability:(_Bool)arg1;

@end

