//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NFBarButtonItemCoordinator : NSObject
{
    // Error parsing type: , name: navigationController
    // Error parsing type: , name: accountButton
}

- (void).cxx_destruct;
- (id)init;
- (void)handleSearchButtonActionFrom:(id)arg1;
- (void)searchTappedFrom:(id)arg1;
- (void)openProfileFrom:(id)arg1;
- (id)barButtonItems;
- (id)initWithNavigationController:(id)arg1;

@end

