//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "DataBrokerDataProviderProtocol-Protocol.h"

@class CSLog, DataBroker, PushNotificationHandler;

@interface NFLXAppSession : NSObject <DataBrokerDataProviderProtocol>
{
    CSLog *_clientLog;
    PushNotificationHandler *_pushNotificationHandler;
}

- (void).cxx_destruct;
@property(retain, nonatomic) PushNotificationHandler *pushNotificationHandler; // @synthesize pushNotificationHandler=_pushNotificationHandler;
@property(retain, nonatomic) CSLog *clientLog; // @synthesize clientLog=_clientLog;
- (id)objectContext;
@property(readonly, nonatomic) DataBroker *dataBroker;
- (id)initWithDataBroker:(id)arg1 clientLog:(id)arg2 pushNotificationHandler:(id)arg3;
- (id)initWithDataBroker:(id)arg1;

@end

