//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NFLXKeyedLiveObject.h"

@class NSNumber, NSString;

@interface NFLXABLiveObject : NFLXKeyedLiveObject
{
    NSString *_testId;
    NSNumber *_cellNumber;
    NSNumber *_explicitAllocation;
}

+ (Class)safeObjectClass;
- (void).cxx_destruct;
@property(retain) NSNumber *explicitAllocation; // @synthesize explicitAllocation=_explicitAllocation;
@property(retain) NSNumber *cellNumber; // @synthesize cellNumber=_cellNumber;
@property(retain) NSString *testId; // @synthesize testId=_testId;

@end

