//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NFLXHTTPRequest : NSObject
{
}

+ (id)removeHeadersFromURLString:(id)arg1 storingInDictionary:(id)arg2;
+ (_Bool)urlStringContainsHeaders:(id)arg1;
+ (id)stringByRemovingExtraBracket:(id)arg1;
+ (id)requestWithMutableRequest:(id)arg1 method:(id)arg2 URLString:(id)arg3 parameters:(id)arg4 error:(id *)arg5;
+ (_Bool)testEqualWithUrlRequest:(id)arg1 with:(id)arg2 error:(id *)arg3;
+ (id)requestWithMethod:(id)arg1 URLString:(id)arg2 parameters:(id)arg3 error:(id *)arg4;

@end

