//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Nbp/NFURLSessionPinnedCertificateEvaluator-Protocol.h>

@class NSDictionary, NSString;

@interface NflxPinnedCertEvaluator : NSObject <NFURLSessionPinnedCertificateEvaluator>
{
    NSDictionary *_pinnedCerts;
}

- (void).cxx_destruct;
@property(retain) NSDictionary *pinnedCerts; // @synthesize pinnedCerts=_pinnedCerts;
- (_Bool)evaluatePinnedCertificate:(struct __SecTrust *)arg1 forHost:(id)arg2;
- (_Bool)hasPinnedCertForHost:(id)arg1;
- (id)init;
- (void)_initPinnedCerts;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

