//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Nbp/NFPlaygraphPlayer-Protocol.h>

@class PlaygraphSegmentItem;
@protocol NFPlaygraphPlayerDataSource, NFPlaygraphSegment, NFPlaygraphSegmentTransitionSelector;

@protocol NFPlaygraphPlayerInternal <NFPlaygraphPlayer>
@property(readonly, nonatomic) _Bool usePlaygraphTransitionImprovements;
@property(readonly, nonatomic) _Bool useDualBoundaryObservation;
@property(readonly, nonatomic) PlaygraphSegmentItem *previousSegmentItem;
@property(readonly, nonatomic) PlaygraphSegmentItem *currentSegmentItem;
@property(readonly, nonatomic) id <NFPlaygraphPlayerDataSource> dataSource;
@property(readonly, nonatomic) _Bool playbackCancelled;
@property(readonly, nonatomic) _Bool playbackClosed;
@property(readonly, nonatomic) _Bool playbackStarted;
- (void)playSegmentItem:(PlaygraphSegmentItem *)arg1 targetPosition:(double)arg2;
- (long long)playbackStartLeadTimeMS;
- (void)markAndSweepSegmentItemsNotReachableFromItem:(PlaygraphSegmentItem *)arg1 maxDepth:(unsigned long long)arg2;
- (void)cleanupItem:(PlaygraphSegmentItem *)arg1;
- (PlaygraphSegmentItem *)nextItemAfterItem:(PlaygraphSegmentItem *)arg1;
- (unsigned long long)numberOfPlayersOpen;
- (unsigned long long)numberOfSegmentItemsOpen;
- (unsigned long long)numberOfSegmentItemsBeingLoaded;
- (PlaygraphSegmentItem *)prepareItemForNextSegment:(id <NFPlaygraphSegment>)arg1 afterItem:(PlaygraphSegmentItem *)arg2 forSkip:(_Bool)arg3 lookAhead:(_Bool)arg4;
- (_Bool)shouldPerformSpeculativePreparationForNextSegmentsAfterSegment:(id <NFPlaygraphSegment>)arg1;
- (PlaygraphSegmentItem *)lookupSegmentItemForSegment:(id <NFPlaygraphSegment>)arg1;
- (id <NFPlaygraphSegmentTransitionSelector>)transitionsSelector;
@end

