//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Nbp/NFPlaylistPlayer-Protocol.h>

@class NSDate, SegmentItem;
@protocol NFPlaylistPlayerDataSource, NFPlaylistSegment, NFSegmentTransitionsSelector;

@protocol NFPlaylistPlayerInternal <NFPlaylistPlayer>
@property(readonly, nonatomic) _Bool usePlaygraphTransitionImprovements;
@property(readonly, nonatomic) _Bool useDualBoundaryObservation;
@property(readonly, nonatomic) SegmentItem *previousSegmentItem;
@property(readonly, nonatomic) SegmentItem *currentSegmentItem;
@property(readonly, nonatomic) id <NFPlaylistPlayerDataSource> dataSource;
@property(readonly, nonatomic) _Bool playbackCancelled;
@property(readonly, nonatomic) _Bool playbackClosed;
@property(readonly, nonatomic) _Bool playbackStarted;
- (long long)playbackStartLeadTimeMS;
- (void)markAndSweepSegmentItemsNotReachableFromItem:(SegmentItem *)arg1 maxDepth:(unsigned long long)arg2;
- (void)cleanupItem:(SegmentItem *)arg1;
- (SegmentItem *)nextItemAfterItem:(SegmentItem *)arg1;
- (unsigned long long)numberOfPlayersOpen;
- (unsigned long long)numberOfSegmentItemsOpen;
- (unsigned long long)numberOfSegmentItemsBeingLoaded;
- (void)notifyTransitionFromItem:(SegmentItem *)arg1 toItem:(SegmentItem *)arg2 atWallClockTime:(NSDate *)arg3;
- (SegmentItem *)prepareItemForNextSegment:(id <NFPlaylistSegment>)arg1 afterItem:(SegmentItem *)arg2 forSkip:(_Bool)arg3 lookAhead:(_Bool)arg4;
- (_Bool)shouldPerformSpeculativePreparationForNextSegmentsAfterSegment:(id <NFPlaylistSegment>)arg1;
- (SegmentItem *)lookupSegmentItemForSegment:(id <NFPlaylistSegment>)arg1;
- (id <NFSegmentTransitionsSelector>)transitionsSelector;
@end

