//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Nbp/NSObject-Protocol.h>

@class AVPlayer, NSDictionary, NSNumber, NSString, PlatformPlaybackRequest;
@protocol NSObject, NfPlaybackAuxiliaryDisplayProvider, NfPlaybackDelegate, NfPlaybackLoggingController;

@protocol NfPlaybackController <NSObject>
@property(readonly, nonatomic) _Bool didUserStartPlayback;
@property(readonly, nonatomic) double minimalVideoFps;
@property(readonly, nonatomic) _Bool hasPlayedDolby;
@property(readonly, nonatomic) _Bool hasPlayedDovi;
@property(retain, nonatomic) id <NfPlaybackDelegate> playbackDelegate;
@property(readonly, nonatomic) unsigned long long fetchOptions;
@property(readonly, nonatomic) AVPlayer *avPlayer;
@property(copy, nonatomic) NSString *uiLabel;
@property(nonatomic) _Bool isUIAutoPlay;
@property(readonly, copy, nonatomic) PlatformPlaybackRequest *platformPlaybackRequest;
- (id)createForkedPlayerWithStartingPts:(double)arg1;
- (id <NfPlaybackLoggingController>)playbackLoggingController;
- (void)setAutoStart:(_Bool)arg1 onReloadForPlaybackId:(NSString *)arg2;
- (void)startPlay;
- (void)limitVideoThroughputByNominalBps:(double)arg1;
- (void)setPlayerAuxiliaryDisplayProvider:(id <NfPlaybackAuxiliaryDisplayProvider>)arg1;
- (NSNumber *)getCurrentPlaybackBitRate;
- (_Bool)isBranching;
- (NSDictionary *)dumpState;
- (void)closePlayback;
- (void)startPlaybackWithTrackingInfo:(NSDictionary *)arg1;
- (void)initiatePlayback:(id <NfPlaybackDelegate>)arg1 startingPtsSeconds:(double)arg2 durationSeconds:(double)arg3 creditStartSeconds:(double)arg4 trackingInfo:(NSDictionary *)arg5 webVTTPlistLocation:(NSString *)arg6 autoStart:(_Bool)arg7 keepOpenAtEnd:(_Bool)arg8 allowAirplay:(_Bool)arg9;
- (_Bool)hasMovieClosed;
- (void)playlistForRequestedM3u8:(NSString *)arg1 forLoadingRequest:(id <NSObject>)arg2;
- (void)encryptionKeyForStream:(NSString *)arg1 forLoadingRequest:(id <NSObject>)arg2;
@end

