//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString, PlatformPlaybackRequest;
@protocol NfPlaydelayTimestamp, PlatformConfigProvider;

@protocol NfPrefetchPlaybackDelegate
@property(readonly, nonatomic) _Bool isMovieOpened;
@property(readonly, nonatomic) NSString *playbackId;
@property(readonly, nonatomic) NSString *movieId;
@property(readonly, nonatomic) _Bool postplayStarted;
- (void)breakRetainCycleInPlayback;
- (NSString *)getPlaybackPCMStage;
- (void)setPlaybackPCMStage:(NSString *)arg1;
- (void)setPlaydelayTimestamp:(id <NfPlaydelayTimestamp>)arg1;
- (void)processCacheExpiration;
- (PlatformPlaybackRequest *)platformPlaybackRequest;
- (_Bool)isBranching;
- (_Bool)isCacheExpired;
- (void)resumePrefetch;
- (void)cancelPrefetch;
- (void)expirePlayback;
- (void)retrieveStatusForPrefetchCacheManager:(int *)arg1 prefetchSucceeded:(_Bool *)arg2 cacheExpired:(_Bool *)arg3;
- (unsigned long long)fetchOptions;
- (id <PlatformConfigProvider>)playbackConfig;
@end

