//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class RecaptchaClient;

@interface NFRCWClient : NSObject
{
    RecaptchaClient *_recaptchaClient;
    NSObject *_delegate;
}

+ (id)createWithSiteKeyAndDelegate:(id)arg1;
- (void).cxx_destruct;
@property __weak NSObject *delegate; // @synthesize delegate=_delegate;
@property(retain) RecaptchaClient *recaptchaClient; // @synthesize recaptchaClient=_recaptchaClient;
- (void)executeLoginAction;
- (void)_handleExecuteFinished:(id)arg1 error:(id)arg2;
- (id)initWithSiteKey:(id)arg1 delegate:(id)arg2;

@end

