//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, RecaptchaToken;

@interface NFRCWToken : NSObject
{
    RecaptchaToken *_token;
}

- (void).cxx_destruct;
@property(retain) RecaptchaToken *token; // @synthesize token=_token;
@property(readonly) NSString *recaptchaToken;
- (id)initWithToken:(id)arg1;

@end

