//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol NSObject;

@interface NFRecaptchaWrapper : NSObject
{
    id <NSObject> _wrappedRecaptchaClient;
    CDUnknownBlockType _nfrcwCallback;
}

+ (id)invokeObject:(id)arg1 selector:(SEL)arg2;
+ (void)invokeVoid:(id)arg1 selector:(SEL)arg2;
+ (long long)invokeNSInteger:(id)arg1 selector:(SEL)arg2;
+ (id)_invokeOnTarget:(id)arg1 selector:(SEL)arg2 arguments:(char *)arg3 returnType:(const char *)arg4;
- (void).cxx_destruct;
@property(copy) CDUnknownBlockType nfrcwCallback; // @synthesize nfrcwCallback=_nfrcwCallback;
@property(retain) id <NSObject> wrappedRecaptchaClient; // @synthesize wrappedRecaptchaClient=_wrappedRecaptchaClient;
- (void)executeLoginActionWithCallback:(CDUnknownBlockType)arg1;
- (void)didFinishLoginExecution:(id)arg1;
- (id)initWithSiteKey:(id)arg1;
- (Class)_recaptchaClientClass;
- (id)_loadRecaptchaFramework;

@end

