//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Nbp/NSObject-Protocol.h>

@class NSArray;
@protocol NfPlaybackAudioOption, NfPlaybackSubtitleOption;

@protocol NfSubtitleAudioController <NSObject>
- (void)subtitleSegmentsReady;
- (void)enableStickyForSelectedAudioSubtitle;
- (void)selectSubtitleOption:(id <NfPlaybackSubtitleOption>)arg1;
- (void)selectAudioOption:(id <NfPlaybackAudioOption>)arg1;
- (NSArray *)availableSubtitleOptions;
- (NSArray *)availableAudioOptions;
- (id <NfPlaybackSubtitleOption>)selectedSubtitleOption;
- (id <NfPlaybackAudioOption>)selectedAudioOption;
@end

