//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NFUIFamiliarityRowCell.h"

#import "LolomoRowCell-Protocol.h"
#import "NFUICellFactoryItemProtocol-Protocol.h"
#import "NFUIScrollViewPercentageVisibleDelegateProtocol-Protocol.h"

@class LolomoListViewModel, NFUIRenderTimer, NSString, UICollectionView, UICollectionViewFlowLayout;
@protocol LolomoViewDelegate><LolomoActionDelegate;

@interface NFUILolomoFeedWrappedRowCell : NFUIFamiliarityRowCell <NFUICellFactoryItemProtocol, LolomoRowCell, NFUIScrollViewPercentageVisibleDelegateProtocol>
{
    _Bool _isForReuse;
    _Bool _hasPrefetchedAfterDisplay;
    id <LolomoViewDelegate><LolomoActionDelegate> _lolomoViewDelegate;
}

+ (id)dequeueForItemAtIndexPath:(id)arg1 inCollectionView:(id)arg2 withLolomoViewDelegate:(id)arg3;
+ (void)registerInCollectionView:(id)arg1 withLolomoViewDelegate:(id)arg2;
+ (id)viewModelForListModel:(id)arg1 withIndexPath:(id)arg2;
+ (id)customLayout;
+ (_Bool)shouldReturnClassForType:(id)arg1 withModel:(id)arg2;
+ (id)reuseIdentifier;
+ (void)load;
- (void).cxx_destruct;
@property(nonatomic) _Bool hasPrefetchedAfterDisplay; // @synthesize hasPrefetchedAfterDisplay=_hasPrefetchedAfterDisplay;
@property(nonatomic) __weak id <LolomoViewDelegate><LolomoActionDelegate> lolomoViewDelegate; // @synthesize lolomoViewDelegate=_lolomoViewDelegate;
@property(readonly, nonatomic) _Bool isForReuse; // @synthesize isForReuse=_isForReuse;
- (void)configureWithViewModel:(id)arg1;
@property(readonly, nonatomic) __weak UICollectionViewFlowLayout *collectionViewLayout;
@property(readonly, nonatomic) __weak UICollectionView *collectionView;
- (void)cellDidAppearFromContext:(unsigned long long)arg1;
- (void)cellDidEndDisplaying:(id)arg1;
- (void)cellWillDisplay:(id)arg1;
- (void)visibleInfoForViewInScrollView:(id)arg1;
- (void)prefetchVideoForModel:(id)arg1;
- (void)prefetchVisibleCells;
- (id)visibleCells;
- (void)didScrollEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)didScrollEndDecelerating:(id)arg1;
- (void)didSelectItemAtIndexPath:(id)arg1;
- (id)registrationType;
- (double)minimumInterItemSpacingForSection:(long long)arg1;
- (double)minimumLineSpacingForSection:(long long)arg1;
- (struct UIEdgeInsets)insetsForSection:(long long)arg1;
- (_Bool)shouldSkipViewModelCreationWhenSizing;
- (struct CGSize)calculatedSize:(struct CGSize)arg1 withModel:(id)arg2 withCollectionView:(id)arg3;
- (struct CGSize)staticCalculatedSizeForModel:(id)arg1 withCollectionView:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) __weak NFUIRenderTimer *renderTimer;
@property(readonly) Class superclass;
@property(readonly, nonatomic) __weak LolomoListViewModel *viewModel;

@end

