//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIScrollView;
@protocol NFUISegmentedControllerSelectableViewProtocol, NFUISegmentedControllerViewDelegate;

@interface NFUISegmentedControllerView : UIView
{
    _Bool _overrideSemanticContentAttribute;
    id <NFUISegmentedControllerViewDelegate> _delegate;
    UIView<NFUISegmentedControllerSelectableViewProtocol> *_selectedView;
    UIScrollView *_scrollView;
    UIView *_contentView;
    double _itemMargin;
    double _leadingMargin;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool overrideSemanticContentAttribute; // @synthesize overrideSemanticContentAttribute=_overrideSemanticContentAttribute;
@property(nonatomic) double leadingMargin; // @synthesize leadingMargin=_leadingMargin;
@property(nonatomic) double itemMargin; // @synthesize itemMargin=_itemMargin;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UIView<NFUISegmentedControllerSelectableViewProtocol> *selectedView; // @synthesize selectedView=_selectedView;
@property(retain, nonatomic) id <NFUISegmentedControllerViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)toggleLTR;
- (void)toggleRTL;
- (void)setScrollViewSemanticContentAttribute:(long long)arg1;
- (id)segmentedViewAtIndex:(long long)arg1;
- (void)setShouldScroll:(_Bool)arg1;
- (void)layoutSubviews;
- (void)removeAllSegmentedViews;
- (void)setupConstraintsForView:(id)arg1;
- (void)setupConstraintsForViews:(id)arg1;
- (id)segmentedViews;
- (void)addSegmentedView:(id)arg1;
- (void)addSegmentedViews:(id)arg1;
- (void)scrollItemsIntoView;
- (void)clearSelectedView;
- (void)handleTap:(id)arg1;
- (void)commonInit;
- (id)init;
- (id)initWithCoder:(id)arg1;

@end

