//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NFUIDownloadMetadata.h"

@class NSNumber, NSString;

@interface NFUIDownloadMetadataContent : NFUIDownloadMetadata
{
    NSString *_synopsis;
    NSString *_title;
    NSString *_maturityRating;
    NSNumber *_maturityLevel;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSNumber *maturityLevel; // @synthesize maturityLevel=_maturityLevel;
@property(readonly, copy, nonatomic) NSString *maturityRating; // @synthesize maturityRating=_maturityRating;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, copy, nonatomic) NSString *synopsis; // @synthesize synopsis=_synopsis;

@end

