//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NFUIFlow;

@interface NFUIFlowUnwindSegueSource : NSObject
{
    NFUIFlow *_sourceFlow;
    SEL _unwindAction;
    id _sender;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id sender; // @synthesize sender=_sender;
@property(nonatomic) SEL unwindAction; // @synthesize unwindAction=_unwindAction;
@property(retain, nonatomic) NFUIFlow *sourceFlow; // @synthesize sourceFlow=_sourceFlow;

@end

