//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LolomoAbstractEntityItemCell.h"

#import "LolomoItemCell-Protocol.h"
#import "NFUICellDisplayProtocol-Protocol.h"
#import "NFUICellFactoryItemProtocol-Protocol.h"
#import "NFUIRenderTimerDelegateProtocol-Protocol.h"
#import "NFUIReusableViewProtocol-Protocol.h"

@class CAGradientLayer, CAShapeLayer, LolomoListItemViewModel, LolomoListViewModel, NFUILabel, NFUILottieAnimationView, NFUIRenderTimer, NFUITitleTreatmentView, NSString, UICollectionView, UIImage, UIImageViewAligned, UILabel, UIView, UIViewController;
@protocol LolomoViewDelegate><LolomoActionDelegate;

@interface NFUIPreviewsLolomoItemCell : LolomoAbstractEntityItemCell <LolomoItemCell, NFUIRenderTimerDelegateProtocol, NFUICellFactoryItemProtocol, NFUIReusableViewProtocol, NFUICellDisplayProtocol>
{
    _Bool _isLayoutPass;
    _Bool hasInlineVideo;
    UICollectionView *delegateCollectionView;
    UIViewController *delegateViewController;
    LolomoListViewModel *delegateListViewModel;
    id delegate;
    UIImageViewAligned *_imageView;
    NFUITitleTreatmentView *_titleTreatmentView;
    UIImage *_panelArtImage;
    UIImage *_watchedPanelArtImage;
    UIImage *_titleTreatmentImage;
    UIImage *_watchedtitleTreatmentImage;
    CAGradientLayer *_imageGradient;
    CAShapeLayer *_imageOutline;
    unsigned long long _panelArtImageState;
    unsigned long long _titleTreatmentImageState;
    NFUILabel *_titleLabel;
    UIView *_lottieEmojiView;
    UILabel *_promoNewLabel;
    UIImageViewAligned *_promoLogo;
    CAShapeLayer *_promoOutline;
    CAGradientLayer *_promoGradientOutline;
    NFUILottieAnimationView *_animationView;
}

+ (id)viewModelForListModel:(id)arg1 withIndexPath:(id)arg2;
+ (id)dequeueForItemAtIndexPath:(id)arg1 inCollectionView:(id)arg2 withLolomoViewDelegate:(id)arg3;
+ (void)registerInCollectionView:(id)arg1 withLolomoViewDelegate:(id)arg2;
+ (id)reuseIdentifier;
+ (_Bool)shouldReturnClassForType:(id)arg1 withModel:(id)arg2;
+ (void)load;
- (void).cxx_destruct;
@property(retain, nonatomic) NFUILottieAnimationView *animationView; // @synthesize animationView=_animationView;
@property(retain, nonatomic) CAGradientLayer *promoGradientOutline; // @synthesize promoGradientOutline=_promoGradientOutline;
@property(retain, nonatomic) CAShapeLayer *promoOutline; // @synthesize promoOutline=_promoOutline;
@property(retain, nonatomic) UIImageViewAligned *promoLogo; // @synthesize promoLogo=_promoLogo;
@property(retain, nonatomic) UILabel *promoNewLabel; // @synthesize promoNewLabel=_promoNewLabel;
@property(retain, nonatomic) UIView *lottieEmojiView; // @synthesize lottieEmojiView=_lottieEmojiView;
@property(retain, nonatomic) NFUILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) unsigned long long titleTreatmentImageState; // @synthesize titleTreatmentImageState=_titleTreatmentImageState;
@property(nonatomic) unsigned long long panelArtImageState; // @synthesize panelArtImageState=_panelArtImageState;
@property(retain, nonatomic) CAShapeLayer *imageOutline; // @synthesize imageOutline=_imageOutline;
@property(retain, nonatomic) CAGradientLayer *imageGradient; // @synthesize imageGradient=_imageGradient;
@property(retain, nonatomic) UIImage *watchedtitleTreatmentImage; // @synthesize watchedtitleTreatmentImage=_watchedtitleTreatmentImage;
@property(retain, nonatomic) UIImage *titleTreatmentImage; // @synthesize titleTreatmentImage=_titleTreatmentImage;
@property(retain, nonatomic) UIImage *watchedPanelArtImage; // @synthesize watchedPanelArtImage=_watchedPanelArtImage;
@property(retain, nonatomic) UIImage *panelArtImage; // @synthesize panelArtImage=_panelArtImage;
@property(retain, nonatomic) NFUITitleTreatmentView *titleTreatmentView; // @synthesize titleTreatmentView=_titleTreatmentView;
@property(retain, nonatomic) UIImageViewAligned *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) _Bool hasInlineVideo; // @synthesize hasInlineVideo;
@property(nonatomic) _Bool isLayoutPass; // @synthesize isLayoutPass=_isLayoutPass;
@property(nonatomic) __weak id delegate; // @synthesize delegate;
@property(nonatomic) __weak LolomoListViewModel *delegateListViewModel; // @synthesize delegateListViewModel;
@property(nonatomic) __weak UIViewController *delegateViewController; // @synthesize delegateViewController;
@property(nonatomic) __weak UICollectionView *delegateCollectionView; // @synthesize delegateCollectionView;
- (void)configureWithAnimationNamed:(id)arg1;
- (struct CGAffineTransform)promoTitleTreatmentTransform;
- (void)cellDidDisappearFromContext:(unsigned long long)arg1;
- (void)cellDidAppearFromContext:(unsigned long long)arg1;
- (void)animatePromoOutline;
- (void)renderGradientPromoOutlineWithViewModel:(id)arg1;
- (id)promoTitleImage;
- (void)animateEmoji;
- (void)renderSpecialPromoPreviewItemWithViewModel:(id)arg1;
- (void)renderComedyFeedPromoPreviewItemWithViewModel:(id)arg1;
- (void)renderGeneralPromoPreviewItemWithViewModel:(id)arg1;
- (void)setPanelArtImageWithViewModel:(id)arg1;
- (struct CGRect)defaultTitleTreatmentFrame;
- (id)grayscaleImage:(id)arg1;
- (void)renderWatchedStateIfNeededWithViewModel:(id)arg1;
- (void)markReady;
- (void)animateImageOutline;
- (void)setHighlighted:(_Bool)arg1;
- (void)reportImagesPainted;
- (void)adjustFrameForCurrentTitleTreatmentImage;
- (void)setTitleTreatmentImage:(id)arg1 withViewModel:(id)arg2;
- (void)setPanelArtImage:(id)arg1 withViewModel:(id)arg2;
- (id)gradientColorsForBackgroundColor:(id)arg1;
- (void)resetPanelArtWithUrl:(id)arg1 titleTreatmentWithUrl:(id)arg2 viewModel:(id)arg3;
- (void)resetRenderedViews;
- (void)loadDisplayArt:(id)arg1;
- (void)configureWithViewModel:(id)arg1;
- (void)prepareForReuse;
- (void)viewInitialized:(_Bool)arg1;
- (struct CGSize)calculatedSize:(struct CGSize)arg1 withModel:(id)arg2 withCollectionView:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isForReuse;
@property(nonatomic) __weak id <LolomoViewDelegate><LolomoActionDelegate> lolomoViewDelegate;
@property(nonatomic) __weak NFUIRenderTimer *renderTimer;
@property(nonatomic) _Bool shouldBlockDetailsAction;
@property(nonatomic) _Bool shouldSkipViewModelCreationWhenSizing;
@property(readonly) Class superclass;
@property(readonly, nonatomic) __weak LolomoListItemViewModel *viewModel;

@end

