//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NFUIFlow, NSMutableArray, NSMutableDictionary, NSOperationQueue;
@protocol OS_dispatch_queue;

@interface NFUIFlowInternal : NSObject
{
    NSObject<OS_dispatch_queue> *_accessQueue;
    NFUIFlow *_parent;
    NSMutableArray *_children;
    NSOperationQueue *_loadOperationQueue;
    NSMutableArray *_segueOperations;
    NSMutableDictionary *_segueOperationsByKey;
}

+ (id)loadOperationQueue;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *segueOperationsByKey; // @synthesize segueOperationsByKey=_segueOperationsByKey;
@property(retain, nonatomic) NSMutableArray *segueOperations; // @synthesize segueOperations=_segueOperations;
@property(retain, nonatomic) NSOperationQueue *loadOperationQueue; // @synthesize loadOperationQueue=_loadOperationQueue;
@property(retain, nonatomic) NSMutableArray *children; // @synthesize children=_children;
@property(nonatomic) __weak NFUIFlow *parent; // @synthesize parent=_parent;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *accessQueue; // @synthesize accessQueue=_accessQueue;
- (id)init;

@end

