//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray;

@interface NFUIFamiliaritySimpleTagsView : UIView
{
    NSArray *_tags;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *tags; // @synthesize tags=_tags;
- (id)accessibilityLabel;
- (void)configureAcccessibility;
- (void)setupTags;
- (void)updateTags:(id)arg1 withDotColor:(id)arg2;
- (long long)numberOfTags;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

