//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "COEntity.h"

@class NSNumber, NSString;

@interface NFUIGenericComedyFeedEntity : COEntity
{
    _Bool _isWatched;
    NSString *overrideActionEntityType;
    NSNumber *overrideActionEntityId;
    NSString *_logoUrl;
    NSString *_logoIdentifier;
    NSString *_logoUnbrandedUrl;
    NSString *_logoUnbrandedIdentifier;
    NSString *_imageUrl;
    NSString *_imageIdentifier;
    NSString *_maturityRating;
    NSString *_title;
    NSString *_kind;
    NSNumber *_supplementalId;
    NSNumber *_topNodeVideoId;
    NSNumber *_parentId;
    NSNumber *_playbackId;
    NSString *_foregroundColorString;
    NSString *_backgroundColorString;
    NSNumber *_rawRuntime;
}

+ (id)falcorKeyPathsForUpdateMap;
+ (id)falcorKeyPathMap;
- (void).cxx_destruct;
@property(copy, nonatomic) NSNumber *rawRuntime; // @synthesize rawRuntime=_rawRuntime;
@property(copy, nonatomic) NSString *backgroundColorString; // @synthesize backgroundColorString=_backgroundColorString;
@property(copy, nonatomic) NSString *foregroundColorString; // @synthesize foregroundColorString=_foregroundColorString;
@property(nonatomic) _Bool isWatched; // @synthesize isWatched=_isWatched;
@property(copy, nonatomic) NSNumber *playbackId; // @synthesize playbackId=_playbackId;
@property(copy, nonatomic) NSNumber *parentId; // @synthesize parentId=_parentId;
@property(copy, nonatomic) NSNumber *topNodeVideoId; // @synthesize topNodeVideoId=_topNodeVideoId;
@property(copy, nonatomic) NSNumber *supplementalId; // @synthesize supplementalId=_supplementalId;
@property(copy, nonatomic) NSString *kind; // @synthesize kind=_kind;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *maturityRating; // @synthesize maturityRating=_maturityRating;
@property(copy, nonatomic) NSString *imageIdentifier; // @synthesize imageIdentifier=_imageIdentifier;
@property(copy, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
@property(copy, nonatomic) NSString *logoUnbrandedIdentifier; // @synthesize logoUnbrandedIdentifier=_logoUnbrandedIdentifier;
@property(copy, nonatomic) NSString *logoUnbrandedUrl; // @synthesize logoUnbrandedUrl=_logoUnbrandedUrl;
@property(copy, nonatomic) NSString *logoIdentifier; // @synthesize logoIdentifier=_logoIdentifier;
@property(copy, nonatomic) NSString *logoUrl; // @synthesize logoUrl=_logoUrl;
- (void)setOverrideActionEntityId:(id)arg1;
- (void)setOverrideActionEntityType:(id)arg1;
- (id)entityType;
- (id)entityId;
- (id)overrideActionEntityType;
- (id)overrideActionEntityId;
@property(readonly, copy, nonatomic) NSString *runtime;
- (id)backgroundColor;
- (id)foregroundColor;

@end

