//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSNumber, NSString, PrimaryLolomoViewController;

@interface NFUIUMAContext : NSObject
{
    _Bool _dismissPlayerOnDismiss;
    _Bool _checkLastEpisode;
    PrimaryLolomoViewController *_lolomoController;
    NSDictionary *_alertPayload;
    NSString *_button;
    NSArray *_points;
    NSNumber *_playPercent;
    NSNumber *_videoId;
}

+ (id)playbackContextWithPayload:(id)arg1;
+ (id)contextWithButton:(id)arg1;
+ (id)contextWithPoints:(id)arg1;
+ (id)lolomoContext;
- (void).cxx_destruct;
@property(nonatomic) _Bool checkLastEpisode; // @synthesize checkLastEpisode=_checkLastEpisode;
@property(retain, nonatomic) NSNumber *videoId; // @synthesize videoId=_videoId;
@property(retain, nonatomic) NSNumber *playPercent; // @synthesize playPercent=_playPercent;
@property(retain, nonatomic) NSArray *points; // @synthesize points=_points;
@property(retain, nonatomic) NSString *button; // @synthesize button=_button;
@property(nonatomic) _Bool dismissPlayerOnDismiss; // @synthesize dismissPlayerOnDismiss=_dismissPlayerOnDismiss;
@property(retain, nonatomic) NSDictionary *alertPayload; // @synthesize alertPayload=_alertPayload;
@property(nonatomic) __weak PrimaryLolomoViewController *lolomoController; // @synthesize lolomoController=_lolomoController;

@end

