//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NFUIButton.h"

@class NFUILottieAnimationView, NSLayoutConstraint;

@interface NFUIPreviewsSyleButton : NFUIButton
{
    NFUIPreviewsSyleButton *_dummyDelegateView;
    NFUILottieAnimationView *_animatedIconView;
    NSLayoutConstraint *_heightConstraint;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSLayoutConstraint *heightConstraint; // @synthesize heightConstraint=_heightConstraint;
@property(retain, nonatomic) NFUILottieAnimationView *animatedIconView; // @synthesize animatedIconView=_animatedIconView;
@property(nonatomic) __weak NFUIPreviewsSyleButton *dummyDelegateView; // @synthesize dummyDelegateView=_dummyDelegateView;
- (void)animateSizeAndLabelChangeToString:(id)arg1 isPromoType:(_Bool)arg2;
- (void)renderForStandardPreviewWithForegroundColor:(id)arg1 andBackgroundColor:(id)arg2;
- (void)renderForPromotionalPreviewWithForegroundColor:(id)arg1 andbackgroundColor:(id)arg2;
- (id)titleLabelForButtonStyle:(unsigned long long)arg1;
- (id)imageNameForButtonStyle:(unsigned long long)arg1;
- (void)setStyle:(unsigned long long)arg1 andForegroundColor:(id)arg2 andBackgroundColor:(id)arg3 animated:(_Bool)arg4;

@end

