//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NFUIFeatureManager, NSDictionary;
@protocol DataBrokerDataProviderProtocol, OS_dispatch_queue;

@interface NFUIConfigManager : NSObject
{
    NSObject<OS_dispatch_queue> *_configFileQueue;
    _Bool _canaryAllocationChecked;
    id <DataBrokerDataProviderProtocol> _delegate;
    NFUIFeatureManager *_featureManager;
}

+ (id)lolomoModel;
+ (id)sharedInstance;
+ (id)slsMessage;
+ (_Bool)kidsSLSOn;
+ (_Bool)kidsSLSMessagingEnabled;
+ (_Bool)useNewLolopi;
- (void).cxx_destruct;
@property(retain, nonatomic, getter=feature) NFUIFeatureManager *featureManager; // @synthesize featureManager=_featureManager;
@property(nonatomic) _Bool canaryAllocationChecked; // @synthesize canaryAllocationChecked=_canaryAllocationChecked;
@property(nonatomic) __weak id <DataBrokerDataProviderProtocol> delegate; // @synthesize delegate=_delegate;
- (id)configFilePath;
- (id)configDirPath;
- (void)suppressCanaryAllocationTest:(id)arg1;
- (void)setCanaryAllocationTest:(id)arg1 andCell:(id)arg2;
@property(readonly, nonatomic) NSDictionary *config;
- (id)init;
- (_Bool)isPerformanceTraceTimingEnabled;
- (_Bool)fullPlayerEmojisBarEnabled;
- (_Bool)shouldRetryError10061;
- (_Bool)isDownloadsInterstitialDisabled;
- (_Bool)isSharingTooltipDisabled;
- (_Bool)isMobileTooltipCleanupEnabled;
- (_Bool)enableMDXButtonBeforeStartup;
- (_Bool)videoFeedTestEnabled;
- (_Bool)simplifiedActionLogsEnabled;
- (_Bool)isStreamLimitLegaleseEnabled;
- (_Bool)isExtendedCreditsEnabled;
- (_Bool)bundleInAppUpsellEnabled;
- (_Bool)tvLoginMDXEnabled;
- (_Bool)comedyFeedShouldStopPlayersOnDisappear;
- (id)comedyFeedNumPlayers;
- (unsigned long long)comedyFeedTabType;
- (id)comedyFeedTabKey;
- (_Bool)comedyFeedLocalPaginationEnabled;
- (id)comedyFeedPromoVideoId;
- (_Bool)comedyFeedPreviewsEntryPointEnabled;
- (_Bool)comedyFeedIntroCardEnabled;
- (_Bool)comedyFeedSimilarsEnabled;
- (_Bool)comedyFeedEnabled;
- (_Bool)actionSheetDynamicTypeEnabled;
- (_Bool)lolomoDynamicTypeEnabled;
- (_Bool)newMDXSheetEnabled;
- (_Bool)contextualAssetsEnabled;
- (_Bool)graphQLLolomoEnabled;
- (_Bool)feedLolomoEnabled;
- (_Bool)paginatedLolomoPlusEnabled;
- (_Bool)paginatedLolomoEnabled;
- (_Bool)isGenreFilterEnabled;
- (_Bool)isImprovedVisibilityForFiltersEnabled;
- (_Bool)isGenrePromenenceEnabled;
- (_Bool)isSpeedControlEnabled;
- (_Bool)autoplaySettingsSwitchEnabled;
- (id)extrasCTAOptions;
- (_Bool)isExtasCTAEnabled;
- (_Bool)videoInDP_isRotationUpdatedEnabled;
- (_Bool)videoMerchInDPEnabled;
- (_Bool)newNavigationBarEnabledOniPad;
- (_Bool)newNavigationBarEnabled;
- (_Bool)isDownloadsMaturityFiltrationEnabled;
- (_Bool)isParentalControlWebLinksEnabled;
- (_Bool)isParentalControlEnabled;
- (_Bool)isSkipContentEnabled;
- (_Bool)hasMidnightStorm;
- (_Bool)hasTopTenTitles;
- (_Bool)isContentAdvisoryEnabled;
- (_Bool)mobileSharingTooltipEnabled;
- (_Bool)mobileSharingEnabled;
- (_Bool)disableAFNetworking;
- (_Bool)querySearchPashEnabled;
- (_Bool)prequerySearchNapaApolloEnabled;
- (_Bool)mobileCollectionsEssentialsEnabled;
- (_Bool)mobileCollectionsForceToolTip;
- (_Bool)mobileCollectionsTitleGroupsEnabled;
- (_Bool)mobileCollectionsAltRowName;
- (_Bool)mobileCollectionsNoHorizontalScrollModule;
- (_Bool)mobileCollectionsNoCategoryFilter;
- (_Bool)mobileCollectionsNoEditorialContent;
- (_Bool)mobileCollectionsNoCategoryTreatment;
- (_Bool)mobileCollectionsEnabled;
- (_Bool)clipsCollectionListEnabled;
- (_Bool)clipsClipFeedEnabled;
- (_Bool)clipsCollectionFeedEnabled;
- (_Bool)clipsEnabled;
- (id)snapchatOAuthClientID;
- (_Bool)isSimpleSharingEnabled;
- (_Bool)isOfflinePlaybackAirplaneWiFiErrorHandlingEnabled;
- (_Bool)familiarityExperimentalHydrationEnabled;
- (_Bool)familiarityForceReloadEnabled;
- (_Bool)familiarityPreloadDisabled;
- (_Bool)familiaritySimpleHeadersEnabled;
- (_Bool)familiarityAllRowsEnabled;
- (_Bool)familiarityPlaybackScrollHeuristicsEnabled;
- (_Bool)familiarityPrefetchingEnabled;
- (_Bool)familiarityParallaxBillboardEnabled;
- (_Bool)familiaritySuppressPlayButton;
- (_Bool)familiarityTitleCardTreatmentEnabled;
- (_Bool)familiarityUIEnabled;
- (_Bool)updatedPlaybackOnHoldError;
- (_Bool)boxArtLabelsEnabled;
- (_Bool)imageLabelAccessibilityEnabled;
- (_Bool)branchingPlaylistPlayerEnabled:(id)arg1;
- (_Bool)branchingPlaylistPlayerEnabled;
- (_Bool)playgraphPlayerForBranchingEnabledForBossBaby;
- (_Bool)playgraphPlayerForBranchingEnabled;
- (_Bool)usePlaygraphForQuickplay;
- (_Bool)playgraphPlayerEnabled;
- (_Bool)playlistPlayerEnabled;
- (long long)failedDownloadAlertStyle;
- (_Bool)shouldContinueAudioOnLockScreenWithLowBitrate;
- (_Bool)shouldContinueAudioOnLockScreenOnWiFiOnly;
- (_Bool)isContinueAudioOnLockScreenActive;
- (unsigned long long)quickPlayMaxPrebufferCount;
- (_Bool)isLolomoContainerEnabled;
- (_Bool)volumeLoggingEnabled;
- (_Bool)shouldShrinkOrHideTabLabels;
- (long long)updatesPageSize;
- (long long)updatesExpiryDurationInMinutes;
- (id)updatesTabKey;
- (id)updatesScrollType;
- (_Bool)isNotificationsInUpdatesTab;
- (_Bool)isUpdatesEnabled;
- (id)timeDurationAfterCrashToAutoplay;
- (_Bool)isPlaybackAfterCrashEnabled;
- (_Bool)aroGalleriesSearchAsTab;
- (_Bool)aroGalleriesForceFullLogo;
- (_Bool)aroGalleriesSuppressSubGenre;
- (_Bool)aroGalleriesIncludeRecentlyAdded;
- (_Bool)aroGalleriesSubGenreFilterText;
- (_Bool)aroGalleriesShouldHideSubGenreMenu;
- (id)loadingSkeletonDelay;
- (_Bool)isMDXSkipIntroEnabled;
- (id)tabTypeOverrides;
- (_Bool)previewsInBillboardEnabled;
- (_Bool)shouldShowDownloadsBumblebee;
- (_Bool)shouldExplicitlySetExternalPlayback;
- (_Bool)isLottieBasedThumbs;
- (_Bool)isTitleGroupsRowEnabled;
- (_Bool)isPreviewsPrefetchEnabled;
- (_Bool)isPreviewsRowEnabled;
- (_Bool)enhancedDPGesturesUseMorphTransition;
- (id)viewPortWidth;
- (id)titlesPerRow;
- (id)maxRows;
- (_Bool)shouldUseCharacterStoryArt;
- (_Bool)invalidateOnAdultProfileMismatch;

@end

