//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NFUIButton, NFUILabel, NFUILinkLabel, NSLayoutConstraint, NSNumber, StreamLimitEntity, UIActivityIndicatorView, UIStackView, UIView;
@protocol StreamLimitDelegate, UIViewControllerTransitioningDelegate;

@interface NFUIStreamLimitUpgradeViewController : UIViewController
{
    _Bool _isReadyToPurchase;
    NFUILabel *_activeScreensLabel;
    NFUIButton *_cancelButton;
    UIStackView *_buttonStackView;
    NFUILabel *_updatedPlanInfoLabel;
    UIView *_purchaseInfoView;
    UIView *_spinnerView;
    UIActivityIndicatorView *_activitySpinner;
    NSLayoutConstraint *_deviceInfoCenterContraint;
    NSLayoutConstraint *_purchasePlanCenterYContraint;
    NSLayoutConstraint *_titleLabelTopConstraint;
    NSLayoutConstraint *_messageLabelWidthConstraint;
    NSLayoutConstraint *_legalDisclaimerLeadingConstraint;
    NSLayoutConstraint *_legalDisclaimerTrailingConstraint;
    NSLayoutConstraint *_purchaseInfoHeightConstraint;
    NSLayoutConstraint *_buttonStackViewBotomConstraint;
    NFUILinkLabel *_legalDisclaimerLabel;
    NSNumber *_presentationSessionId;
    id <StreamLimitDelegate> _delegate;
    StreamLimitEntity *_model;
    id <UIViewControllerTransitioningDelegate> _transitioningDelegate;
    NFUILabel *_titleLabel;
    NFUILabel *_messageLabel;
    UIView *_activeScreensContainerView;
    NFUIButton *_upgradeButton;
    NFUIButton *_retryButton;
}

+ (id)streamLimitViewControllerWithDelegate:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) __weak NFUIButton *retryButton; // @synthesize retryButton=_retryButton;
@property(nonatomic) __weak NFUIButton *upgradeButton; // @synthesize upgradeButton=_upgradeButton;
@property(nonatomic) __weak UIView *activeScreensContainerView; // @synthesize activeScreensContainerView=_activeScreensContainerView;
@property(nonatomic) __weak NFUILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(nonatomic) __weak NFUILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) id <UIViewControllerTransitioningDelegate> transitioningDelegate; // @synthesize transitioningDelegate=_transitioningDelegate;
@property(retain, nonatomic) StreamLimitEntity *model; // @synthesize model=_model;
@property(nonatomic) __weak id <StreamLimitDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain) NSNumber *presentationSessionId; // @synthesize presentationSessionId=_presentationSessionId;
@property _Bool isReadyToPurchase; // @synthesize isReadyToPurchase=_isReadyToPurchase;
@property __weak NFUILinkLabel *legalDisclaimerLabel; // @synthesize legalDisclaimerLabel=_legalDisclaimerLabel;
@property __weak NSLayoutConstraint *buttonStackViewBotomConstraint; // @synthesize buttonStackViewBotomConstraint=_buttonStackViewBotomConstraint;
@property __weak NSLayoutConstraint *purchaseInfoHeightConstraint; // @synthesize purchaseInfoHeightConstraint=_purchaseInfoHeightConstraint;
@property __weak NSLayoutConstraint *legalDisclaimerTrailingConstraint; // @synthesize legalDisclaimerTrailingConstraint=_legalDisclaimerTrailingConstraint;
@property __weak NSLayoutConstraint *legalDisclaimerLeadingConstraint; // @synthesize legalDisclaimerLeadingConstraint=_legalDisclaimerLeadingConstraint;
@property __weak NSLayoutConstraint *messageLabelWidthConstraint; // @synthesize messageLabelWidthConstraint=_messageLabelWidthConstraint;
@property __weak NSLayoutConstraint *titleLabelTopConstraint; // @synthesize titleLabelTopConstraint=_titleLabelTopConstraint;
@property __weak NSLayoutConstraint *purchasePlanCenterYContraint; // @synthesize purchasePlanCenterYContraint=_purchasePlanCenterYContraint;
@property __weak NSLayoutConstraint *deviceInfoCenterContraint; // @synthesize deviceInfoCenterContraint=_deviceInfoCenterContraint;
@property __weak UIActivityIndicatorView *activitySpinner; // @synthesize activitySpinner=_activitySpinner;
@property __weak UIView *spinnerView; // @synthesize spinnerView=_spinnerView;
@property __weak UIView *purchaseInfoView; // @synthesize purchaseInfoView=_purchaseInfoView;
@property __weak NFUILabel *updatedPlanInfoLabel; // @synthesize updatedPlanInfoLabel=_updatedPlanInfoLabel;
@property __weak UIStackView *buttonStackView; // @synthesize buttonStackView=_buttonStackView;
@property __weak NFUIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property __weak NFUILabel *activeScreensLabel; // @synthesize activeScreensLabel=_activeScreensLabel;
- (_Bool)isOnBundleUpsell;
- (void)adjustForSuperCompact;
- (void)configureLegalNoticeIfNeeded;
- (_Bool)prefersStatusBarHidden;
- (long long)preferredStatusBarStyle;
- (void)initViewModel;
- (_Bool)accessibilityPerformEscape;
- (_Bool)accessibilityViewIsModal;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)closeButtonAction:(id)arg1;
- (void)retryButtonAction:(id)arg1;
- (void)handleError:(id)arg1;
- (void)performUpgrade;
- (void)upgradeButtonAction:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)transitionToPurchaseView;
- (void)configureActiveScreensLabel;
- (void)configureInitialDisplay;
- (void)viewDidLoad;

@end

