//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

@class HudDownloadableIdSelector, NFUILabel, NSMutableDictionary, NSObject;
@protocol OS_dispatch_queue;

@interface NFUIHudScrollView : UIScrollView
{
    _Bool _alwaysOn;
    _Bool _forAutomation;
    NSMutableDictionary *_debugInfoMsgs;
    NSMutableDictionary *_avDownloadableIdsMsgs;
    NFUILabel *_title;
    NFUILabel *_debugInfo;
    NSObject<OS_dispatch_queue> *_hudNotificationQueue;
    HudDownloadableIdSelector *_hudDownloadableIdSelector;
}

+ (id)stringFromJsonObject:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) HudDownloadableIdSelector *hudDownloadableIdSelector; // @synthesize hudDownloadableIdSelector=_hudDownloadableIdSelector;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *hudNotificationQueue; // @synthesize hudNotificationQueue=_hudNotificationQueue;
@property(retain, nonatomic) NFUILabel *debugInfo; // @synthesize debugInfo=_debugInfo;
@property(retain, nonatomic) NFUILabel *title; // @synthesize title=_title;
@property(nonatomic) _Bool forAutomation; // @synthesize forAutomation=_forAutomation;
@property(nonatomic) _Bool alwaysOn; // @synthesize alwaysOn=_alwaysOn;
@property(retain, nonatomic) NSMutableDictionary *avDownloadableIdsMsgs; // @synthesize avDownloadableIdsMsgs=_avDownloadableIdsMsgs;
@property(retain, nonatomic) NSMutableDictionary *debugInfoMsgs; // @synthesize debugInfoMsgs=_debugInfoMsgs;
- (void)receiveNotification:(id)arg1;
- (void)resizeWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)commmonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 andClosingGestureRecognizer:(id)arg2;

@end

