//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "NFUICellSelectionProtocol-Protocol.h"
#import "NFUICollectionViewCellManagerDelegate-Protocol.h"
#import "NFUIManagedCollectionViewControllerDelegate-Protocol.h"

@class NFUICollectionViewCellManager, NFUIManagedCollectionViewController, NSMutableDictionary, NSString, NavigationBarAppearanceManager;
@protocol NFUIFeedViewControllerModelProtocol, NFUIManagedCollectionViewControllerDelegate><NFUICollectionViewCellManagerDelegate><NFUIManagedFeedViewControllerDelegate><NSObject;

@interface NFUIManagedFeedViewController : UIViewController <NFUIManagedCollectionViewControllerDelegate, NFUICollectionViewCellManagerDelegate, NFUICellSelectionProtocol>
{
    _Bool _allowPagination;
    _Bool _paginationEnabled;
    _Bool _shouldDeferReload;
    _Bool _deferPaginationToScrollEnd;
    _Bool _shouldPaginateWithVelocity;
    _Bool _isWaitingToPaginate;
    id <NFUIFeedViewControllerModelProtocol> _dataModel;
    NFUICollectionViewCellManager *_cellManager;
    NFUIManagedCollectionViewController *_managedCollectionView;
    id <NFUIManagedCollectionViewControllerDelegate><NFUICollectionViewCellManagerDelegate><NFUIManagedFeedViewControllerDelegate><NSObject> _delegate;
    double _estimatedItemSize;
    unsigned long long _paginationAmount;
    double _lastOffset;
    NSMutableDictionary *_registeredTypes;
    double _lastVelocityAmount;
    double _currentVelocity;
}

- (void).cxx_destruct;
@property(nonatomic) double currentVelocity; // @synthesize currentVelocity=_currentVelocity;
@property(nonatomic) _Bool isWaitingToPaginate; // @synthesize isWaitingToPaginate=_isWaitingToPaginate;
@property(nonatomic) double lastVelocityAmount; // @synthesize lastVelocityAmount=_lastVelocityAmount;
@property(retain, nonatomic) NSMutableDictionary *registeredTypes; // @synthesize registeredTypes=_registeredTypes;
@property(nonatomic) double lastOffset; // @synthesize lastOffset=_lastOffset;
@property(nonatomic) _Bool shouldPaginateWithVelocity; // @synthesize shouldPaginateWithVelocity=_shouldPaginateWithVelocity;
@property(nonatomic) unsigned long long paginationAmount; // @synthesize paginationAmount=_paginationAmount;
@property(nonatomic) _Bool deferPaginationToScrollEnd; // @synthesize deferPaginationToScrollEnd=_deferPaginationToScrollEnd;
@property(nonatomic) double estimatedItemSize; // @synthesize estimatedItemSize=_estimatedItemSize;
@property(nonatomic) _Bool shouldDeferReload; // @synthesize shouldDeferReload=_shouldDeferReload;
@property(nonatomic) _Bool paginationEnabled; // @synthesize paginationEnabled=_paginationEnabled;
@property(nonatomic) _Bool allowPagination; // @synthesize allowPagination=_allowPagination;
@property(nonatomic) __weak id <NFUIManagedCollectionViewControllerDelegate><NFUICollectionViewCellManagerDelegate><NFUIManagedFeedViewControllerDelegate><NSObject> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NFUIManagedCollectionViewController *managedCollectionView; // @synthesize managedCollectionView=_managedCollectionView;
@property(retain, nonatomic) NFUICollectionViewCellManager *cellManager; // @synthesize cellManager=_cellManager;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)handleIsActive:(id)arg1;
- (void)handleIsNotActive:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)notifyCellDidEndDisplaying:(id)arg1 fromContext:(unsigned long long)arg2;
- (void)notifyCellWillEndDisplaying:(id)arg1 fromContext:(unsigned long long)arg2;
- (void)notifyCellDidDisplay:(id)arg1 fromContext:(unsigned long long)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setCollectionViewLayout:(id)arg1;
- (id)collectionView;
- (id)collectionViewLayout;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (_Bool)respondsToSelector:(SEL)arg1;
- (void)didScrollEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (Class)listClass;
- (id)configureCellWithViewModel:(id)arg1 withModel:(id)arg2 forIndexPath:(id)arg3 forKind:(id)arg4 withCellManager:(id)arg5 shouldCacheResult:(_Bool *)arg6;
- (id)dequeueCellForModel:(id)arg1 forIndexPath:(id)arg2 forKind:(id)arg3 withCellManager:(id)arg4;
- (struct CGSize)sizeForModel:(id)arg1 forIndexPath:(id)arg2 forKind:(id)arg3 withCellManager:(id)arg4 shouldCacheSizeResult:(_Bool *)arg5;
- (void)checkDeferredPagination;
- (void)didScrollEndDecelerating:(id)arg1;
- (void)didAnimationScrollEndDecelerating:(id)arg1;
- (void)callPaginationOnDelegate:(double)arg1;
- (void)cellDidDisplay:(id)arg1 forIndexPath:(id)arg2 forKind:(id)arg3;
- (long long)scrollDirection;
- (void)setScrollDirection:(long long)arg1;
@property(retain, nonatomic) id <NFUIFeedViewControllerModelProtocol> dataModel; // @synthesize dataModel=_dataModel;
- (_Bool)isDataModelSet;
- (double)minimumLineSpacingForSection:(long long)arg1;
- (double)minimumInterItemSpacingForSection:(long long)arg1;
- (struct UIEdgeInsets)insetsForSection:(long long)arg1;
- (id)modelForIndexPath:(id)arg1 forKind:(id)arg2;
- (long long)numberOfItemsInSection:(long long)arg1;
- (long long)numberOfSections;
- (void)reloadData;
- (void)viewDidLoad;
- (void)commonInitWithCollectionViewLayout:(id)arg1;
- (id)initWithCollectionViewLayout:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NavigationBarAppearanceManager *navBarManager;
@property(readonly) Class superclass;

@end

