//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ArgoCore/NFLXGeneratedObject.h>

@class NSNumber, NSString;

@interface NFUILolomoRequest : NFLXGeneratedObject
{
    _Bool _userRetryReachability;
    _Bool _isDeepLink;
    _Bool _useSparseViewModel;
    unsigned long long _cachePolicy;
    NSString *_lolomoId;
    NSString *_hydrationLevel;
    NSNumber *_fragmentLolomoLimitX;
    NSNumber *_fragmentLolomoLimitY;
    NSString *_customPresentationIdentifier;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool useSparseViewModel; // @synthesize useSparseViewModel=_useSparseViewModel;
@property(copy, nonatomic) NSString *customPresentationIdentifier; // @synthesize customPresentationIdentifier=_customPresentationIdentifier;
@property(nonatomic) _Bool isDeepLink; // @synthesize isDeepLink=_isDeepLink;
@property(copy, nonatomic) NSNumber *fragmentLolomoLimitY; // @synthesize fragmentLolomoLimitY=_fragmentLolomoLimitY;
@property(copy, nonatomic) NSNumber *fragmentLolomoLimitX; // @synthesize fragmentLolomoLimitX=_fragmentLolomoLimitX;
@property(copy, nonatomic) NSString *hydrationLevel; // @synthesize hydrationLevel=_hydrationLevel;
@property(nonatomic) _Bool userRetryReachability; // @synthesize userRetryReachability=_userRetryReachability;
@property(copy, nonatomic) NSString *lolomoId; // @synthesize lolomoId=_lolomoId;
@property(nonatomic) unsigned long long cachePolicy; // @synthesize cachePolicy=_cachePolicy;
- (_Bool)isCategoryRequest;
- (_Bool)isGenreRequest;
- (_Bool)isCustomRequest;
- (id)asCategoryRequest;
- (id)asGenreRequest;
- (id)asCustomRequest;

@end

