//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "NFUISearchCellRegistrationProtocol-Protocol.h"
#import "NFUISearchCellSizeProtocol-Protocol.h"

@class NFUISearchBoxArtCellViewModel, UIImage, UIImageView;

@interface NFUISearchBoxArtViewCell : UICollectionViewCell <NFUISearchCellRegistrationProtocol, NFUISearchCellSizeProtocol>
{
    NFUISearchBoxArtCellViewModel *_viewModel;
    UIImageView *_imageView;
}

+ (id)kind;
+ (id)identifier;
- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) NFUISearchBoxArtCellViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void)reloadImage:(id)arg1 identifier:(id)arg2 title:(id)arg3;
@property(readonly, nonatomic) UIImage *image;
- (struct CGSize)calculatedSize:(id)arg1;

@end

