//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@class NSArray, NSMutableDictionary, NSMutableSet;

@interface NFUILinkLabel : UILabel
{
    _Bool _suppressContainerAccessibilityElement;
    NSArray *accessibilityElements;
    NSMutableDictionary *_handlerDictionary;
    NSMutableSet *_attributedLinks;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableSet *attributedLinks; // @synthesize attributedLinks=_attributedLinks;
@property(retain, nonatomic) NSMutableDictionary *handlerDictionary; // @synthesize handlerDictionary=_handlerDictionary;
@property _Bool suppressContainerAccessibilityElement; // @synthesize suppressContainerAccessibilityElement=_suppressContainerAccessibilityElement;
@property(retain, nonatomic) NSArray *accessibilityElements; // @synthesize accessibilityElements;
- (void)processTapRecognzier:(id)arg1;
- (long long)indexOfAccessibilityElement:(id)arg1;
- (id)accessibilityElementAtIndex:(long long)arg1;
- (long long)accessibilityElementCount;
- (_Bool)isAccessibilityElement;
- (struct CGRect)boundingRectForCharacterRange:(struct _NSRange)arg1;
- (void)setLinkForSubstring:(id)arg1 withAttributes:(id)arg2 accessibilityIdentifier:(id)arg3 andLinkHandler:(CDUnknownBlockType)arg4;
- (void)setLinkForSubstring:(id)arg1 withAttributes:(id)arg2 andLinkHandler:(CDUnknownBlockType)arg3;
- (void)handleNFPreferredLocaleDidChangeNotification:(id)arg1;
- (void)updateTextAlignment;
- (void)dealloc;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)awakeFromNib;

@end

