//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFUIPlayerFoundation/NSObject-Protocol.h>

@class NFUIPlaybackRequest, NSArray, NSDictionary, NSString;
@protocol NFPlaygraphPlayerDelegate, NfPlaybackAudioOption, NfPlaybackAuxiliaryDisplayProvider, NfPlaybackDelegate, NfPlaybackSubtitleOption;

@protocol NFUIPlatformControllerProtocol <NSObject>
@property(nonatomic) __weak id <NFPlaygraphPlayerDelegate> playgraphDelegate;
- (NSString *)xid;
- (void)updateUIPlayContextForRequest:(NFUIPlaybackRequest *)arg1;
- (void)enableStickyForSelectedAudioSubtitle;
- (void)selectSubtitleOption:(id <NfPlaybackSubtitleOption>)arg1;
- (void)selectAudioOption:(id <NfPlaybackAudioOption>)arg1;
- (NSArray *)availableSubtitleOptions;
- (NSArray *)availableAudioOptions;
- (id <NfPlaybackSubtitleOption>)selectedSubtitleOption;
- (id <NfPlaybackAudioOption>)selectedAudioOption;
- (NSDictionary *)aspectDetails;
- (void)limitVideoThroughputByNominalBps:(double)arg1;
- (void)setPlayerAuxiliaryDisplayProvider:(id <NfPlaybackAuxiliaryDisplayProvider>)arg1;
- (void)closePlayback;
- (void)presentAVPlayer;
- (void)initPlaybackWithDelegate:(id <NfPlaybackDelegate>)arg1 request:(NFUIPlaybackRequest *)arg2;
@end

