//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NFUILabel, NSNumber, UIScrollView;

@interface NFUISmartDownloadsInfoViewController : UIViewController
{
    UIScrollView *_scrollView;
    NFUILabel *_whatIsHeaderLabel;
    NFUILabel *_whatIsBodyLabel;
    NFUILabel *_howHeaderLabel;
    NFUILabel *_howBodyNumeral1Label;
    NFUILabel *_howBodyNumeral2Label;
    NFUILabel *_howBodyNumeral3Label;
    NFUILabel *_howBodyLabel1;
    NFUILabel *_howBodyLabel2;
    NFUILabel *_howBodyLabel3;
    NFUILabel *_spaceHeaderLabel;
    NFUILabel *_spaceBodyLabel;
    NFUILabel *_cellularHeaderLabel;
    NFUILabel *_cellularBodyLabel;
    NSNumber *_presentationSessionId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSNumber *presentationSessionId; // @synthesize presentationSessionId=_presentationSessionId;
@property(nonatomic) __weak NFUILabel *cellularBodyLabel; // @synthesize cellularBodyLabel=_cellularBodyLabel;
@property(nonatomic) __weak NFUILabel *cellularHeaderLabel; // @synthesize cellularHeaderLabel=_cellularHeaderLabel;
@property(nonatomic) __weak NFUILabel *spaceBodyLabel; // @synthesize spaceBodyLabel=_spaceBodyLabel;
@property(nonatomic) __weak NFUILabel *spaceHeaderLabel; // @synthesize spaceHeaderLabel=_spaceHeaderLabel;
@property(nonatomic) __weak NFUILabel *howBodyLabel3; // @synthesize howBodyLabel3=_howBodyLabel3;
@property(nonatomic) __weak NFUILabel *howBodyLabel2; // @synthesize howBodyLabel2=_howBodyLabel2;
@property(nonatomic) __weak NFUILabel *howBodyLabel1; // @synthesize howBodyLabel1=_howBodyLabel1;
@property(nonatomic) __weak NFUILabel *howBodyNumeral3Label; // @synthesize howBodyNumeral3Label=_howBodyNumeral3Label;
@property(nonatomic) __weak NFUILabel *howBodyNumeral2Label; // @synthesize howBodyNumeral2Label=_howBodyNumeral2Label;
@property(nonatomic) __weak NFUILabel *howBodyNumeral1Label; // @synthesize howBodyNumeral1Label=_howBodyNumeral1Label;
@property(nonatomic) __weak NFUILabel *howHeaderLabel; // @synthesize howHeaderLabel=_howHeaderLabel;
@property(nonatomic) __weak NFUILabel *whatIsBodyLabel; // @synthesize whatIsBodyLabel=_whatIsBodyLabel;
@property(nonatomic) __weak NFUILabel *whatIsHeaderLabel; // @synthesize whatIsHeaderLabel=_whatIsHeaderLabel;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)rotationDidChange:(id)arg1;
- (void)toggleSmartDownloads:(id)arg1;
- (void)backAction:(id)arg1;
- (id)smartDownloadSwitch;
- (id)backButtonArrayWithAction:(SEL)arg1;
- (long long)preferredStatusBarStyle;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

