//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NFUIFeatureManager : NSObject
{
    _Bool _isPromoAutoplayDisabled;
    _Bool _isPostplayAutoplayDisabled;
}

@property(nonatomic) _Bool isPostplayAutoplayDisabled; // @synthesize isPostplayAutoplayDisabled=_isPostplayAutoplayDisabled;
@property(nonatomic) _Bool isPromoAutoplayDisabled; // @synthesize isPromoAutoplayDisabled=_isPromoAutoplayDisabled;
- (void)configLoaded:(id)arg1;
- (id)init;

@end

