//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ArgoCore/NFUIFlowSegue.h>

@class NFUIFlowUnwindSegueSource;

@interface NFUIFlowUnwindSegue : NFUIFlowSegue
{
    NFUIFlowUnwindSegueSource *_unwindSource;
}

+ (id)destinationFlowForUnwindSegueSource:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NFUIFlowUnwindSegueSource *unwindSource; // @synthesize unwindSource=_unwindSource;
- (void)perform;
- (id)initWithUnwindSource:(id)arg1 destination:(id)arg2;

@end

