//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"
#import "UIAccessibilityIdentification-Protocol.h"
#import "ViewControllerOverContextDelegateProtocol-Protocol.h"

@class LolomoViewModel, NFUILolomoRequest, NFUIRatingService, NSString, NavigationBarAppearanceManager, UICollectionView, UICollectionViewFlowLayout, _TtC4Argo21ActionSheetController, _TtC4Argo25NFUIRemoveFromListService;
@protocol UIViewControllerTransitionCoordinator;

@protocol NFUILolomoProtocol <NSObject, UIAccessibilityIdentification, ViewControllerOverContextDelegateProtocol>
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator>)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)reloadDataComplete;
- (_Bool)isViewControllerPresentOverContext;
- (void)willEnterForeground;
- (void)hideCollection:(_Bool)arg1;
- (void)showCollection:(_Bool)arg1 completion:(void (^)(_Bool))arg2;
- (void)hideActivity;
- (void)showActivityForRequest:(NFUILolomoRequest *)arg1;
- (UICollectionView *)nonManagedCollectionView;
@property(nonatomic) __weak UICollectionView *collectionView;
- (UICollectionView *)createCollectionViewWithFlowLayout:(UICollectionViewFlowLayout *)arg1;
- (_Bool)navBarManagerIsTransparent;
- (void)configureNavBarManager:(UICollectionView *)arg1;
- (void)configureNavBarManager;
- (void)reloadCollectionView:(UICollectionView *)arg1;
- (void)configureWithViewModel:(LolomoViewModel *)arg1;
@property(nonatomic, retain) LolomoViewModel *viewModel;
- (LolomoViewModel *)createNewViewModel:(NFUILolomoRequest *)arg1;
@property(nonatomic, retain) _TtC4Argo21ActionSheetController *actionSheetController;
@property(nonatomic, retain) _TtC4Argo25NFUIRemoveFromListService *removeFromListService;
@property(nonatomic, retain) NFUIRatingService *ratingService;
@property(nonatomic, retain) NFUILolomoRequest *pendingLolomoRequest;
@property(nonatomic, retain) NavigationBarAppearanceManager *navBarManager;
@property(nonatomic, copy) NSString *presentationViewIdentifier;
@property(nonatomic, copy) NSString *accessibilityIdentifier;
@end

