//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIStackView.h>

@class NFUIListButton, NSArray, NSString;
@protocol NFUIDynamicStackButtonsDataSource, NFUIDynamicStackButtonsDelegate;

@interface NFUIDynamicStackButtonsView : UIStackView
{
    _Bool _isPlayButtonCentered;
    id <NFUIDynamicStackButtonsDelegate> _delegate;
    id <NFUIDynamicStackButtonsDataSource> _datasource;
    NSArray *_buttonsArray;
    NSString *_accessibilityPrefix;
    unsigned long long _listStatus;
    NFUIListButton *_myListButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NFUIListButton *myListButton; // @synthesize myListButton=_myListButton;
@property(nonatomic) unsigned long long listStatus; // @synthesize listStatus=_listStatus;
@property(retain, nonatomic) NSString *accessibilityPrefix; // @synthesize accessibilityPrefix=_accessibilityPrefix;
@property(retain, nonatomic) NSArray *buttonsArray; // @synthesize buttonsArray=_buttonsArray;
@property(nonatomic) _Bool isPlayButtonCentered; // @synthesize isPlayButtonCentered=_isPlayButtonCentered;
@property(nonatomic) __weak id <NFUIDynamicStackButtonsDataSource> datasource; // @synthesize datasource=_datasource;
@property(nonatomic) __weak id <NFUIDynamicStackButtonsDelegate> delegate; // @synthesize delegate=_delegate;
- (void)buttonClicked:(id)arg1;
- (void)refreshButtons:(id)arg1 myListAction:(unsigned long long)arg2;
- (void)updateMyListStatusIfNeeded:(id)arg1 myListStatus:(unsigned long long)arg2;
- (void)configureMyListButtonWithTag:(long long)arg1 andIdentifier:(id)arg2 isVertical:(_Bool)arg3;
- (void)setupWithButtons:(id)arg1 accessibilityPrefix:(id)arg2 myListStatus:(unsigned long long)arg3;

@end

