//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSFastEnumeration-Protocol.h"

@class NSMutableOrderedSet, NSNumber, NSString;
@protocol UpdatesListViewModelProtocol;

@interface NFUIUpdatesListViewModel : NSObject <NSFastEnumeration>
{
    NSMutableOrderedSet *_list;
    id <UpdatesListViewModelProtocol> _delegate;
    NSString *_listContext;
    NSNumber *_trackId;
    NSString *_requestId;
    NSString *_listId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *listId; // @synthesize listId=_listId;
@property(retain, nonatomic) NSString *requestId; // @synthesize requestId=_requestId;
@property(retain, nonatomic) NSNumber *trackId; // @synthesize trackId=_trackId;
@property(retain, nonatomic) NSString *listContext; // @synthesize listContext=_listContext;
@property(nonatomic) __weak id <UpdatesListViewModelProtocol> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSMutableOrderedSet *list; // @synthesize list=_list;
- (id)itemAtIndex:(unsigned long long)arg1;
- (unsigned long long)count;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (long long)updateViewModelWithResults:(id)arg1 baseKey:(id)arg2 summaryKeyPath:(id)arg3 dataKey:(id)arg4 fromIndex:(long long)arg5 toIndex:(long long)arg6 andObjectContext:(id)arg7;
- (id)init;

@end

