//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface NSObject (NFLX)
+ (id)castObject:(id)arg1;
+ (id)decodableObjectFrom:(id)arg1 using:(Class)arg2;
@property(retain, nonatomic) NSString *memoryAddress;
@end

