//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Nbp/NfOfflineLicenseInfo-Protocol.h>

@class NSDate, NSString;

@interface OfflineLicenseInfo : NSObject <NfOfflineLicenseInfo>
{
    _Bool _allowAutoLicenseRefresh;
    double _playWindowInterval;
    NSDate *_currentPlayWindowEnd;
    long long _playWindowRefreshLimit;
    long long _licenseRefreshLimit;
    NSDate *_licenseEnd;
    NSDate *_refreshLicenseTimestamp;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool allowAutoLicenseRefresh; // @synthesize allowAutoLicenseRefresh=_allowAutoLicenseRefresh;
@property(readonly, nonatomic) NSDate *refreshLicenseTimestamp; // @synthesize refreshLicenseTimestamp=_refreshLicenseTimestamp;
@property(readonly, nonatomic) NSDate *licenseEnd; // @synthesize licenseEnd=_licenseEnd;
@property(readonly, nonatomic) long long licenseRefreshLimit; // @synthesize licenseRefreshLimit=_licenseRefreshLimit;
@property(readonly, nonatomic) long long playWindowRefreshLimit; // @synthesize playWindowRefreshLimit=_playWindowRefreshLimit;
@property(readonly, nonatomic) NSDate *currentPlayWindowEnd; // @synthesize currentPlayWindowEnd=_currentPlayWindowEnd;
@property(readonly, nonatomic) double playWindowInterval; // @synthesize playWindowInterval=_playWindowInterval;
- (long long)_calculatelicenseRefreshLimit:(id)arg1;
- (id)initWithRecord:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

