//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Nbp/NSObject-Protocol.h>

@class NSArray, NSDictionary, NSNumber, NSObject, NSString;
@protocol OfflineRecordProtocol;

@protocol OfflineDBProtocol <NSObject>
- (NSArray *)recoverableDownloads;
- (NSArray *)removedDownloads;
- (NSArray *)expiredDownloads;
- (NSArray *)progressingDownloads;
- (NSArray *)startedDownloads;
- (NSArray *)queuedDownloads;
- (NSArray *)allDownloads;
- (NSObject<OfflineRecordProtocol> *)downloadsByMovieId:(NSString *)arg1;
- (NSObject<OfflineRecordProtocol> *)downloadForAssetURL:(NSString *)arg1;
- (NSObject<OfflineRecordProtocol> *)downloadForDownloadID:(NSNumber *)arg1;
- (NSObject<OfflineRecordProtocol> *)createOfflineRecordForMovieId:(NSString *)arg1 quality:(NSString *)arg2 dlxid:(NSString *)arg3 oxid:(NSString *)arg4 trackingInfo:(NSDictionary *)arg5;
@end

