//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Nbp/OfflineDependencyProvider-Protocol.h>

@class APIConfiguration, PBOClient, PlatformConfigManager;
@protocol NfRegistrationController, StoreCrypto;

@interface OfflineDependencyContainer : NSObject <OfflineDependencyProvider>
{
    PBOClient *_pboClient;
    PlatformConfigManager *_platformConfigProvider;
    id <NfRegistrationController> _registrationController;
    id <StoreCrypto> _storeCrypto;
    APIConfiguration *_configuration;
}

- (void).cxx_destruct;
@property(retain, nonatomic) APIConfiguration *configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) id <StoreCrypto> storeCrypto; // @synthesize storeCrypto=_storeCrypto;
@property(retain, nonatomic) id <NfRegistrationController> registrationController; // @synthesize registrationController=_registrationController;
@property(retain, nonatomic) PlatformConfigManager *platformConfigProvider; // @synthesize platformConfigProvider=_platformConfigProvider;
@property(retain, nonatomic) PBOClient *pboClient; // @synthesize pboClient=_pboClient;
- (id)initWithPBOClient:(id)arg1 configManager:(id)arg2 registrationController:(id)arg3 storeCrypto:(id)arg4 apiConfiguration:(id)arg5;

@end

