//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Nbp/MSLClient-Protocol.h>

@protocol IMslClient;

@interface PlatformMSLClient : NSObject <MSLClient>
{
    id <IMslClient> _client;
}

- (void).cxx_destruct;
@property(retain) id <IMslClient> client; // @synthesize client=_client;
- (void)backupMSLCredentialsFromId:(id)arg1 toId:(id)arg2;
- (void)updateMSLCredentialsFromId:(id)arg1 toId:(id)arg2;
- (id)sendMslRequest:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)_sendMslRequest:(id)arg1 task:(id)arg2 callback:(CDUnknownBlockType)arg3 tryCount:(long long)arg4;
- (void)_handleMslTaskResult:(id)arg1 request:(id)arg2 clientResponse:(id)arg3 clientError:(id)arg4 callback:(CDUnknownBlockType)arg5;
- (id)_createMSLCredentials:(id)arg1;
- (_Bool)_maybeRetry5xxError:(id)arg1 task:(id)arg2 request:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (id)requestWithURL:(id)arg1 headers:(id)arg2 credentials:(id)arg3 body:(id)arg4 timeout:(double)arg5;
- (id)requestWithURL:(id)arg1 headers:(id)arg2 GUID:(id)arg3 body:(id)arg4 timeout:(double)arg5;
- (id)requestWithURL:(id)arg1 headers:(id)arg2 body:(id)arg3 timeout:(double)arg4;
- (id)initWithClient:(id)arg1;

@end

