//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Nbp/MSLTask-Protocol.h>

@interface PlatformMSLTask : NSObject <MSLTask>
{
    _Bool _isCanceled;
    long long _numTries;
}

@property long long numTries; // @synthesize numTries=_numTries;
@property _Bool isCanceled; // @synthesize isCanceled=_isCanceled;
- (void)cancel;
- (id)init;

@end

