//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Nbp/PlaygraphSegmentItemPrepBaseStrategy.h>

@interface PlaygraphSegmentRemainingTimeBasedPrepStrategy2 : PlaygraphSegmentItemPrepBaseStrategy
{
    _Bool _nextSegmentReuseFix;
    double _remainingTimeThreshold;
    double _numberOfItemsAllowedLoadingInParallel;
}

@property(nonatomic) _Bool nextSegmentReuseFix; // @synthesize nextSegmentReuseFix=_nextSegmentReuseFix;
@property(nonatomic) double numberOfItemsAllowedLoadingInParallel; // @synthesize numberOfItemsAllowedLoadingInParallel=_numberOfItemsAllowedLoadingInParallel;
@property(nonatomic) double remainingTimeThreshold; // @synthesize remainingTimeThreshold=_remainingTimeThreshold;
- (_Bool)shouldPrepareTransition:(id)arg1 forPlayer:(id)arg2 atPosition:(CDStruct_aa637a14)arg3;
- (id)transitionsToBePreparedForPlayer:(id)arg1 forPosition:(CDStruct_aa637a14)arg2;
- (void)prepareForPlaygraphPlayer:(id)arg1 forPosition:(CDStruct_aa637a14)arg2;
- (id)segmentsOrderedByDistanceFrom:(id)arg1 maxDistance:(unsigned long long)arg2;
- (_Bool)shouldPrepareAdditionalSegmentItemsForPlaygraphPlayer:(id)arg1;
- (_Bool)canLoadAnotherPlayerInParallel:(id)arg1;
- (_Bool)playerSlotAvailable:(id)arg1;
- (void)playgraphPlayer:(id)arg1 didUpdatePlaygraphPosition:(CDStruct_aa637a14)arg2;
- (id)init;

@end

