//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Nbp/ChoiceMapLoaderDelegate-Protocol.h>
#import <Nbp/NFPlaylistPlayer-Protocol.h>
#import <Nbp/NFPlaylistPlayerDataSourceChangeObserver-Protocol.h>
#import <Nbp/NFPlaylistPlayerInternal-Protocol.h>
#import <Nbp/NFPlaylistTimeConversionDelegate-Protocol.h>
#import <Nbp/SegmentItemDelegate-Protocol.h>

@class AVPlayer, CADisplayLink, ChoiceMapLoader, NSMutableDictionary, NSString, PlaybackStateSnapshot, SegmentItem;
@protocol NFPlayerDelegate, NFPlayerFactory, NFPlayerInternal, NFPlaylist, NFPlaylistPlayerDataSource, NFPlaylistPlayerDelegate, NFPlaylistSegment, NFPlaylistTimeConversionDelegate, NFSegmentTransitionsSelector, NfPlaybackLoggingController, NfSubtitleAudioController, SegmentItemPreparationStrategy;

@interface PlaylistPlayer : NSObject <NFPlaylistTimeConversionDelegate, NFPlaylistPlayerDataSourceChangeObserver, ChoiceMapLoaderDelegate, SegmentItemDelegate, NFPlaylistPlayerInternal, NFPlaylistPlayer>
{
    _Bool _playerReadyToPlayNotifiedToDelegate;
    _Bool _transitionInProgress;
    _Bool _useAccurateTimingForBranchingPlayback;
    _Bool _delayPreviousSegmentItemCleanup;
    _Bool _segmentStartNotified;
    _Bool _usePlaygraphTransitionImprovements;
    _Bool _currentSegmentItemPresented;
    _Bool _playlistPlayerSegmentItemCleanupFix;
    _Bool _doNotShareBoundaryRegistrations;
    _Bool _useNextSegmentReuseFix;
    _Bool _pipActive;
    _Bool _useCellDataLimitsOnPlaylistPlayer;
    _Bool _playbackStarted;
    _Bool _playbackClosed;
    _Bool _playbackCancelled;
    _Bool _useDualBoundaryObservation;
    _Bool _useAlwaysNewAVPlayerForBranching;
    float persistentRate;
    id <NFPlaylistPlayerDataSource> _dataSource;
    id <NFPlaylistPlayerDelegate> _playlistDelegate;
    id <NFPlaylistTimeConversionDelegate> _timeConversionDelegate;
    id <NFPlayerFactory> _playerFactory;
    NSString *_uniqueRequestId;
    ChoiceMapLoader *_choiceMapLoader;
    CDUnknownBlockType _choiceMapLoaderCompletionBlock;
    long long _transitionType;
    unsigned long long _repositionAttemptCount;
    id <NFSegmentTransitionsSelector> _transitionsSelector;
    id <SegmentItemPreparationStrategy> _preparationStrategy;
    NSMutableDictionary *_playbackIdToSegmentIdMap;
    NSMutableDictionary *_playerByPlaybackId;
    NSMutableDictionary *_transitionUserInitiatedMarkers;
    double _learnedPlaybackStartLeadTimeMS;
    CADisplayLink *_displayLink;
    double _transitionFirstDisplayLinkTimestamp;
    PlaybackStateSnapshot *_transitionInitialStateSnapshot;
    SegmentItem *_currentSegmentItem;
    SegmentItem *_previousSegmentItem;
    id <NFPlayerDelegate> _delegate;
    id <NFPlayerInternal> _currentPlayer;
    id <NFPlaylist> _currentPlaylist;
    id <NFPlaylistSegment> _currentSegment;
    NSMutableDictionary *_segmentItemMap;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *segmentItemMap; // @synthesize segmentItemMap=_segmentItemMap;
@property(nonatomic) _Bool useAlwaysNewAVPlayerForBranching; // @synthesize useAlwaysNewAVPlayerForBranching=_useAlwaysNewAVPlayerForBranching;
@property(nonatomic) _Bool useDualBoundaryObservation; // @synthesize useDualBoundaryObservation=_useDualBoundaryObservation;
@property(retain, nonatomic) id <NFPlaylistSegment> currentSegment; // @synthesize currentSegment=_currentSegment;
@property(retain, nonatomic) id <NFPlaylist> currentPlaylist; // @synthesize currentPlaylist=_currentPlaylist;
@property(retain, nonatomic) id <NFPlayerInternal> currentPlayer; // @synthesize currentPlayer=_currentPlayer;
@property(nonatomic) __weak id <NFPlayerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SegmentItem *previousSegmentItem; // @synthesize previousSegmentItem=_previousSegmentItem;
@property(retain, nonatomic) SegmentItem *currentSegmentItem; // @synthesize currentSegmentItem=_currentSegmentItem;
@property(nonatomic) _Bool playbackCancelled; // @synthesize playbackCancelled=_playbackCancelled;
@property(nonatomic) _Bool playbackClosed; // @synthesize playbackClosed=_playbackClosed;
@property(nonatomic) _Bool playbackStarted; // @synthesize playbackStarted=_playbackStarted;
@property(nonatomic) _Bool useCellDataLimitsOnPlaylistPlayer; // @synthesize useCellDataLimitsOnPlaylistPlayer=_useCellDataLimitsOnPlaylistPlayer;
@property(nonatomic) _Bool pipActive; // @synthesize pipActive=_pipActive;
@property(nonatomic) _Bool useNextSegmentReuseFix; // @synthesize useNextSegmentReuseFix=_useNextSegmentReuseFix;
@property(nonatomic) _Bool doNotShareBoundaryRegistrations; // @synthesize doNotShareBoundaryRegistrations=_doNotShareBoundaryRegistrations;
@property(nonatomic) _Bool playlistPlayerSegmentItemCleanupFix; // @synthesize playlistPlayerSegmentItemCleanupFix=_playlistPlayerSegmentItemCleanupFix;
@property(retain, nonatomic) PlaybackStateSnapshot *transitionInitialStateSnapshot; // @synthesize transitionInitialStateSnapshot=_transitionInitialStateSnapshot;
@property(nonatomic) double transitionFirstDisplayLinkTimestamp; // @synthesize transitionFirstDisplayLinkTimestamp=_transitionFirstDisplayLinkTimestamp;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(nonatomic) _Bool currentSegmentItemPresented; // @synthesize currentSegmentItemPresented=_currentSegmentItemPresented;
@property(nonatomic) double learnedPlaybackStartLeadTimeMS; // @synthesize learnedPlaybackStartLeadTimeMS=_learnedPlaybackStartLeadTimeMS;
@property(nonatomic) _Bool usePlaygraphTransitionImprovements; // @synthesize usePlaygraphTransitionImprovements=_usePlaygraphTransitionImprovements;
@property(nonatomic) _Bool segmentStartNotified; // @synthesize segmentStartNotified=_segmentStartNotified;
@property(nonatomic) _Bool delayPreviousSegmentItemCleanup; // @synthesize delayPreviousSegmentItemCleanup=_delayPreviousSegmentItemCleanup;
@property(retain, nonatomic) NSMutableDictionary *transitionUserInitiatedMarkers; // @synthesize transitionUserInitiatedMarkers=_transitionUserInitiatedMarkers;
@property(nonatomic) _Bool useAccurateTimingForBranchingPlayback; // @synthesize useAccurateTimingForBranchingPlayback=_useAccurateTimingForBranchingPlayback;
@property(retain, nonatomic) NSMutableDictionary *playerByPlaybackId; // @synthesize playerByPlaybackId=_playerByPlaybackId;
@property(retain, nonatomic) NSMutableDictionary *playbackIdToSegmentIdMap; // @synthesize playbackIdToSegmentIdMap=_playbackIdToSegmentIdMap;
@property(retain, nonatomic) id <SegmentItemPreparationStrategy> preparationStrategy; // @synthesize preparationStrategy=_preparationStrategy;
@property(retain, nonatomic) id <NFSegmentTransitionsSelector> transitionsSelector; // @synthesize transitionsSelector=_transitionsSelector;
@property(nonatomic) unsigned long long repositionAttemptCount; // @synthesize repositionAttemptCount=_repositionAttemptCount;
@property(nonatomic) long long transitionType; // @synthesize transitionType=_transitionType;
@property(nonatomic) _Bool transitionInProgress; // @synthesize transitionInProgress=_transitionInProgress;
@property(copy, nonatomic) CDUnknownBlockType choiceMapLoaderCompletionBlock; // @synthesize choiceMapLoaderCompletionBlock=_choiceMapLoaderCompletionBlock;
@property(retain, nonatomic) ChoiceMapLoader *choiceMapLoader; // @synthesize choiceMapLoader=_choiceMapLoader;
@property(nonatomic) _Bool playerReadyToPlayNotifiedToDelegate; // @synthesize playerReadyToPlayNotifiedToDelegate=_playerReadyToPlayNotifiedToDelegate;
@property(readonly, nonatomic) NSString *uniqueRequestId; // @synthesize uniqueRequestId=_uniqueRequestId;
@property(retain, nonatomic) id <NFPlayerFactory> playerFactory; // @synthesize playerFactory=_playerFactory;
@property(nonatomic) __weak id <NFPlaylistTimeConversionDelegate> timeConversionDelegate; // @synthesize timeConversionDelegate=_timeConversionDelegate;
@property(nonatomic) __weak id <NFPlaylistPlayerDelegate> playlistDelegate; // @synthesize playlistDelegate=_playlistDelegate;
@property(retain, nonatomic) id <NFPlaylistPlayerDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(readonly, nonatomic) float persistentRate; // @synthesize persistentRate;
- (_Bool)isRetinaScreen;
- (_Bool)isDeviceSlowForBranching;
- (void)_didEndTransitionWithPlaybackState:(id)arg1 loggingController:(id)arg2;
- (void)displayLinkTimerFired;
- (void)teardownDisplayLink;
- (void)setupDisplayLink;
- (void)updatePlaybackStartLeadTimeMS:(long long)arg1;
- (long long)playbackStartLeadTimeMS;
- (void)_willBeginTransitionWithPlaybackState:(id)arg1 userInitiated:(_Bool)arg2 transitionWeight:(long long)arg3 loggingController:(id)arg4;
- (id)createPlaybackStateSnapshot;
- (_Bool)shouldLogTransitionsForItem:(id)arg1;
- (CDStruct_aa637a14)convertToPlaylistPositionForPlayer:(id)arg1 playlistOffset:(double)arg2;
- (double)convertToPresentableTimeForPlayer:(id)arg1 playlistPosition:(CDStruct_aa637a14)arg2;
- (double)presentableDurationForPlayer:(id)arg1;
- (void)reconcileNextItemsAfterUpdateInDataSource:(id)arg1 forSegment:(id)arg2;
- (void)dataSource:(id)arg1 didUpdatePlaylist:(id)arg2;
- (void)dataSource:(id)arg1 didChangeNextSegmentAfterSegment:(id)arg2;
- (id)player;
@property(nonatomic) float rate;
@property(nonatomic) float volume;
@property(readonly, nonatomic) double currentTime;
@property(readonly, nonatomic) double duration;
@property(readonly, nonatomic) _Bool currentItemPlaybackLikelyToKeepUp;
@property(readonly, nonatomic) _Bool externalPlaybackActive;
@property(readonly, nonatomic) _Bool allowsExternalPlayback;
- (void)startPlaybackWithTrackingInfo:(id)arg1;
- (void)percentSubtitleFontSize:(double)arg1;
- (void)positionSubtitleWithPercent:(double)arg1;
- (void)stop;
- (_Bool)seekFrom:(double)arg1 to:(double)arg2 completion:(CDUnknownBlockType)arg3;
- (void)beginScrubbing;
- (void)pause;
- (void)play;
- (void)closePlayback;
- (void)startPlayback;
- (void)presentAVPlayer;
@property(readonly, nonatomic) NSString *xid;
@property double preferredVideoNominalBps;
@property(readonly, nonatomic) id <NfPlaybackLoggingController> loggingController;
@property(readonly, nonatomic) id <NfSubtitleAudioController> subtitleAudioController;
- (void)segmentItem:(id)arg1 didOpenMovieWithChoiceMap:(id)arg2 withExpiration:(id)arg3 andError:(id)arg4;
- (void)segmentItem:(id)arg1 shouldStartPreparingNextSegment:(id)arg2 withWeight:(id)arg3 allowSkip:(_Bool)arg4;
- (void)segmentItem:(id)arg1 playerEffectiveRateChangedFrom:(float)arg2 to:(float)arg3;
- (void)segmentItem:(id)arg1 playerRateChangedFrom:(float)arg2 to:(float)arg3;
- (id)sharedAVPlayerForSegmentItem:(id)arg1;
- (void)segmentItem:(id)arg1 updatedPts:(double)arg2;
- (void)notifySegmentItemStarted:(id)arg1;
- (void)logTransitionToCurrentItemCompleted;
- (void)notifySegmentItemPreparationEnded:(id)arg1;
- (void)segmentItemStateChanged:(id)arg1 fromState:(int)arg2 toState:(int)arg3;
- (void)segmentItemReachedEnd:(id)arg1 withError:(id)arg2;
- (void)presentPlayer:(id)arg1;
- (void)notifyStartOfSegment:(id)arg1 startTime:(double)arg2;
- (void)notifyTransitionFromItem:(id)arg1 toItem:(id)arg2 atWallClockTime:(id)arg3;
- (void)playCurrentSegmentItemIfNeededAndLogTransition;
- (void)handleCurrentSegmentItemReadyToPlayAtTargetPosition:(double)arg1;
- (void)repositionCurrentSegmentItemIfNeededAndPlayAtTargetPosition:(double)arg1;
- (void)handleCurrentSegmentItemPendingLoading;
- (_Bool)shouldPausePreviousItem:(double)arg1;
- (void)pausePreviousItemIfNeeded:(double)arg1;
- (void)notifyDelegateOfChangesIfNeeded;
- (void)fixPlaylistMovieDurationIfNeededForSegmentItem:(id)arg1;
- (_Bool)repositionSegmentItemIfNeeded:(id)arg1 targetPosition:(double)arg2;
- (void)playSegmentItem:(id)arg1 targetPosition:(double)arg2;
- (void)logStartOfTransitionToItemIfNeeded:(id)arg1;
- (void)abandonTransition;
- (void)cleanupPreviousItemIfNeeded;
- (void)startPlaybackForItem:(id)arg1;
- (void)markAndSweepSegmentItemsReachableFromItem:(id)arg1;
- (void)markAndSweepSegmentItemsNotReachableFromItem:(id)arg1 maxDepth:(unsigned long long)arg2;
- (void)cleanupItem:(id)arg1;
- (void)cleanupItem:(id)arg1 force:(_Bool)arg2;
- (void)mapSegmentItem:(id)arg1;
- (unsigned long long)numberOfPlayersOpen;
- (unsigned long long)numberOfSegmentItemsOpen;
- (unsigned long long)numberOfSegmentItemsBeingLoaded;
- (id)lookupSegmentItemForSegment:(id)arg1;
- (id)setupSegmentItemWithPlayer:(id)arg1 forSegment:(id)arg2;
- (id)playerWithRequest:(id)arg1 delegate:(id)arg2;
- (_Bool)playerNotAssignedToAnySegment:(id)arg1;
- (id)setupSegmentItemWithRequest:(id)arg1 forSegmentId:(id)arg2 inPlaylist:(id)arg3;
- (void)prepareLookAheadItemsAfterItem:(id)arg1;
- (id)prepareItemForNextSegment:(id)arg1 afterItem:(id)arg2 forSkip:(_Bool)arg3 lookAhead:(_Bool)arg4;
- (id)prepareItemWithNewPlayerForNextSegment:(id)arg1;
- (void)prepareItemForNextSegmentAfterItem:(id)arg1 forSkip:(_Bool)arg2 lookAhead:(_Bool)arg3;
- (_Bool)shouldPerformSpeculativePreparationForNextSegmentsAfterSegment:(id)arg1;
- (id)prepareForPlaybackSegment:(id)arg1 startTime:(double)arg2;
- (double)lookupViewableDurationForSegment:(id)arg1;
- (double)lookupCreditsStartSecondsForSegment:(id)arg1;
- (void)startSegment:(id)arg1 atStartTime:(double)arg2;
- (void)choiceMapLoader:(id)arg1 didLoadChoiceMap:(id)arg2 withExpiration:(id)arg3 andError:(id)arg4;
- (void)releasePlayerFromSegmentItem:(id)arg1;
- (void)assignPlayer:(id)arg1 toSegmentItem:(id)arg2;
- (void)removePlayer:(id)arg1;
- (void)addPlayer:(id)arg1 forVideoId:(id)arg2;
- (id)anyPlayerForByMovieId:(id)arg1;
- (id)nextItemAfterItem:(id)arg1;
- (void)loadPlaylistWithRequest:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)updatePlaylist:(id)arg1 trackingInfo:(id)arg2 startPosition:(CDStruct_aa637a14)arg3;
- (void)updateNextSegmentWeightsForSegmentId:(id)arg1 nextSegmentWeights:(id)arg2;
- (void)gotoNextSegment;
- (void)gotoSegmentId:(id)arg1 time:(double)arg2 userInitiated:(_Bool)arg3;
- (void)gotoSegmentId:(id)arg1 time:(double)arg2;
- (void)gotoNextSegmentFromCurrentSegmentId:(id)arg1 nextSegmentId:(id)arg2 userInitiated:(_Bool)arg3;
- (void)gotoNextSegmentFromCurrentSegmentId:(id)arg1 nextSegmentId:(id)arg2;
- (void)setNextSegmentAfterSegmentId:(id)arg1 nextSegmentId:(id)arg2 userInitiated:(_Bool)arg3;
- (void)markTransitionFromSegmentId:(id)arg1 toSegmentId:(id)arg2 userInitiated:(_Bool)arg3;
- (_Bool)isTransitionUserInitiatedFromSegmentId:(id)arg1 toSegmentId:(id)arg2;
- (void)setNextSegmentAfterSegmentId:(id)arg1 nextSegmentId:(id)arg2;
- (void)pipDidStop;
- (void)pipDidStart;
- (id)aspectDetails;
@property(readonly, nonatomic) AVPlayer *avPlayer;
@property(readonly, nonatomic) CDStruct_aa637a14 currentPosition;
@property(readonly, nonatomic) NSString *movieId;
@property(readonly, nonatomic) NSString *playbackId;
- (void)dealloc;
- (id)initWithDataSource:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

