//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFPrefetchCache/BasePrefetchCacheManager.h>

@class NSString, PrefetchCacheManager2;
@protocol NrdControllerInternal;

@interface PrefetchCacheManager2Group : BasePrefetchCacheManager
{
    _Bool _addedToRegistrationHandler;
    PrefetchCacheManager2 *_fullscreenPlayerCache;
    PrefetchCacheManager2 *_previewPlayerCache;
    NSString *_cellCapSettingUserDefault;
    id <NrdControllerInternal> _nrdController;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <NrdControllerInternal> nrdController; // @synthesize nrdController=_nrdController;
@property(retain, nonatomic) NSString *cellCapSettingUserDefault; // @synthesize cellCapSettingUserDefault=_cellCapSettingUserDefault;
@property(nonatomic) _Bool addedToRegistrationHandler; // @synthesize addedToRegistrationHandler=_addedToRegistrationHandler;
@property(retain, nonatomic) PrefetchCacheManager2 *previewPlayerCache; // @synthesize previewPlayerCache=_previewPlayerCache;
@property(retain, nonatomic) PrefetchCacheManager2 *fullscreenPlayerCache; // @synthesize fullscreenPlayerCache=_fullscreenPlayerCache;
- (void)onNbpInitiatePlayback:(id)arg1;
- (void)handleDidActivateWithResult:(id)arg1;
- (void)handleProfileWillChange;
- (void)handleWillDeactivate;
- (void)stopAllCachingActivity;
- (void)stopAllCachingActivityInternal;
- (void)removeNrdRegistrationHandler;
- (_Bool)isFullscreenPlaybackOn:(_Bool)arg1;
- (id)playbackControllerForPlaybackRequest:(id)arg1;
- (id)playbackForPlaybackId:(id)arg1;
- (void)startClosingForMovieId:(id)arg1;
- (void)startPrefetchForPlaybackRequest:(id)arg1;
- (void)notifyBranchingMovieId:(id)arg1;
- (void)didBecomeActiveNotification:(id)arg1;
- (void)userDefaultsChanged:(id)arg1;
- (void)networkChanged:(id)arg1;
- (void)setShouldClearCache:(_Bool)arg1;
- (_Bool)isPlaybackOn;
- (_Bool)isPrefetchInflight:(unsigned long long)arg1;
- (void)createPlayerCacheWithMaxAllowedParallel4Preview:(long long)arg1 maxAllowedParallel4Fullscreen:(long long)arg2 cacheCapacity4Preview:(long long)arg3 cacheCapacity4Fullscreen:(long long)arg4 pendingQueueCapacity4Preview:(long long)arg5 pendingQueueCapacity4Fullscreen:(long long)arg6 andNrdController:(id)arg7;
- (int)version;
- (void)dealloc;
- (id)initWithMaxAllowedParallel4Preview:(long long)arg1 maxAllowedParallel4Fullscreen:(long long)arg2 cacheCapacity4Preview:(long long)arg3 cacheCapacity4Fullscreen:(long long)arg4 pendingQueueCapacity4Preview:(long long)arg5 pendingQueueCapacity4Fullscreen:(long long)arg6 andNrdController:(id)arg7;

@end

