//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFPrefetchCache/PrefetchCacheManager2Group.h>

@interface PrefetchCacheManager3Group : PrefetchCacheManager2Group
{
}

- (void)startClosingForPlaybackId:(id)arg1;
- (void)createPlayerCacheWithMaxAllowedParallel4Preview:(long long)arg1 maxAllowedParallel4Fullscreen:(long long)arg2 cacheCapacity4Preview:(long long)arg3 cacheCapacity4Fullscreen:(long long)arg4 pendingQueueCapacity4Preview:(long long)arg5 pendingQueueCapacity4Fullscreen:(long long)arg6 andNrdController:(id)arg7;
- (int)version;

@end

