//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFPrefetchCache/BasePrefetchCacheManager.h>

@class NSMutableArray, NSMutableDictionary, NSMutableSet, NflxTimer, PrefetchCacheManager2Group, StreamingPlaybackCacheQueue2;
@protocol NrdControllerInternal;

@interface PrefetchCacheManager2 : BasePrefetchCacheManager
{
    _Bool _isFullscreenCache;
    float _garbageCollectionIntervalMs;
    StreamingPlaybackCacheQueue2 *_cacheQueue;
    PrefetchCacheManager2Group *_prefetchCacheManagerGroup;
    id <NrdControllerInternal> _nrdController;
    unsigned long long _countingId;
    NSMutableSet *_branchingNarrativeMovieIds;
    long long _maxAllowedParallelPrefetch;
    long long _inflightParallelPrefetch;
    unsigned long long _pendingQueueCapacity;
    NSMutableArray *_pendingQueue;
    NSMutableDictionary *_garbageQueue;
    NflxTimer *_garbageCollectionTimer;
    long long _garbageCollectionTimerCounter;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isFullscreenCache; // @synthesize isFullscreenCache=_isFullscreenCache;
@property(nonatomic) long long garbageCollectionTimerCounter; // @synthesize garbageCollectionTimerCounter=_garbageCollectionTimerCounter;
@property(nonatomic) float garbageCollectionIntervalMs; // @synthesize garbageCollectionIntervalMs=_garbageCollectionIntervalMs;
@property(retain, nonatomic) NflxTimer *garbageCollectionTimer; // @synthesize garbageCollectionTimer=_garbageCollectionTimer;
@property(retain, nonatomic) NSMutableDictionary *garbageQueue; // @synthesize garbageQueue=_garbageQueue;
@property(retain, nonatomic) NSMutableArray *pendingQueue; // @synthesize pendingQueue=_pendingQueue;
@property(nonatomic) unsigned long long pendingQueueCapacity; // @synthesize pendingQueueCapacity=_pendingQueueCapacity;
@property(nonatomic) long long inflightParallelPrefetch; // @synthesize inflightParallelPrefetch=_inflightParallelPrefetch;
@property(nonatomic) long long maxAllowedParallelPrefetch; // @synthesize maxAllowedParallelPrefetch=_maxAllowedParallelPrefetch;
@property(retain, nonatomic) NSMutableSet *branchingNarrativeMovieIds; // @synthesize branchingNarrativeMovieIds=_branchingNarrativeMovieIds;
@property(nonatomic) unsigned long long countingId; // @synthesize countingId=_countingId;
@property(nonatomic) __weak id <NrdControllerInternal> nrdController; // @synthesize nrdController=_nrdController;
@property(nonatomic) __weak PrefetchCacheManager2Group *prefetchCacheManagerGroup; // @synthesize prefetchCacheManagerGroup=_prefetchCacheManagerGroup;
@property(retain, nonatomic) StreamingPlaybackCacheQueue2 *cacheQueue; // @synthesize cacheQueue=_cacheQueue;
- (void)dumpGarbageQueueInfo;
- (id)className;
- (void)setShouldClearCache:(_Bool)arg1;
- (void)onNbpInitiatePlayback:(id)arg1;
- (void)handleDidActivateWithResult:(id)arg1;
- (void)handleProfileWillChange;
- (void)handleWillDeactivate;
- (void)stopAllCachingActivity;
- (void)stopAllCachingActivityInternal;
- (void)clearCache;
- (void)stopInflightPrefetch;
- (_Bool)isFullscreenPlaybackOn:(_Bool)arg1;
- (id)playbackControllerForPlaybackRequest:(id)arg1;
- (id)playbackForPlaybackId:(id)arg1;
- (void)startClosingForPlaybackId:(id)arg1;
- (void)startClosingForMovieId:(id)arg1;
- (void)donePrefetchForPlaybackId:(id)arg1 withSuccess:(_Bool)arg2;
- (void)startPrefetchForPlaybackRequest:(id)arg1;
- (void)notifyBranchingMovieId:(id)arg1;
- (void)resumeCancelledPrefetch;
- (void)removeNonBranchingMovieFromCache:(id)arg1;
- (_Bool)isBranchingNarrative:(id)arg1;
- (void)prefetchNextMovie;
- (_Bool)isPlaybackUsable:(id)arg1 forRequest:(id)arg2;
- (id)findUsableCacheItemForMovieId:(id)arg1 platformPlaybackRequest:(id)arg2;
- (id)createStreamingPlaybackForPlaybackRequest:(id)arg1;
- (void)addDiscardedCacheItemIntoGarbageQueue:(id)arg1;
- (void)performGarbageCollection;
- (_Bool)isPlaybackOn;
- (_Bool)isPrefetchInflight:(unsigned long long)arg1;
- (int)version;
- (void)processExpiredEntries;
- (void)createCacheQueueWithCacheCapacity:(long long)arg1 andNrdController:(id)arg2;
- (void)dealloc;
- (id)initWithMaxAllowedParallelPrefetch:(long long)arg1 cacheCapacity:(long long)arg2 pendingQueueCapacity:(long long)arg3 prefetchCacheManagerGroup:(id)arg4 isFullscreenCache:(_Bool)arg5 andNrdController:(id)arg6;

@end

