//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFPrefetchCache/PrefetchCacheManager2.h>

@interface PrefetchCacheManager3 : PrefetchCacheManager2
{
}

- (void)startClosingForPlaybackId:(id)arg1;
- (void)startClosingForMovieId:(id)arg1;
- (id)findUsableCacheItemForMovieId:(id)arg1 platformPlaybackRequest:(id)arg2;
- (void)removeNonBranchingMovieFromCache:(id)arg1;
- (void)createCacheQueueWithCacheCapacity:(long long)arg1 andNrdController:(id)arg2;

@end

