//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFPrefetchCache/NSObject-Protocol.h>

@class NSString, PlatformPlaybackRequest;

@protocol PrefetchProtocol <NSObject>
- (id)playbackControllerForPlaybackRequest:(PlatformPlaybackRequest *)arg1;
- (void)clearManifestCache;
- (_Bool)isPlaybackOn;
- (_Bool)isPrefetchInflight:(unsigned long long)arg1;
- (void)startPrefetchForPlaybackRequest:(PlatformPlaybackRequest *)arg1;
- (void)notifyBranchingMovieId:(NSString *)arg1;
- (int)version;
@end

