//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PrimaryLolomoViewController.h"

#import "NFUICollectionViewCellManagerDelegate-Protocol.h"
#import "NFUIFeedViewControllerModelProtocol-Protocol.h"
#import "NFUIManagedFeedViewControllerDelegate-Protocol.h"

@class NFUICollectionViewCellManager, NFUIManagedFeedViewController, NSString, NavigationBarAppearanceManager;
@protocol NFUIFeedViewControllerModelFeedDelegate;

@interface PrimaryFeedLolomoViewController : PrimaryLolomoViewController <NFUIFeedViewControllerModelProtocol, NFUICollectionViewCellManagerDelegate, NFUIManagedFeedViewControllerDelegate>
{
    NFUIManagedFeedViewController *_feedViewController;
    NFUICollectionViewCellManager *_feedCellManager;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NFUICollectionViewCellManager *feedCellManager; // @synthesize feedCellManager=_feedCellManager;
@property(retain, nonatomic) NFUIManagedFeedViewController *feedViewController; // @synthesize feedViewController=_feedViewController;
- (void)paginateForAmount:(unsigned long long)arg1;
- (id)configureCellWithViewModel:(id)arg1 withModel:(id)arg2 forIndexPath:(id)arg3 forKind:(id)arg4 withCellManager:(id)arg5 shouldCacheResult:(_Bool *)arg6;
- (void)presentationTrackingTriggerFromScroll;
- (double)minimumInterItemSpacingForSection:(long long)arg1;
- (double)minimumLineSpacingForSection:(long long)arg1;
- (struct UIEdgeInsets)insetsForSection:(long long)arg1;
- (id)modelForIndexPath:(id)arg1 forKind:(id)arg2;
- (long long)numberOfItemsInSection:(long long)arg1;
- (long long)numberOfSections;
- (id)typeForIndexPath:(id)arg1 withKind:(id)arg2;
- (_Bool)pagesRemotely;
@property(retain, nonatomic) NFUICollectionViewCellManager *cellManager;
- (void)registerCells:(id)arg1;
- (id)createNewViewModel:(id)arg1;
- (id)nonManagedCollectionView;
- (id)collectionView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (void)viewDidLoad;
- (void)commonInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) __weak id <NFUIFeedViewControllerModelFeedDelegate> feedDelegate;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NavigationBarAppearanceManager *navBarManager;
@property(readonly) Class superclass;

@end

