//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NFALolomoViewController.h"

#import "NFUITopTenManagerDelegateProtocol-Protocol.h"

@class IntroCardDisplayController, NFUIUMAContext, NSString;

@interface PrimaryLolomoViewController : NFALolomoViewController <NFUITopTenManagerDelegateProtocol>
{
    _Bool _paginating;
    IntroCardDisplayController *_introCardDisplayController;
    NFUIUMAContext *_alertContext;
    double _lastOffset;
}

- (void).cxx_destruct;
@property(nonatomic) double lastOffset; // @synthesize lastOffset=_lastOffset;
@property(nonatomic) _Bool paginating; // @synthesize paginating=_paginating;
@property(retain, nonatomic) NFUIUMAContext *alertContext; // @synthesize alertContext=_alertContext;
@property(retain, nonatomic) IntroCardDisplayController *introCardDisplayController; // @synthesize introCardDisplayController=_introCardDisplayController;
- (void)handleDynamicTypeChange:(id)arg1;
- (void)topTenHasUpdatedVideos:(id)arg1;
- (_Bool)navBarManagerIsTransparent;
- (void)configureNavBarManager;
- (void)handleNavBarChange:(id)arg1;
- (void)configureWithViewModel:(id)arg1;
- (void)playbackFinished:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)willMoveToParentViewController:(id)arg1;
- (id)createCollectionViewWithFlowLayout:(id)arg1;
- (void)commonInit;
- (void)willEnterForeground:(id)arg1;
- (void)reloadViewModelInBackground:(id)arg1;
- (id)enqueueFetch:(id)arg1;
- (void)showRelevantMessagingIfNeeded:(id)arg1;
- (_Bool)isPrimaryLolomoVisible;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

