//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, _TtC62googlemac_iPhone_recaptcha_recaptcha_verification_handler_impl33RecaptchaVerificationHandlerSwift;

@interface RecaptchaVerificationHandler : NSObject
{
    _TtC62googlemac_iPhone_recaptcha_recaptcha_verification_handler_impl33RecaptchaVerificationHandlerSwift *_recaptchaVerificationHandlerImpl;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) long long timeout;
@property(readonly, copy, nonatomic) NSString *identifier;
- (void)verifyPin:(id)arg1 onVerification:(CDUnknownBlockType)arg2;
- (id)initWithVerificationToken:(id)arg1 siteKey:(id)arg2 identifier:(id)arg3 timeout:(long long)arg4;

@end

