//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFPlaylistGeneration/NSObject-Protocol.h>

@protocol HLSSegmentEnumeratorProtocol;

@protocol SidxInfoProtocol <NSObject>
@property(readonly, nonatomic) unsigned int timescale;
- (id <HLSSegmentEnumeratorProtocol>)segmentEnumerator;
- (double)maxIFrameSegmentDuration;
- (double)maxSegmentDuration;
- (double)duration;
- (void)addSidxEntryWithReferencedSize:(unsigned int)arg1 subsegmentDuration:(unsigned int)arg2 ssixEntryMoofAndIFrameSize:(unsigned int)arg3;
@end

