//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NSStreamDelegate-Protocol.h"

@class NSArray, NSInputStream, NSMutableString, NSOutputStream, NSString, NSTimer;
@protocol SKPSMTPMessageDelegate;

@interface SKPSMTPMessage : NSObject <NSCopying, NSStreamDelegate>
{
    _Bool isSecure;
    _Bool serverAuthCRAMMD5;
    _Bool serverAuthPLAIN;
    _Bool serverAuthLOGIN;
    _Bool serverAuthDIGESTMD5;
    _Bool server8bitMessages;
    _Bool _requiresAuth;
    _Bool _wantsSecure;
    _Bool _validateSSLChain;
    NSString *_login;
    NSString *_pass;
    NSString *_relayHost;
    NSArray *_relayPorts;
    NSString *_subject;
    NSString *_fromEmail;
    NSString *_toEmail;
    NSString *_ccEmail;
    NSString *_bccEmail;
    NSArray *_parts;
    double _connectTimeout;
    id <SKPSMTPMessageDelegate> _delegate;
    NSMutableString *_inputString;
    NSTimer *_connectTimer;
    NSTimer *_watchdogTimer;
    unsigned long long _sendState;
    NSInputStream *_inputStream;
    NSOutputStream *_outputStream;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSOutputStream *outputStream; // @synthesize outputStream=_outputStream;
@property(retain, nonatomic) NSInputStream *inputStream; // @synthesize inputStream=_inputStream;
@property(nonatomic) unsigned long long sendState; // @synthesize sendState=_sendState;
@property(retain, nonatomic) NSTimer *watchdogTimer; // @synthesize watchdogTimer=_watchdogTimer;
@property(retain, nonatomic) NSTimer *connectTimer; // @synthesize connectTimer=_connectTimer;
@property(retain, nonatomic) NSMutableString *inputString; // @synthesize inputString=_inputString;
@property(nonatomic) __weak id <SKPSMTPMessageDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double connectTimeout; // @synthesize connectTimeout=_connectTimeout;
@property(retain, nonatomic) NSArray *parts; // @synthesize parts=_parts;
@property(retain, nonatomic) NSString *bccEmail; // @synthesize bccEmail=_bccEmail;
@property(retain, nonatomic) NSString *ccEmail; // @synthesize ccEmail=_ccEmail;
@property(retain, nonatomic) NSString *toEmail; // @synthesize toEmail=_toEmail;
@property(retain, nonatomic) NSString *fromEmail; // @synthesize fromEmail=_fromEmail;
@property(retain, nonatomic) NSString *subject; // @synthesize subject=_subject;
@property(nonatomic) _Bool validateSSLChain; // @synthesize validateSSLChain=_validateSSLChain;
@property(nonatomic) _Bool wantsSecure; // @synthesize wantsSecure=_wantsSecure;
@property(nonatomic) _Bool requiresAuth; // @synthesize requiresAuth=_requiresAuth;
@property(retain, nonatomic) NSArray *relayPorts; // @synthesize relayPorts=_relayPorts;
@property(retain, nonatomic) NSString *relayHost; // @synthesize relayHost=_relayHost;
@property(retain, nonatomic) NSString *pass; // @synthesize pass=_pass;
@property(retain, nonatomic) NSString *login; // @synthesize login=_login;
- (void)cleanUpStreams;
- (void)connectionConnectedCheck:(id)arg1;
- (_Bool)sendParts;
- (void)parseBuffer;
- (id)formatAddresses:(id)arg1;
- (id)formatAnAddress:(id)arg1;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;
- (_Bool)send;
- (_Bool)preflightCheckWithError:(id *)arg1;
- (void)connectionWatchdog:(id)arg1;
- (void)stopWatchdog;
- (void)startLongWatchdog;
- (void)startShortWatchdog;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

