//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NFManifestAccess/_TtP16NFManifestCommon11NFStreamUrl_-Protocol.h>

@class NSDictionary, NSString;

@interface StreamUrlAccess : NSObject <_TtP16NFManifestCommon11NFStreamUrl_>
{
    NSDictionary *_dict;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSDictionary *dict; // @synthesize dict=_dict;
@property(readonly, copy, nonatomic) NSString *cdnIdentifier;
@property(readonly, copy, nonatomic) NSString *urlString;
- (id)initWithDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

