//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BasePrefetchCacheManager, NSMutableArray;
@protocol NrdControllerInternal;

@interface StreamingPlaybackCacheQueue2 : NSObject
{
    int _version;
    NSMutableArray *_streamingPlaybacks;
    unsigned long long _streamingPlaybacksCapacity;
    BasePrefetchCacheManager *_prefetchCacheManager;
    id <NrdControllerInternal> _nrdController;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <NrdControllerInternal> nrdController; // @synthesize nrdController=_nrdController;
@property(nonatomic) __weak BasePrefetchCacheManager *prefetchCacheManager; // @synthesize prefetchCacheManager=_prefetchCacheManager;
@property(nonatomic) unsigned long long streamingPlaybacksCapacity; // @synthesize streamingPlaybacksCapacity=_streamingPlaybacksCapacity;
@property(nonatomic) int version; // @synthesize version=_version;
@property(retain, nonatomic) NSMutableArray *streamingPlaybacks; // @synthesize streamingPlaybacks=_streamingPlaybacks;
- (id)description;
- (void)dump;
- (void)resumeCancelledPrefetch;
- (void)stopInflightPrefetch;
- (_Bool)hasPlayerStartedButNotClosed:(_Bool)arg1;
- (void)retrievePlaybackStatus:(id)arg1 canStayInCache:(_Bool *)arg2 canRemove:(_Bool *)arg3;
- (void)processExpiredEntries;
- (void)clear;
- (void)expireAll;
- (unsigned long long)count;
- (void)moveStreamingPlaybackToEnd:(id)arg1;
- (id)findByPlaybackId:(id)arg1;
- (id)lastObject;
- (void)enumerateByMovieId:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (id)findByMovieId:(id)arg1;
- (id)dequeue;
- (id)enqueue:(id)arg1;
- (void)removeStreamingPlaybackFromCache:(id)arg1;
- (void)dealloc;
- (id)initWithPrefetchCacheManager:(id)arg1 cacheCapacity:(long long)arg2 andNrdController:(id)arg3;

@end

