//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

#import "NFUITabBarDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class NFBarButtonItemCoordinator, NSString;
@protocol NFUITabBarItemProvider, UIGestureRecognizerDelegate;

@interface TabBarNavigationController : UINavigationController <NFUITabBarDelegate, UINavigationControllerDelegate>
{
    id <UIGestureRecognizerDelegate> _interactivePopDelegate;
    NFBarButtonItemCoordinator *_barButtonItemCoordinator;
}

+ (id)newWithViewController:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NFBarButtonItemCoordinator *barButtonItemCoordinator; // @synthesize barButtonItemCoordinator=_barButtonItemCoordinator;
@property(retain, nonatomic) id <UIGestureRecognizerDelegate> interactivePopDelegate; // @synthesize interactivePopDelegate=_interactivePopDelegate;
- (void)selectedTab:(id)arg1 comingFromTab:(id)arg2;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (id)targetForAction:(SEL)arg1 withSender:(id)arg2;
- (void)addDefaultItemsToNavigationItem:(id)arg1;
- (void)configureSecondaryNavForController:(id)arg1;
- (id)popToRootViewControllerAnimated:(_Bool)arg1;
- (id)popToViewController:(id)arg1 animated:(_Bool)arg2;
- (id)popViewControllerAnimated:(_Bool)arg1;
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;
- (void)setViewControllers:(id)arg1 animated:(_Bool)arg2;
- (void)viewDidLoad;
@property(readonly, nonatomic) id <NFUITabBarItemProvider> tabBarItemProvider;
- (id)initWithNavigationBarClass:(Class)arg1 toolbarClass:(Class)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

