//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NFManifestAccess/_TtP16NFManifestCommon13NFTextCdnInfo_-Protocol.h>

@class NSString;
@protocol _TtP16NFManifestCommon9NFCdnInfo_;

@interface TextCdnAccess : NSObject <_TtP16NFManifestCommon13NFTextCdnInfo_>
{
    long long cdnIdentifier;
    NSString *downloadableId;
    id <_TtP16NFManifestCommon9NFCdnInfo_> cdnInfo;
    NSString *urlString;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *urlString; // @synthesize urlString;
@property(retain, nonatomic) id <_TtP16NFManifestCommon9NFCdnInfo_> cdnInfo; // @synthesize cdnInfo;
@property(copy, nonatomic) NSString *downloadableId; // @synthesize downloadableId;
@property(nonatomic) long long cdnIdentifier; // @synthesize cdnIdentifier;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

