//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFManifestAccess/TrackAccess.h>

#import <NFManifestAccess/_TtP16NFManifestCommon11NFTextTrack_-Protocol.h>

@class NSArray, NSDictionary, NSString;
@protocol NFManifest;

@interface TextTrackAccess : TrackAccess <_TtP16NFManifestCommon11NFTextTrack_>
{
}

+ (long long)typeFromSubtitleTrackTypeString:(id)arg1;
+ (id)identifierForImageBased;
+ (id)identifierForWebVTT;
+ (id)identifierForRichWebVTT;
@property(readonly, nonatomic) unsigned long long streamCount;
@property(readonly, copy, nonatomic) NSArray *rankSortedCdnInfoArray;
- (void)enumerateStreams:(CDUnknownBlockType)arg1;
- (void)enumerateTextStreams:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) _Bool isClosedCaption;
@property(readonly, nonatomic) long long textTrackType;
@property(readonly, nonatomic) _Bool isForcedNarrative;
@property(readonly, copy, nonatomic) NSString *displayName;
@property(readonly, copy, nonatomic) NSString *languageCode;
@property(readonly, copy, nonatomic) NSString *language;
@property(readonly, nonatomic) _Bool hasRichWebVTT;
@property(readonly, nonatomic) _Bool hasWebVTT;
@property(readonly, nonatomic) _Bool hasImageBased;
- (id)downloadableIdForStreamIdentifier:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy, nonatomic) NSString *decryptionKey;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isEncrypted;
@property(readonly, copy, nonatomic) NSString *languageDescription;
@property(retain, nonatomic) id <NFManifest> manifest;
@property(readonly, nonatomic) _Bool native;
@property(readonly, copy, nonatomic) NSString *profile;
@property(readonly, copy, nonatomic) NSString *rawTrackType;
@property(readonly) Class superclass;
@property(retain, nonatomic) NSDictionary *track;
@property(readonly, copy, nonatomic) NSString *trackName;
@property(readonly, copy, nonatomic) NSString *trackUniqueIdentifier;

@end

