//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NFManifestAccess/_TtP16NFManifestCommon17NFTrackPreference_-Protocol.h>

@class NSDictionary, NSString;
@protocol _TtP16NFManifestCommon12NFAudioTrack_;

@interface TrackPreferenceAccess : NSObject <_TtP16NFManifestCommon17NFTrackPreference_>
{
    id <_TtP16NFManifestCommon12NFAudioTrack_> audioTrack;
    NSDictionary *_data;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *data; // @synthesize data=_data;
@property(retain, nonatomic) id <_TtP16NFManifestCommon12NFAudioTrack_> audioTrack; // @synthesize audioTrack;
@property(readonly, copy) NSString *description;
- (id)mediaIdComponentWithPrefix:(id)arg1;
@property(readonly, copy, nonatomic) NSString *subtitleMediaId;
@property(readonly, copy, nonatomic) NSString *videoMediaId;
@property(readonly, copy, nonatomic) NSString *audioMediaId;
@property(readonly, copy, nonatomic) NSString *mediaId;
@property(readonly, nonatomic) unsigned long long preferenceOrder;
- (id)initWithDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

