//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (NFLX)
+ (struct CGRect)nflx_localizedFrame:(struct CGRect)arg1 containerWidth:(double)arg2;
+ (struct CGSize)nflx_sizeForIndexedViewInSize:(struct CGSize)arg1 count:(unsigned long long)arg2;
+ (struct CGSize)nflx_sizeOfIndexedViewInSize:(struct CGSize)arg1 spacing:(double)arg2 rectRatio:(double)arg3 count:(unsigned long long)arg4;
+ (struct CGRect)nflx_rectForTileIndex:(long long)arg1 tileSize:(struct CGSize)arg2 containerWidth:(double)arg3;
+ (id)nflx_conformsCache;
- (_Bool)conformsToProtocol:(id)arg1;
- (id)layoutConstraintWithAnchorType:(id)arg1 toView:(id)arg2;
- (id)nflx_constraintsDictionaryForTypes:(id)arg1 withView:(id)arg2;
@property(nonatomic) double height;
@property(nonatomic) double width;
@property(nonatomic) struct CGSize size;
@property(nonatomic) struct CGPoint safeCenter;
@property(nonatomic) double bottom;
@property(nonatomic) double top;
@property(nonatomic) double right;
@property(nonatomic) double left;
- (void)nflx_removeAllSubviews;
- (void)nflx_bringToFront;
- (id)nflx_newWidthConstraint:(double)arg1 forSubView:(id)arg2;
- (id)nflx_newHeightConstraint:(double)arg1 forSubView:(id)arg2;
- (void)nflx_constrainToSize:(struct CGSize)arg1 forSubView:(id)arg2;
- (void)nflx_constrainToSize:(struct CGSize)arg1;
- (void)nflx_addFullFrameSubView:(id)arg1 alignedToTopLayoutAnchor:(id)arg2;
- (void)nflx_configureFullFrameConstraintsForSubview:(id)arg1 alignedToTopLayoutAnchor:(id)arg2;
- (void)nflx_configureFullWidthConstraintForSubView:(id)arg1;
- (void)nflx_configureFullHeightConstraintForSubView:(id)arg1;
- (void)nflx_configureFullFrameConstraintsForSubview:(id)arg1;
- (void)nflx_addFullFrameSubView:(id)arg1;
- (void)nflx_configureCenteredConstraintsForSubView:(id)arg1;
- (void)nflx_centerInSuperview;
- (void)setHiddenAnimated:(_Bool)arg1;
- (void)applyCornerRadiusType:(long long)arg1 toLayer:(id)arg2 ignoringABTest:(_Bool)arg3;
- (void)applyCornerRadiusType:(long long)arg1 toLayer:(id)arg2;
- (void)configureCornerRadiusWithType:(long long)arg1;
@end

