//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NFManifestAccess/TrackAccess.h>

#import <NFManifestAccess/_TtP16NFManifestCommon12NFVideoTrack_-Protocol.h>

@class NSDictionary, NSString;
@protocol NFManifest;

@interface VideoTrackAccess : TrackAccess <_TtP16NFManifestCommon12NFVideoTrack_>
{
}

- (id)getPsshStringForStream:(id)arg1;
- (id)drmHeaders;
@property(readonly, nonatomic) _Bool isEncrypted;
@property(readonly, copy, nonatomic) NSString *keyId;
- (void)enumerateStreams:(CDUnknownBlockType)arg1;
- (void)enumerateVideoStreams:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy, nonatomic) NSString *decryptionKey;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, copy, nonatomic) NSString *language;
@property(readonly, copy, nonatomic) NSString *languageCode;
@property(readonly, copy, nonatomic) NSString *languageDescription;
@property(retain, nonatomic) id <NFManifest> manifest;
@property(readonly, nonatomic) _Bool native;
@property(readonly, copy, nonatomic) NSString *profile;
@property(readonly, copy, nonatomic) NSString *rawTrackType;
@property(readonly, nonatomic) unsigned long long streamCount;
@property(readonly) Class superclass;
@property(retain, nonatomic) NSDictionary *track;
@property(readonly, copy, nonatomic) NSString *trackName;
@property(readonly, copy, nonatomic) NSString *trackUniqueIdentifier;

@end

